marlin-succinct/circuits/src/index.rs
marlin-succinct/commitment/src/commitment.rs
marlin-succinct/commitment/src/urs.rs
marlin-succinct/commitment/tests/batch.rs
marlin-succinct/protocol/src/prover.rs
marlin-succinct/protocol/src/verifier.rs
marlin-succinct/protocol/tests/group_addition.rs

This PR makes it possible to pass in a previously generated URS into the index create function.

Pass in URS to index create function

---

dlog/circuits/src/compiled.rs
dlog/circuits/src/index.rs
dlog/protocol/src/prover.rs
dlog/protocol/src/verifier.rs
pairing/circuits/src/compiled.rs
pairing/circuits/src/index.rs
pairing/protocol/src/prover.rs
pairing/protocol/src/verifier.rs

This PR proposes implementation of 6K->3K polynomial degree reduction in both Marlins

this commits 6K->3K polynomial degree reduction

---

dlog/protocol/src/prover.rs
dlog/protocol/src/verifier.rs

This PR changes a bit how things are absorbed into the random oracle and adds a few new entries to the oracles struct for the dlog based argument.

tweaks to how oracles are handled in Dlog based argument

---

dlog/protocol/src/marlin_sponge.rs
dlog/tests/batch.rs
dlog/tests/group_addition.rs
oracle/src/lib.rs
oracle/src/marlin_sponge.rs
pairing/protocol/src/marlin_sponge.rs
pairing/protocol/src/prover.rs
pairing/protocol/src/verifier.rs
pairing/tests/group_addition.rs

This PR makes a common "marlin sponge" module that is shared by both proof systems

 Use same marlin sponge

---

dlog/plonk/src/prover.rs
dlog/plonk/src/verifier.rs
dlog/tests/poseidon_bn382.rs
dlog/tests/poseidon_tweedledee.rs
dlog/tests/poseidon_tweedledum.rs
dlog/tests/turbo_plonk.rs

Plonk Prover, Verifier and tests have been updated for recursion with previous proof challenges

Plonk prover/verifier support for recursion with previous proof challenges

---

circuits/plonk/src/constraints.rs

This PR corrects PR-50 merge error.

correct merge error for pr-50

---

circuits/plonk/src/constraints.rs
circuits/plonk/src/polynomials/addition.rs
circuits/plonk/src/polynomials/endosclmul.rs
circuits/plonk/src/polynomials/permutation.rs
circuits/plonk/src/polynomials/poseidon.rs
circuits/plonk/src/polynomials/varbasemul.rs
dlog/commitment/src/commitment.rs
dlog/plonk/src/index.rs
dlog/plonk/src/lib.rs
dlog/plonk/src/prover.rs
dlog/plonk/src/range.rs
dlog/plonk/src/verifier.rs
dlog/tests/batch.rs
dlog/tests/marlin_group_addition.rs
dlog/tests/marlin_reduction.rs
dlog/tests/poseidon_bn382.rs
dlog/tests/poseidon_tweedledee.rs
dlog/tests/poseidon_tweedledum.rs
dlog/tests/turbo_plonk.rs

this implements the following:
1. zk for polys before interpolation
2. fix some broken tests
3. correct commitment schema
4. implement the use the correct endoscalar
5. correct scaling of custom constraint checks with the correct powers of alpha

latest changes

---

BUILD.bazel
WORKSPACE.bazel
bzl/cargo/Cargo.lock
bzl/cargo/crates.bzl
bzl/cargo/remote/BUILD.crossbeam-channel-0.5.0.bazel
bzl/cargo/remote/BUILD.crossbeam-epoch-0.9.1.bazel
bzl/cargo/remote/BUILD.crossbeam-utils-0.8.1.bazel
bzl/cargo/remote/BUILD.memoffset-0.6.1.bazel
bzl/cargo/remote/BUILD.rayon-core-1.9.0.bazel
version.ml

* this is a workaround until we get Bazel version stamping implemented

temporarily export version.ml to mina zexe_backend

---

oracle/tests/poseidon_tests.rs

* Added 5-wire poseidon unit tests
* Added 3-wire poseidon unit tests
* Created simple poseidon unit test framework

Implemented 3- and 5-wire Poseidon unit tests

---

Cargo.toml
dlog/Cargo.toml
dlog/commitment/Cargo.toml
groupmap/Cargo.toml
groupmap/src/lib.rs
groupmap/tests/groupmap.rs

step 3 needs to land before this PR: https://github.com/o1-labs/marlin/pull/110
This also updates the zexe backend

[step 4] groupmap moved zexe/groupmap to our workspace

---

bzl/cargo/Cargo.toml
circuits/plonk-5-wires/Cargo.toml
circuits/plonk-5-wires/src/constraints.rs
circuits/plonk/Cargo.toml
circuits/plonk/src/constraints.rs
dlog/commitment/Cargo.toml
dlog/commitment/src/srs.rs

This is by @mimoo, opening for visibility and review

Update blake2 to fix build issue

---

.github/workflows/coverage.yml

Adds code coverage via https://app.codecov.io/gh/o1-labs/proof-systems

[CI] code coverage

---

.github/workflows/rustdoc.yml

[CI] fix nightly

---

curves/Cargo.toml
curves/src/pasta/curves/tests.rs
curves/src/pasta/fields/tests.rs

fixes https://github.com/o1-labs/marlin/issues/115

[step 7] re-adding tests after zexe->arkworks

---

dlog/commitment/src/commitment.rs

For some reason the linter in vscode is confused by the `max()` function there. This makes the code uglier, but fixes the only lint issue.

[easy][commitment] rephrase what the linter doesn't like

---

.github/workflows/rust.yml
circuits/kimchi/src/expr.rs
circuits/kimchi/src/gate.rs
circuits/kimchi/src/nolookup/constraints.rs
circuits/kimchi/src/polynomials/chacha.rs
circuits/kimchi/src/polynomials/endomul_scalar.rs
circuits/kimchi/src/polynomials/lookup.rs
circuits/kimchi/src/polynomials/permutation.rs
circuits/kimchi/src/polynomials/varbasemul.rs
circuits/plonk/src/lib.rs
dlog/commitment/src/combine.rs
dlog/commitment/src/commitment.rs
dlog/commitment/src/srs.rs
dlog/commitment/tests/commitment.rs
dlog/kimchi/src/index.rs
dlog/kimchi/src/prover.rs
dlog/kimchi/src/verifier.rs
dlog/kimchi/tests/endomul_scalar.rs
dlog/plonk/src/lib.rs
dlog/plonk/src/prover.rs
dlog/plonk/src/verifier.rs
dlog/tests/batch_5_wires.rs

This enforces clippy in CI for the whole workspace.
Note that I ignore some of the lints for now, but we should track and fix them when we get time to do it (https://github.com/o1-labs/proof-systems/issues/225). At least we won't get new lints!

[kimchi][CI] enabling clippy for the whole workspace (except plonkv1 crates)

---

LICENSE

closes https://github.com/o1-labs/proof-systems/issues/222

adding Apache 2.0 license

---

circuits/kimchi/Cargo.toml
circuits/plonk/Cargo.toml
curves/Cargo.toml
ocaml/ocaml-gen/Cargo.toml
ocaml/ocaml-gen/derive/Cargo.toml
ocaml/tests/Cargo.toml
oracle/Cargo.toml
utils/Cargo.toml

Supplement https://github.com/o1-labs/proof-systems/pull/234 and add license field to all Cargo.toml files.

add license to all Cargo.toml

---

.github/workflows/benches.yml
dlog/kimchi/README.md
dlog/kimchi/benches/proof_criterion.rs
dlog/kimchi/benches/proof_iai.rs
dlog/kimchi/src/bench.rs

Hopefully this will allow benchmarking to work in CI as well. The benchmark is still not great for reasons listed in https://github.com/o1-labs/proof-systems/issues/249

[kimchi] better benchmark

---

circuits/kimchi/src/gate.rs
circuits/kimchi/src/gates/endosclmul.rs
circuits/kimchi/src/gates/varbasemul.rs
circuits/kimchi/src/nolookup/constraints.rs
circuits/kimchi/src/polynomials/endomul_scalar.rs
circuits/kimchi/src/polynomials/endosclmul.rs
circuits/kimchi/src/polynomials/varbasemul.rs
dlog/kimchi/src/prover.rs
dlog/kimchi/src/verifier.rs
dlog/kimchi/tests/endomul_scalar.rs
dlog/tests/endomul.rs
dlog/tests/varbasemul.rs

This PR improves the GateType variant names as suggested by Izzy.
Closes #251

Improved GateType enum variant names

---

circuits/kimchi/Cargo.toml
circuits/kimchi/src/nolookup/constraints.rs
curves/Cargo.toml
dlog/Cargo.toml
dlog/commitment/Cargo.toml
dlog/commitment/src/srs.rs
dlog/kimchi/Cargo.toml
groupmap/Cargo.toml
oracle/Cargo.toml
signer/Cargo.toml
signer/src/schnorr.rs

updating dependencies

---

ocaml/ocaml-gen/src/lib.rs
rust-toolchain.toml

bump rust version to 1.57.0

---

.github/workflows/rust.yml
dlog/kimchi/src/index.rs
oracle/src/poseidon.rs
rust-toolchain.toml

bumping rust version, and making sure that clippy is clean (I forgot to run clippy in deny mode in CI)

bumping rust version to 1.58.0

---

kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/index.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs
utils/src/evaluations.rs

Trying to declutter https://github.com/o1-labs/proof-systems/pull/216 by moving some of the unrelated changes here

Various cleanups

---

kimchi/src/circuits/gates/varbasemul.rs
kimchi/src/tests/mod.rs

I think I screwed up when I moved the tests from outside the crate to a submodule, fixing this 😳

re-add tests

---

utils/src/field_helpers.rs

* Make FieldHelpers work on FftField
* Added to/from bits interface
* Extend and improve unit tests
Closes #306

Improvements to FieldHelpers

---

utils/src/field_helpers.rs

Make FieldHelpers work with Field instead of FftField

---

kimchi/src/circuits/argument.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/complete_add.rs
kimchi/src/circuits/polynomials/endomul_scalar.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/varbasemul.rs

Convert Argument trait Field associated type to trait bound

---

.github/workflows/gh-page.yml

[CI] fix book

---

Cargo.toml
tools/kimchi-visu/Cargo.toml
tools/kimchi-visu/README.md
tools/kimchi-visu/src/assets/script.js
tools/kimchi-visu/src/assets/template.html
tools/kimchi-visu/src/lib.rs
tools/kimchi-visu/src/main.rs

handy tool to visualize a circuit

added tool to visualize a circuit

---

.github/workflows/gh-page.yml
book/assets/css/mdbook-admonish.css
book/book.toml
book/specifications/kimchi/Specification.toml
book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/circuits/gates/poseidon.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/poseidon.rs

Specifying two gates in this PR. Rest incoming.

[specs][kimchi] specify poseidon + double generic gates

---

kimchi/src/alphas.rs
kimchi/src/circuits/argument.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/complete_add.rs
kimchi/src/circuits/polynomials/endomul_scalar.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/lookup.rs
kimchi/src/circuits/polynomials/permutation.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/varbasemul.rs
oracle/src/poseidon.rs

helps https://github.com/o1-labs/proof-systems/issues/346

usize -> u64 or u32

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/prover.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/poseidon.rs

will write a PR description in 3, 2, 1, ...
closes https://github.com/o1-labs/proof-systems/issues/356

[tests] create a test for public inputs

---

book/specifications/kimchi/Specification.toml
book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/bench.rs
kimchi/src/circuits/constraints.rs
kimchi/src/index.rs
kimchi/src/lib.rs
kimchi/src/linearization.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/poseidon.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs
tools/kimchi-visu/src/lib.rs
tools/kimchi-visu/src/main.rs

To make it easier to spec the constraint system and index setup:
* index -> prover_index and verifier_index
* index::linearization -> linearization
This also adds some spec comment in order to fill the spec out. More to come.

[specs][kimchi] index and constraint system parts

---

README.md
kimchi/src/alphas.rs
kimchi/src/bench.rs
kimchi/src/bin/flamegraph.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/lib.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
ocaml/ocaml-gen/derive/src/lib.rs
ocaml/ocaml-gen/src/lib.rs
poly-commitment/src/commitment.rs
tools/kimchi-visu/src/witness.rs
utils/src/serialization.rs

nicer README with example, and fixed all the `cargo doc` warnings

update the README & fix cargo doc

---

kimchi/src/prover.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
poly-commitment/src/lib.rs
poly-commitment/tests/commitment.rs

1. Add module `evaluation_proof`
2. Move OpeningProof and open into `evaluation_proof.rs`
3. Change `kimchi/src/prover.rs` accordingly

[Commitment] Move OpeningProof and open to evaluation_proof.rs

---

README.md
groupmap/src/lib.rs

Added groupmap description to README.md and added some preliminary comments to groupmap lib.rs from snarky Ocaml implementation.

Groupmap docs

---

book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/prover.rs

addresses feedback from @querolita on specs

[specs] address feedback

---

oracle/Cargo.toml
oracle/export_test_vectors/src/main.rs

fix issue https://github.com/o1-labs/proof-systems/issues/398 
not sure if i should remove `--all-features` in the ci as ocaml seems to be relying on this. lmk on this
also im sorry @mimoo for missing out the println message. hopefully you are ok with me fixing in the same pr.

change cargo toml in oracle + change println message

---

utils/src/dense_polynomial.rs

[easy][utils][dense_polynomial] improve doc + code

---

book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/lookup.rs
kimchi/src/circuits/polynomials/permutation.rs
kimchi/src/error.rs
kimchi/src/prover.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/verifier.rs
poly-commitment/src/commitment.rs

specifying the verifier.
Also made a few changes as I was doing that:
* removed an assert, and made the verifier return its own error type
* created a `verify` for a single proof, applied it to most tests
* added some doc / renamed some variables

[specs][kimchi] spec the verifier

---

kimchi/src/verifier.rs

reverting some of the changes in https://github.com/o1-labs/proof-systems/pull/366/files#diff-fc95db4d289fd33bc7fbefe8a487926ce8b47cbe71f047a1dd6933d7444b5d5aL319
as the OCaml side does need this information

[kimchi] re-adding combined_inner_product

---

.github/workflows/rust.yml
book/specifications/kimchi/Specification.toml
book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/chacha.rs

* simply turns some doc into spec doc
* also fixes CI that didn't catch a spec error

[spec][chacha] add chacha to spec

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

Cleaned up some code as I was going through it.
Low priority, as it will probably mess up a bunch of other PRs from @mrmr1993

[lookup] cleaning constraints

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/varbasemul.rs

This is one of the gates that were pending to be specified.
I removed the previous version of the documentation comments as they were referring to an outdated version of the constraints and layout.
The current module only contains some short documentation comments, and all the details of it are written with `cargo-spec` type of comments.

specification of varbasemul gate

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/varbasemul.rs

This is a specification of the endosclmul gate. I reused some equations from the older version of varbasemul that match these ones instead, updating them with the current version of the code.

specification of endosclmul

---

kimchi/src/circuits/expr.rs

two tests:
* make sure that linearize fails if we multiply two unevaluated commitments
* make sure that deriving the evaluation form of a polynomial in expr form fails if d8 isn't large enough to hold it

[expr] implement negative tests

---

book/src/SUMMARY.md
book/src/rfcs/3-lookup.md

looks like this: https://hackmd.io/LJQDwtJeSeKKg2zYBCw7-w?view

[RFC] Integration of plookup in kimchi

---

book/src/introduction.md

as we talked during our standup

[easy][book] added disclaimer

---

book/specifications/kimchi/template.md
book/src/specs/kimchi.md

- split the protocol diagram into section after discussion with @jspada 
- separate proof data structure into a separate section to easily refer to it

[easy][specs][kimchi] update protocol diagram

---

kimchi/src/circuits/expr.rs

Fix lagrange `l0_1` commenting and use `EvaluationDomain::elements()`

---

book/assets/css/mdbook-admonish.css
book/book.toml
book/mdbook-admonish.css

There seems to be a problem regarding the version of `mdbook-admonish`, this PR tries to fix it. 
The details of the error are here: 
https://github.com/o1-labs/proof-systems/runs/6231484369?check_suite_focus=true

fixing mdbook admonish error

---

kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/prover.rs

address PR feedback

---

book/src/specs/kimchi.md
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/error.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

This adds the missing evaluation proofs for lookup.

[lookup] add evaluation proofs in the protocol

---

kimchi/src/prover.rs

We previously tested each gate/argument constraints via something like this:
```rust
if cfg!(test) {
let (_, res) = evaluation
.interpolate_by_ref()
.divide_by_vanishing_poly(index.cs.domain.d1)
.unwrap();
assert!(res.is_zero());
}
```
I moved this to a macro to simplify the code, and used `cfg!(debug_assertions)` so that we get this behavior whenever we are not running in release.
Also, I removed a bunch of `drop` to replace them with scoped `{ ... }` which is exactly the same but cleaner

[prover] move tests to debug_assertions

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/domain_constant_evaluation.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/permutation.rs
kimchi/src/prover_index.rs
poly-commitment/src/commitment.rs

https://github.com/o1-labs/proof-systems/issues/425

[easy] domain.size as usize -> domain.size()

---

kimchi/src/circuits/lookup/index.rs

Implemented the suggestion from @mrmr1993  (https://github.com/o1-labs/proof-systems/pull/536#discussion_r865077433)

[easy][lookup] If a table has ID 0, then it must have a zero entry

---

kimchi/src/circuits/expr.rs

* Switch to faster way of computing lagrange basis
g^{n-i} = 1/g^i
* Fix missing spots where we should use this
closes #589

Compute unnormalized lagrange basis in a faster way

---

kimchi/src/circuits/expr.rs

Add unnormalized lagrange basis unit test

---

kimchi/Cargo.toml
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/linearization.rs
kimchi/src/prover.rs
kimchi/src/verifier_index.rs

This PR builds upon #581 to simplify the logic around the 'lookup constraint system' using the explicit lookup patterns.

Refactors using explicit lookup patterns

---

kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/linearization.rs
kimchi/src/prover.rs

This PR builds upon #582. This fixes #580.

Move `runtime_tables`, `runtime_table_offset` into `LookupConstraintSystem`

---

book/src/SUMMARY.md
book/src/specs/urs.md

still TODO items but it's something

[specs] added spec for URS

---

book/book.toml

Fix admonish error after merging

[easy] fix admonish error

---

book/book.toml

The previous fix didn't really fix the mdbook-admonish error, I hope this one does.

fix admonish

---

book/book.toml
book/mdbook-admonish.css

I have updated mdbook-admonish to version 1.7.0 which changes book.toml to 2.0.0. I think this should solve the error.

installing mdbook-admonish again

---

book/src/rfcs/3-lookup.md

Solves #613 as discussed with @mimoo.

add missing elements in plookup example

---

circuit-construction/src/lib.rs
circuit-construction/tests/sudoku.rs

This PR aims to fix the sudoku test, so that the test can be used as a baseline for other changes.
- fix some of the kombucha APIs
- fix the sudoku test
- use a new sudoku example as the previous one seems to have no solution for diagonal rules
- the "equals" API seems to have WIP code, for now this PR reverts the WIP changes in the "equals" to previous code

[kombucha] Fix sudoku test

---

cairo/src/helper.rs
circuit-construction/src/constants.rs
circuit-construction/src/lib.rs
circuit-construction/src/prover.rs
circuit-construction/src/tests/example_proof.rs
curves/src/pasta/curves/pallas.rs
curves/src/pasta/curves/tests.rs
curves/src/pasta/curves/vesta.rs
groupmap/tests/groupmap.rs
kimchi/src/bench.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/prover_index.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/poseidon.rs
kimchi/src/tests/serde.rs
kimchi/src/tests/varbasemul.rs
poly-commitment/src/commitment.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs
signer/src/lib.rs
tools/kimchi-visu/src/main.rs
utils/src/field_helpers.rs

renamed affine as per issue title #692 .

renaming affine try#3

---

kimchi/src/oracles.rs

https://github.com/MinaProtocol/mina/pull/11576

[ocaml] add missing ocaml derivations

---

book/src/specs/kimchi.md
kimchi/src/prover.rs

specify some parts of the runtime tables

[lookup][runtime] specify

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/range_check/circuitgates.rs

Found a few mistakes in spec and fixed formatting.

Fixes to range check specification

---

kimchi/src/verifier.rs
poly-commitment/src/commitment.rs

This had G when it could have F

remove unnecessary bound on function

---

poly-commitment/src/commitment.rs

This PR replaces the two distinct implementations of masking with a single implementation.

Replace body of `mask` with call to `mask_custom`

---

kimchi/src/circuits/expr.rs
kimchi/src/snarky/constraint_system.rs

* Create ArithmeticOps trait
* Fixed some unrelated cargo doc warnings
Closes #726

Add interface for reusing constraint code for witness computation

---

Cargo.lock
circuit-construction/Cargo.toml
kimchi/Cargo.toml
poly-commitment/Cargo.toml
signer/Cargo.toml
tools/kimchi-visu/Cargo.toml

Remove the `array-init` crates from toml files

---

kimchi/src/circuits/argument.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/complete_add.rs
kimchi/src/circuits/polynomials/endomul_scalar.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/linearization.rs

looks like https://github.com/o1-labs/proof-systems/pull/758 introduced a breaking change in the OCaml code. This fixes that. The fix is easy: revert back to `PrimeField`.

[expr] fix bug from #758

---

circuit-construction/src/writer.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/circuits/wires.rs
kimchi/src/snarky/constraint_system.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/lookup.rs
kimchi/src/tests/varbasemul.rs

This will facilitate refactors on the gate, for example https://github.com/o1-labs/proof-systems/pull/793

[easy][gate] create constructor for gate

---

utils/src/chunked_evaluations.rs
utils/src/lib.rs

**What's been done:**
- Add a new type `ChunkedEvaluations` for the `ProofEvaluations` refactor
Reference: #759

Add the `ChunkedEvaluations` type

---

book/src/kimchi/arguments.md

It is not being rendered correctly in https://o1-labs.github.io/proof-systems/kimchi/arguments.html

[docs] Fix reference to `kimchi.png` in `arguments.md`

---

.github/workflows/rust.yml

Integrate the beta clippy in CI

---

book/src/fundamentals/zkbook_commitment.md

**What's been done:** 
Fix the wrong formulas in [zkbook_commitment.md](https://github.com/o1-labs/proof-systems/blob/master/book/src/fundamentals/zkbook_commitment.md)
**Reference:** #829

Fix the errors in `zkbook_commitment` book

---

.github/workflows/rust.yml
hasher/src/roinput.rs
kimchi/src/bench.rs
kimchi/src/circuits/expr.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/serde.rs
kimchi/src/tests/turshi.rs
kimchi/src/tests/xor.rs
signer/tests/signer.rs
signer/tests/transaction.rs
utils/src/dense_polynomial.rs
utils/src/field_helpers.rs

This PR
* updates CI to apply clippy to all targets in the repo
* applies its suggestions.

Apply clippy to all repo targets

---

kimchi/src/verifier_index.rs
poly-commitment/src/commitment.rs
utils/src/math.rs

[commitment] inline commit_helper and factor out div_ceil fn

---

book/src/specs/poseidon.md

adding more to the poseidon spec for https://github.com/ethereum/EIPs/pull/5988

[specs] add more to the Poseidon spec

---

.github/workflows/rust.yml
kimchi/src/circuits/polynomials/rot.rs
utils/Cargo.toml

This PR
* adds a CI job to stop us from breaking things that don't have tests
* fixes the target that broke.

Un-break utils

---

book/src/rfcs/foreign_field_mul.md
book/src/specs/kimchi.md
kimchi/src/circuits/argument.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/foreign_field_add/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/foreign_field_mul/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/gadget.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/rot.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/xor.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/tests/and.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/xor.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs

Support multiple foreign field moduli per circuit

---

book/src/rfcs/foreign_field_mul.md
book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/foreign_field_mul/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/witness.rs
kimchi/src/tests/foreign_field_mul.rs

This needs to be merged after #924 
Closes #930

Non-native field multiplication optimization 2

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/range_check/circuitgates.rs

Add some missing documentation.

Document compact limbs mode of multi-range-check gadget

---

kimchi/src/circuits/constraints.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs

Essential for getting test coverage of plookup constraints

Disable gates checks mode

---

kimchi/src/prover.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/framework.rs

* Useful for testing plookup constraints

Disable custom constraints option for testing

---

kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/tests/foreign_field_mul.rs
utils/src/math.rs

Special thanks to @querolita for solving the wraparound instances for the tests!
Closes #953

Fix non-native field multiplication wraparound soundness regression

---

poseidon/Cargo.toml
poseidon/src/sponge.rs

* The code for this feature is conditionally compiled only if
* It is a non-release build AND
* The "debug_sponge" feature is enabled
* It prints the sponge trace to stdout to aid debugging certain complex scenarios
Closes #968

Add debug sponge feature

---

book/src/fundamentals/custom_constraints.md
book/src/fundamentals/zkbook.md
book/src/fundamentals/zkbook_commitment.md
book/src/fundamentals/zkbook_groups.md
book/src/fundamentals/zkbook_ips.md

Fix: typos

---

book/src/specs/kimchi.md
circuit-construction/src/prover.rs
circuit-construction/src/tests/example_proof.rs
kimchi/benches/proof_criterion.rs
kimchi/benches/proof_iai.rs
kimchi/src/bench.rs
kimchi/src/bin/flamegraph.rs
kimchi/src/oracles.rs
kimchi/src/proof.rs
kimchi/src/prover.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/serde.rs
kimchi/src/verifier.rs

Move public input out of ProverProof type into an argument of verify

---

kimchi/benches/proof_criterion.rs
kimchi/benches/proof_iai.rs
kimchi/src/bench.rs
kimchi/src/bin/flamegraph.rs
kimchi/src/oracles.rs
kimchi/src/tests/serde.rs
kimchi/src/verifier.rs

Follow-up: address nits from #976.

Use slice references in function arg types, verifier::Context

---

kimchi/src/prover.rs

the changes for https://github.com/o1-labs/proof-systems/pull/976 and https://github.com/o1-labs/proof-systems/pull/982 are moot if we leave the bindings alone : )
mina side: https://github.com/MinaProtocol/mina/pull/12609

[ocaml] fix bindings

---

book/src/SUMMARY.md

Otherwise it doesn't show in the specs.

[EASY] Update name of FFAdd RFC

---

signer/README.md
signer/src/keypair.rs
signer/src/pubkey.rs
signer/src/seckey.rs

Improve serialization for SecKey, PubKey and Keypair

---

Cargo.lock
Cargo.toml
internal-tracing/Cargo.toml
internal-tracing/src/lib.rs
kimchi/Cargo.toml
kimchi/src/prover.rs

Required for https://github.com/MinaProtocol/mina/pull/12875

Internal tracing for the prover

---

signer/src/seckey.rs

Add base58 encode/decode to SecKey in signer crate.

Add base58 encode/decode to secret key

---

Cargo.lock
internal-tracing/Cargo.toml
kimchi/Cargo.toml
kimchi/src/circuits/lookup/runtime_tables.rs
poly-commitment/Cargo.toml
poseidon/Cargo.toml

Cherry-picked from dannywillems/lookup.
Built on top of #1113

Expose runtime table types to ocaml

---

Cargo.lock
internal-tracing/Cargo.toml
kimchi/Cargo.toml
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/lookup/tables/mod.rs
poly-commitment/Cargo.toml
poseidon/Cargo.toml

Built on top of https://github.com/o1-labs/proof-systems/pull/1112.
Cherry-picked from dannywillems/lookup

Expose lookup tables types ocaml

---

Cargo.lock
internal-tracing/Cargo.toml
kimchi/Cargo.toml
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/lookup/tables/mod.rs
poly-commitment/Cargo.toml
poseidon/Cargo.toml

Included in the PR train, depends on https://github.com/o1-labs/proof-systems/pull/1114

Expose runtime table spec types ocaml

---

kimchi/src/tests/framework.rs
kimchi/src/tests/lookup.rs

Fix https://github.com/MinaProtocol/mina/issues/13607

Runtime table test: randomize queries and negative tests

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/rot.rs
kimchi/src/tests/rot.rs

This is the Rust counterpart of this [Mina PR](https://github.com/MinaProtocol/mina/pull/13491)
It is not necessary right now, as we are not using rust gadgets but only Snarky's. Nonetheless, it is good to have the same code on both sides so it is easier to maintain.

Fix potential soundness bug in rotation

---

kimchi/src/circuits/lookup/lookups.rs
kimchi/src/verifier_index.rs

Related to https://github.com/MinaProtocol/mina/pull/13882.

[develop] Add lookup verifier index

---

kimchi/src/circuits/lookup/lookups.rs
kimchi/src/verifier_index.rs

Berkeley counterpart of https://github.com/o1-labs/proof-systems/pull/1182

[berkeley] Add lookup verifier index 

---

kimchi/src/tests/lookup.rs

Fix [#13928](https://github.com/MinaProtocol/mina/issues/13928)

More negative tests for runtime tables

---

.github/workflows/rust.yml
kimchi/src/tests/framework.rs
poly-commitment/src/combine.rs

Fix https://github.com/MinaProtocol/mina/issues/13929

[main] Add rust 1.70 in CI

---

book/src/specs/kimchi.md
kimchi/src/circuits/berkeley_columns.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/mod.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/error.rs
kimchi/src/linearization.rs
kimchi/src/proof.rs
kimchi/src/prover_index.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs

This PR ports over some changes necessary for using the expression framework for the MIPS VM, abstracting the expression framework over the columns.

Abstract expr over columns

---

optimism/src/cannon.rs
optimism/src/main.rs
optimism/src/mips/witness.rs

Add symbol to debugging/info output

Support for `meta.json` file

---

Cargo.toml

https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html

[develop] Fix resolver warnings

---

Cargo.toml

https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html

[master] Fix resolver warnings

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR implements the skeleton of the VM interpreter, with all instructions stubbed out, so that each individual instruction can be added as a separate PR on top.

Skeleton of the VM interpreter

---

.gitignore
optimism/run-vm.sh
optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

See https://max.cs.kzoo.edu/cs230/Resources/MIPS/MachineXL/InstructionFormats.html
For the instruction I and J, we will simply add the relevant parts.
The next PR will be the jump instruction.

Interpreter: add InstructionParts and decode it

---

book/src/specs/kimchi.md
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/circuits/lookup/tables/range_check.rs
kimchi/src/circuits/lookup/tables/xor.rs
kimchi/src/error.rs
kimchi/src/precomputed_srs.rs
kimchi/src/prover_index.rs
kimchi/src/tests/and.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/lookup.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/xor.rs

This reverts PR #1263, which both breaks Mina and disables some behaviour that we actually want.

Revert bad PR #1263

---

kimchi/Cargo.toml
kimchi/src/tests/lookup.rs

Part of https://github.com/MinaProtocol/mina/issues/14664

[develop] Use seedable rng for some tests

---

kimchi/src/circuits/constraints.rs
kimchi/src/tests/lookup.rs

Fix 1362: add the dummy entry in the domain size count

---

kimchi/src/tests/lookup.rs

https://github.com/o1-labs/proof-systems/pull/1484 targetting develop.
Fixing https://github.com/MinaProtocol/mina/issues/14678

Test: number of gates should be at least 2 [develop]

---

optimism/run-op-program.sh

Review this one XOR https://github.com/o1-labs/proof-systems/pull/1534

Missing $ for the variable

---

kimchi/src/circuits/lookup/index.rs
kimchi/src/tests/lookup.rs

Brings in some lookup test changes

Merge develop into master

---

kimchi/src/folding/error.rs
kimchi/src/folding/expressions.rs
kimchi/src/folding/instance_witness.rs
kimchi/src/folding/mod.rs
kimchi/src/folding/quadricization.rs
kimchi/src/folding/test.rs
kimchi/src/lib.rs

This PR finishes folding as currently envisioned with the next main changes:
- Refactoring.
- Integrating quadricization inside folding.
- Automatic witness generation for quadricization.
- Degree 3 folding.
- Powers of alpha handled directly by folding.

Folding improvements

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/mips/witness.rs

This is to make sure that all other witness values are correctly set to zero between steps of execution.

[easy] Implement Default for KeccakColumns

---

optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/mips/witness.rs

This adds the skeleton for the Keccak interpreter. Functions content will be added in subsequent PRs.

[easy] Trait definition of Keccak interpreter

---

optimism/src/keccak/environment.rs
optimism/src/keccak/witness.rs

This includes the logic to pass from one step to the right next one, depending on the data stored in the KeccakEnv.

Function to update the step of Keccak execution

---

optimism/src/mips/column.rs
optimism/src/mips/constraints.rs
optimism/src/mips/witness.rs

Builds on https://github.com/o1-labs/proof-systems/pull/1602.

Add `InstructionCounter` dedicated column

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs

No-op, just the trait definition.

Skeleton for Keccak constraints

---

optimism/src/keccak/constraints.rs

The difference between these and the ones found in the Kimchi gate is an extra degree due to multiplying by the `is_round()` selector.

Constraints of the Theta permutation step

---

optimism/src/keccak/constraints.rs

The difference between these and the ones found in the Kimchi gate is an extra degree due to multiplying by the `is_round()` selector.

Constraints of the Chi permutation step

---

optimism/src/keccak/constraints.rs

The difference between these and the ones found in the Kimchi gate is an extra degree due to multiplying by the `is_round()` selector.

Constraints of the PiRho permutation step

---

kimchi/src/circuits/expr.rs

This builds upon https://github.com/o1-labs/proof-systems/pull/1577.

Use `ChallengeTerm` and `ConstantTerm` in `PolishToken`

---

kimchi/src/circuits/polynomials/keccak/mod.rs

Part of https://github.com/MinaProtocol/mina/issues/14664

Keccak: randomize the seed for tests

---

kimchi/src/tests/lookup.rs

Part of https://github.com/MinaProtocol/mina/issues/14664

Use a seedable PRNG for randomized tests

---

optimism/src/mips/constraints.rs

Fixing doc build. Master CI is currently broken.

Use new structure of the expression framework

---

kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/tests/lookup.rs

Primarily integrates https://github.com/o1-labs/proof-systems/pull/1567/

Merge develop into master 03/01/2023

---

optimism/src/keccak/lookups.rs

No-op, just clean-up before those fields are removed in a coming PR.

[easy] Use function calls instead of direct struct field access inside lookups

---

optimism/run-cannon.sh
optimism/run-code.sh
optimism/run-op-program.sh

We should be able to run the binaries individually

Split op-program and cannon

---

optimism/src/keccak/lookups.rs

This PR is the second one trying to simplify the `Lookup` trait for `KeccakEnv` by adding a helper to easily create lookups to the `Reset` lookup table. Not only does it clean up the interface, but it also allows for switch on/off functionality thanks to the flag argument of `Signed`.

[easy] Helper for `Reset` lookup table

---

optimism/src/keccak/lookups.rs

This PR is the fourth one trying to simplify the Lookup trait for KeccakEnv by adding a helper to easily create lookups to the Sparse lookup table. Not only does it clean up the interface, but it also allows for switch on/off functionality thanks to the flag argument of Signed.

[easy] Helper for `Sparse` lookup table

---

optimism/src/keccak/lookups.rs

[easy] Clean-up sponge lookups

---

optimism/src/keccak/lookups.rs

[easy] Clean-up Theta lookups

---

optimism/src/keccak/lookups.rs

[easy] Clean-up Pirho lookups

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs

To prevent undesired side-effects.

[easy] Limit number of public fields inside `KeccakColumns`

---

kimchi/src/folding/expressions.rs

This PR replaces the `FoldingCompatibleExpressions` hard-coded type with an instance of `Operations`, in preparation for unification with the `Expr` type in `kimchi`.

Use `Operations` for folding expressions

---

optimism/src/mips/witness.rs

Closes https://github.com/o1-labs/proof-systems/issues/1702

[easy] Make `preimage_bytes_read` a `u64`

---

optimism/src/keccak/column.rs
optimism/src/keccak/mod.rs

This PR replicates what is being done in `mips` for `WitnessColumns`.

Implement iterators for `KeccakColumns`

---

optimism/src/keccak/proof.rs
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/proof.rs

zkVM: share domain size

---

optimism/src/keccak/column.rs
optimism/src/keccak/proof.rs

This replicates what's done in `mips` for `ProofInputs`.

Implement fold for `KeccakProofInputs`

---

optimism/src/keccak/proof.rs

This PR replicates what is being done in `mips` for `WitnessColumns`.

Implement `prove` function for `KeccakProof`

---

optimism/src/keccak/proof.rs

This PR replicates what is being done in `mips` for `Proof`.

Implement verify for `KeccakProof`

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/witness.rs

This PR removes `ThetaStateA`, `IotaStateG`, `SpongeOldState`, and `SpongeXorState`, substituting them for `Input` and `Output`. They correspond to the variables in locations `curr[0..100]` and `next[0..100]`. 
Otherwise, when variables are being used in constraints, the value written in the input and output of consecutive steps will not have the same format making it impossible to fold the instance.
Related to https://github.com/o1-labs/proof-systems/issues/1723
Note: it also renames single-indices in environment variables to `idx` to avoid confusion with `i` (normally used to index only from 0 to 4), so when the above issue is addressed fully it becomes more readable.

Create `Input` and `Output` Keccak columns

---

book/macros.txt
book/src/pickles/accumulation.md
book/src/specs/kimchi.md
kimchi/src/plonk_sponge.rs
kimchi/src/proof.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
poly-commitment/src/lib.rs
poseidon/src/lib.rs
poseidon/src/sponge.rs

This is the part with some small refactorings I was doing while working on the vinegar RFC. No code logic change intended, changes should be purely cosmetic.
Review by commit.

Improve code & book documentation

---

book/src/fundamentals/zkbook_groups.md

Hi guys!
Thank you for the book!
A little typo, I believe

fix typo in the book

---

kimchi/src/tests/ec.rs
kimchi/src/tests/foreign_field_add.rs
utils/src/lib.rs

Part of https://github.com/MinaProtocol/mina/issues/14664

Make tests more random

---

optimism/src/mips/mod.rs
optimism/src/mips/proof.rs

@querolita
To keep a note of the structure of the zkVM.

Document top level module MIPS and some structs in the module proof

---

msm/src/constraint.rs
msm/src/lib.rs

Note that the example code is compiled in the CI while running cargo test --doc.
It enforces us to keep updated documentation.

MSM: introduce expression framework to build constraints

---

msm/src/proof.rs
msm/src/prover.rs

Superseeds https://github.com/o1-labs/proof-systems/pull/1802/
The previous interface is not satisfying enough, and implementing `Into` does not make the following PRs elegant.

Provide a better interface for converting evaluations into polynomials

---

optimism/src/keccak/lookups.rs
optimism/src/lookup.rs
optimism/src/mips/constraints.rs
optimism/src/mips/interpreter.rs

`RangeCheck16` lookup table

---

optimism/src/lookup.rs

`Byte` lookup table

---

optimism/src/lookup.rs

`Sparse` lookup table

---

optimism/src/keccak/lookups.rs
optimism/src/lookup.rs

`Reset` lookup table

---

kimchi/src/circuits/polynomials/keccak/mod.rs
optimism/src/keccak/lookups.rs
optimism/src/lookup.rs

`RoundConstants` lookup table

---

optimism/src/keccak/witness.rs
optimism/src/lookup.rs

Closes https://github.com/o1-labs/proof-systems/issues/1735

`Pad` lookup table

---

optimism/src/keccak/column.rs

Start fixing rendering of Keccak doc

---

msm/README.md

The document will evolve in the future

Kimchi MSM: introduce README

---

msm/src/constraint.rs
msm/src/precomputed_srs.rs
poly-commitment/src/pairing_proof.rs

The PR 1812 introduces unecessary changes. This PR reverts it, while keeping it in the git history if necessary in the future.
Let's not merge dead code in master.

Changes for 1812

---

book/src/specs/kimchi.md
kimchi/src/verifier.rs

Adding the corresponding PlonK rounds and the corresponding use of the challenges

Doc/Kimchi: modestly improve documentation

---

Cargo.lock
Cargo.toml
curves/Cargo.toml
groupmap/Cargo.toml
hasher/Cargo.toml
internal-tracing/Cargo.toml
kimchi/Cargo.toml
kimchi/snarky-deriver/Cargo.toml
optimism/Cargo.toml
optimism/src/preimage_oracle.rs
poly-commitment/Cargo.toml
poseidon/Cargo.toml
signer/Cargo.toml
tools/kimchi-visu/Cargo.toml
turshi/Cargo.toml
utils/Cargo.toml

keeps all the dependencies in one place, makes updating versions easier.

cargo update + use workspace deps

---

msm/src/witness.rs

Same than https://github.com/o1-labs/proof-systems/pull/1872 in the MSM directory

Generic witness: implement iterator with lifetime

---

msm/src/serialization/witness.rs

Fix https://github.com/o1-labs/proof-systems/issues/1870

MSM/Serialization: assert limbs size

---

msm/src/serialization/witness.rs

Checking the decomposition in base 16 of the last limbs

MSM/Serialization: implement first constraint

---

msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/witness.rs

Env: use Fp type for variable to encode 15 bits decomposition

---

msm/src/serialization/constraints.rs
msm/src/serialization/witness.rs

Review https://github.com/o1-labs/proof-systems/pull/1888 first

MSM/Serialization: implement second constraint

---

msm/src/serialization/interpreter.rs

Fix https://github.com/o1-labs/proof-systems/issues/1899

MSM/Serialization: folding constraints definitions

---

msm/src/prover.rs

Fix https://github.com/o1-labs/proof-systems/issues/1912

MSM: prover - use functional traits instead of imperative traits

---

msm/src/ffa/witness.rs
msm/src/proof.rs
msm/src/serialization/main.rs

Generic prover: add public input size

---

kimchi/src/circuits/expr.rs

The branch name could be less FP oriented :). Adding a comment just as a reminder next time I go into the code

Kimchi/Expr: comment Either type

---

msm/src/ffa/columns.rs
msm/src/ffa/witness.rs

This introduces actual constraints for computing FF addition, but for now the core computation w/o range checks

MSM FFA Addition: Introducing new columns

---

kimchi/src/tests/and.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/xor.rs
utils/src/foreign_field.rs

Makes some tests with hardcoded seed actually randomised, which is hopefully really good!

Use utils::make_test_rng instead of hardcoded RNG_SEED

---

msm/src/columns.rs
msm/src/mvlookup.rs

Cherry-picking from https://github.com/o1-labs/proof-systems/pull/1966/files

[no-op/easy] MISC changes - Documentation + remove old comments

---

msm/src/lookups.rs
msm/src/mvlookup.rs
msm/src/serialization/mod.rs
optimism/src/lookups.rs
optimism/src/ramlookup.rs

Part of https://github.com/o1-labs/proof-systems/pull/1966/

MISC: add some table ID converters

---

msm/src/column_env.rs
msm/src/columns.rs
msm/src/ffa/columns.rs
msm/src/ffa/witness.rs
msm/src/proof.rs
msm/src/serialization/witness.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/1966

Add specialized columns for lookup protocol

---

msm/src/serialization/constraints.rs

Used later. Tests coming later.

Lookup: implement combine_lookups

---

msm/src/serialization/constraints.rs

Cherry-pick from https://github.com/o1-labs/proof-systems/pull/1966/files.
Used later. Tests coming.

Serialization: implement constraint lookups

---

msm/src/lib.rs
msm/src/mvlookup.rs

It will be used to define the quotient polynomial and split the looked-up values

Define constant for the max supported degree

---

msm/src/column_env.rs
msm/src/mvlookup.rs
msm/src/prover.rs

And implement LookupPartialSum

LookupEnv: init QuotientPolynomialEnvironment

---

Cargo.lock
msm/Cargo.toml
msm/src/ffa/constraint.rs
msm/src/ffa/interpreter.rs
msm/src/ffa/main.rs
msm/src/ffa/witness.rs

This PR adds working FF Addition circuits and constraints. `main.rs` works, but I plan to convert it into a test in the next PR.
Please first merge https://github.com/o1-labs/proof-systems/pull/1932
(these changes are duplicated here for... git reasons)
Previous PR: https://github.com/o1-labs/proof-systems/pull/1921

MSM FFA Addition: Add actual circuits and constraints

---

msm/src/mvlookup.rs

Cherry-picked commits from [dw/tmp-eval-8/](https://github.com/o1-labs/proof-systems/commits/dw/tmp-eval-8/)

Logup: parallelize evaluations

---

msm/src/column_env.rs
msm/src/mvlookup.rs
msm/src/prover.rs

Some parts come from the (closed) PR: https://github.com/o1-labs/proof-systems/pull/1986.

Lookup/Evaluations: evaluate on d8 when there are lookups

---

msm/src/test/mod.rs

Always a good check, in particular as we introduce now the quotient polynomial that can be splitted.

Tests: checking proof size

---

poly-commitment/src/evaluation_proof.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs
utils/src/dense_polynomial.rs

Utils: ensuring that the requested number of chunks is returned

---

poly-commitment/src/evaluation_proof.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs
utils/src/dense_polynomial.rs

Testing on mina/develop looks ok.

[develop] Utils: ensuring that the requested number of chunks is returned

---

optimism/src/keccak/tests.rs

Danny got a failing assert in one of the Keccak tests yesterday. I found out that with that seed, the byte position that I was trying to nullify in the negative test was already 0, so instead of 2 errors, only 1 should occur. 
This type of "problem" could arise in other negative tests. I would need to spend more time looking into them to know if others need some special treatment as well. For now I am fixing this one.

Improve the negative padding test of Keccak

---

msm/src/proof.rs

Still missing fixed lookup tables

MSM/Proof: implement ColumnEvaluation for lookups

---

kimchi/src/circuits/berkeley_columns.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/foreign_field_mul/gadget.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/prover.rs

Planning to implement FormattedOutput for the generic prover

Move berkeley related expressions into berkeley_column.rs

---

optimism/run-code.sh
optimism/src/main.rs

I realised that a previous PR modified the main file in a way that is not desirable in master, but just for testing purposes. This PR reverts it.

[easy] Revert changes made in `main` for debugging

---

msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/witness.rs

I don't like leaving small TODO's like this :).

MSM/witness: rename Fp in F, solving TODO

---

book/src/kimchi/gates.md
msm/src/serialization/interpreter.rs

chore: fix typos

---

optimism/src/circuit.rs
optimism/src/keccak/circuit.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/circuit.rs
optimism/src/mips/mod.rs
optimism/src/mips/tests.rs

[easy] Move circuit definition to their own module

---

msm/src/lib.rs
msm/src/logup.rs

Run `RUSTDOCFLAGS="-D warnings" cargo doc --all-features --no-deps`.

Logup: more documentation

---

Cargo.lock
msm/Cargo.toml
optimism/Cargo.toml

For consistency
Other packages use `-`.

Package name: use dash instead of underscore

---

msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/lookups.rs
msm/src/serialization/mod.rs
msm/src/serialization/witness.rs

This is a refactoring PR aimed to improve interfaces around lookups in `serialization/`.
Previous PR: https://github.com/o1-labs/proof-systems/pull/2070
Addresses #2060

MSM Serialization: Improve interfaces around lookups [no-op]

---

msm/src/logup.rs

Logup: remove old comment

---

optimism/run-vm.sh
optimism/src/keccak/trace.rs
optimism/src/main.rs
optimism/src/mips/trace.rs
optimism/src/trace.rs

There was a change in the package name so this fixes it.

Preliminar work to fix MIPS (fixes master)

---

optimism/run-vm.sh
optimism/src/keccak/trace.rs
optimism/src/main.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/tests.rs
optimism/src/mips/trace.rs
optimism/src/trace.rs

See https://github.com/ethereum-optimism/optimism/blob/develop/cannon/mipsevm/mips.go#L221C1-L222C18

MIPS: implement MoveToHi

---

msm/src/fec/interpreter.rs
msm/src/serialization/interpreter.rs

Now that the interpreter is unified (https://github.com/o1-labs/proof-systems/pull/2114), we can remove some terrible copy-paste. Win-win!

MSM: Remove duplicated FEC/Serialization code

---

msm/src/circuit_design/composition.rs

Just some comments on capability composition to build a bit of intuition (@dannywillems as requested in https://github.com/o1-labs/proof-systems/pull/2115).

[#2060] Comments on composition [easy, cosmetics]

---

kimchi/Cargo.toml
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/snarky/api.rs

I cannot run the CI in https://github.com/o1-labs/proof-systems/pull/1867

Remove spew to stdout [1867]

---

optimism/src/main.rs

Will make it easier to generalize later to any curve

[easy peasy] o1VM: simplify type alias

---

folding/src/instance_witness.rs
msm/src/prover.rs
optimism/src/folding.rs
optimism/src/mips/constraints.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2146

[easy peasy] Modest changes in doc + default impl

---

optimism/src/folding.rs

Also, add an explanation on the challenges
Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2146/

[easy] o1VM/folding: be more generic for the challenges using enum count

---

optimism/src/keccak/folding.rs

@querolita will certainly need it

Folding/Keccak: makes structures public to use it in other crates

---

folding/src/lib.rs

No reason to make it available only for bn254

Folding: make structure always available

---

folding/src/decomposable_folding.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/examples/generic.rs
folding/src/lib.rs
optimism/src/folding.rs
optimism/src/keccak/folding.rs
optimism/src/mips/folding.rs

Note: the PR does not aim to check that all the randomness is handled properly. I only replace the sponge trait by an appropriate instance of a sponge.

Handle sponge in folding properly

---

optimism/src/trace.rs

And use abstraction of Witness structure

Trace/folding: avoid clone + use parallel

---

o1vm/src/folding.rs
o1vm/src/keccak/column.rs
o1vm/src/keccak/folding.rs
o1vm/src/keccak/tests.rs
o1vm/src/keccak/trace.rs
o1vm/src/main.rs
o1vm/src/mips/column.rs
o1vm/src/mips/folding.rs
o1vm/src/mips/trace.rs

o1VM: prefix columns vars with N and suffix with COLS

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs

Does scalar computation for `r^2 phi^i` and `r^3 phi^i` in an ineffective but very simple way.
Previous PR:
- https://github.com/o1-labs/proof-systems/pull/2173

IVC Circuit (Part 7): Simple scalar computation

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/lib.rs

There might be more, but here are just a few I found while reading about IVC.

[easy] Fix typos in IVC comments

---

msm/src/prover.rs
o1vm/src/keccak/interpreter.rs
o1vm/src/keccak/tests.rs

The goal of this PR is to simplify the current Keccak folding tests and increase the visibility of the effects of quadri of folding.

Common framework for Keccak tests with quadri

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
msm/src/circuit_design/composition.rs
msm/src/circuit_design/constraints.rs
msm/src/circuit_design/witness.rs
msm/src/test/test_circuit/mod.rs

Applied cosmetic suggestions from https://github.com/o1-labs/proof-systems/pull/2233

Suggestions from the IVC Selectors PR

---

utils/src/array.rs

Fixes https://github.com/o1-labs/proof-systems/pull/2247. The functions before were still overflowing the stack. That was happening because e.g. `vec_of_slices2.iter().map(...)` was dereferencing inside the map (https://github.com/o1-labs/proof-systems/pull/2260/files#diff-892a56213c28a7749b5e25aa89c7067aac3c15d0d5d86293a00cb720ef88c6c4L20), thus bringing the value into the stack again. In practice, each element of that vector was put on stack and then added from stack to the vector again.
Main changes:
- Implement converters properly. Now new vectors are created from a slice, so from a memory reference directly.
- Tests changed to create much bigger arrays (that actually fail on `master`)
Introduces `Clone` but I haven't found another way. It's honestly a bit tough with rust that I can't …

Fix allocation in o1utils array module

---

ivc/src/ivc_circuit.rs
ivc/src/lib.rs

IVC: clean some files

---

poly-commitment/src/pairing_proof.rs
poly-commitment/src/srs.rs

Fix the cofactor in G2 / BN254 bug

---

Cargo.lock
folding/src/expressions.rs
folding/tests/test_quadraticization.rs

Here unexpected failing tests. Built on top of https://github.com/o1-labs/proof-systems/pull/2270/files.

Tests folding discriminant

---

folding/src/error_term.rs
folding/src/lib.rs

It can be infered using the domain size from the environment

Folding: remove zero_vec from FoldingEnv

---

folding/src/decomposable_folding.rs
folding/src/instance_witness.rs
folding/src/lib.rs

It will be replaced by blinders. See WIP 2285.

Folding: remove zero_commitment parameter

---

ivc/src/ivc/mod.rs
ivc/src/poseidon/mod.rs
ivc/src/poseidon_quadri/mod.rs
ivc/tests/add.rs
kimchi/src/circuits/polynomials/foreign_field_common.rs
kimchi/src/snarky/range_checks.rs
kimchi/src/tests/and.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/xor.rs
msm/src/fec/mod.rs
msm/src/ffa/mod.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs
msm/src/test/logup.rs
msm/src/test/proof_system.rs
msm/src/test/test_circuit/mod.rs
o1vm/src/keccak/tests.rs
o1vm/src/main.rs
o1vm/src/mips/tests.rs
poly-commitment/src/tests/commitment.rs
utils/src/lib.rs

Just for convenience of debugging, cherry-picked from https://github.com/o1-labs/proof-systems/pull/2299

[easy] Random tests allow to pass a specific seed

---

ivc/src/poseidon/mod.rs
ivc/src/poseidon_quadri/mod.rs

IVC/Poseidon: add next row

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs

Move to an instance of Poseidon suitable for IVC

IVC: use poseidon degree 2

---

folding/src/expressions.rs

Maps variable (column index) in expression using the `mapper` function. Can be used to modify (remap) the indexing of columns after the expression is built.
Cherry-picking from https://github.com/o1-labs/proof-systems/pull/2269

Folding: add method to reindex variables

---

ivc/src/ivc/columns.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2269/

IVC/columns: add MISC comments

---

ivc/src/ivc/columns.rs

All columns must be off by one. A better method should be used to avoid the duplicated code `add_rel_offset`, but it is left for another commit.
Also, this doesn't implement how the FoldIteration column is filled in the interpreter. It will come in another commit.

IVC/Column: add FoldIteration

---

poly-commitment/src/commitment.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2269/

Poly-commitment: improve error message when panicking

---

ivc/tests/add.rs

Will be useful in a future PR where we add the IVC columns
There is also a new implementation of FoldingEnv in the folding library we might want to use in the future. Mostly cherry-picking from the big PR

IVC/Add: make plonkish witness and instance generic over N_COL

---

msm/src/fec/mod.rs

Provides a test that checks that FEC ADD circuit actually computes `p + q`. Now in the test the point is actually valid, and we compare the output with the native implementation on Pallas.
Closes #2230.

Add test for correctness of FEC ADD

---

ivc/tests/add.rs

Mostly cleaning old code, and prepare the witness and instance to include the IVC columns
In the next PR, the folding env and config will be changed to use the new generic folding env created some days ago. It will clean the code.
From there, I will continue to concatenate the witnesses and instances

IVC: prepare code for folding APP and IVC

---

ivc/tests/add.rs

It removes duplicated code. The folding environment is not required anymore. It is pre-defined in the folding library.

IVC: using StandardConfig from folding library

---

ivc/src/lib.rs

We must keep somewhere our discussion.

IVC: add top level documentation

---

ivc/src/ivc/interpreter.rs
ivc/tests/add.rs

We should move this into an appropriate environment later

IVC: assert the domain is large enough to handle the IVC circuit

---

ivc/src/ivc/columns.rs
ivc/tests/add.rs

There is still the fold interation to be added.

IVC: building correctly all round constants and fixed selectors

---

ivc/src/ivc/mod.rs

We should also have a test for the number of additional columns, but I suppose it would come later.

IVC: some regression tests

---

.config/nextest.toml
.github/workflows/rust.yml
ivc/src/ivc/constraints.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
ivc/src/lib.rs
ivc/tests/add.rs

IVC: base case - temporary solution

---

.github/workflows/rust.yml
book/specifications/kimchi/Makefile
ivc/src/poseidon_55_0_7_3_2/mod.rs
ivc/src/poseidon_55_0_7_3_7/mod.rs
ivc/src/poseidon_8_56_5_3_2/mod.rs
ivc/tests/add.rs
kimchi/src/precomputed_srs.rs
kimchi/src/tests/chunked.rs
msm/src/ffa/mod.rs
msm/src/precomputed_srs.rs
msm/src/serialization/mod.rs
o1vm/src/keccak/tests.rs

~~CI seems to fail with OOM. I wonder how much can it handle.~~
Now this PR introduces a new runner type.

Switch CI to the bigger Hetzner instance

---

book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/proof.rs
kimchi/src/prover.rs

broke link related proof system fix

chore: readme

---

ivc/tests/add.rs

Found some issues that have to be fixed before the next PR.

[#2313] Porting IVC+ADD 8: Bugfixes for test params

---

poly-commitment/src/pairing_proof.rs

changes the verification equation of kzg from `e(numerator,1)=?e(quotient,denominator)` to 
`finale_exp  (miller_loop((numerator,1(-quotient,denominator))))=?1`

Poly_commitment/pairing_proofs : optimize verif

---

poly-commitment/src/evaluation_proof.rs

We should have more documentation in this file, and we should maybe rename it.

Poly-commitment: additional top-level documentation

---

mvpoly/src/prime.rs

MVPoly: add double

---

mvpoly/src/prime.rs

Fix request: https://github.com/o1-labs/proof-systems/pull/2484#pullrequestreview-2263442205.

MVPoly: use functional trait instead of imperative trait

---

mvpoly/src/prime.rs
mvpoly/tests/prime.rs

Implement suggestion https://github.com/o1-labs/proof-systems/pull/2489#pullrequestreview-2263462842

MVPoly: rename mul_by_const into mul_by_scalar

---

mvpoly/src/prime.rs
mvpoly/tests/prime.rs

Address https://github.com/o1-labs/proof-systems/pull/2482#issuecomment-2313686065

MVPoly: mark random as unsafe

---

mvpoly/src/prime.rs
mvpoly/tests/prime.rs

Might be useful if the user wants to artificially increase the maximum degree of the polynomial.
Not sure it will useful at the moment.

MVPoly: helper to increase the degree in the type

---

mvpoly/tests/prime.rs

Address previous comments noticing missing PBT tests for multiplications

MVPoly: add more PBT for polynomial multiplication

---

.github/workflows/ci-nightly.yml
.github/workflows/ci.yml
Makefile
codecov.yml
mvpoly/src/utils.rs
mvpoly/tests/utils.rs

It will be used later in the cross-term computation to perform the multi-nomial sum

MVPoly: util to compute nested loops indices

---

Makefile
mvpoly/Cargo.toml
mvpoly/benches/monomials.rs
mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs

It aims to share the same interface as `prime::Dense`, but it is a WIP. I would suggest to add a trait later.
Built on top of #2514

MVPoly: implement monomials form

---

mvpoly/src/utils.rs
mvpoly/tests/utils.rs

Addressing https://github.com/o1-labs/proof-systems/pull/2514#issuecomment-2329004289

MVPoly/utils: edge cases for nested loop indices computation

---

kimchi/src/lagrange_basis_evaluations.rs

https://github.com/o1-labs/proof-systems/pull/2521

Address feedback from 2521

---

ivc/src/prover.rs
ivc/src/verifier.rs
kimchi/src/tests/generic.rs
msm/src/lib.rs
msm/src/precomputed_srs.rs
msm/src/test/generic.rs
msm/src/test/logup.rs
o1vm/src/lib.rs
o1vm/src/main.rs
poly-commitment/src/kzg.rs
poly-commitment/src/lib.rs
poly-commitment/src/srs.rs
poly-commitment/tests/kzg.rs

As discussed with @marcbeunardeau88

Poly-commitment: rename pairing_proof in kzg and add comments/docs

---

mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/pbt.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs
mvpoly/tests/prime.rs

MVPoly tests generalization finalization.

---

arrabiata/src/columns.rs
arrabiata/src/interpreter.rs
arrabiata/src/prover.rs
arrabiata/src/verifier.rs

The homogeneisation will be later, using mvpoly, and also for the cross-terms

Arrabiata/doc: small update

---

arrabiata/src/lib.rs
arrabiata/src/witness.rs

Addressing comments from https://github.com/o1-labs/proof-systems/pull/2433

Arrabiata/doc: no need to absorb vk

---

.github/workflows/ci.yml

Ported https://github.com/o1-labs/proof-systems/pull/2595

Cancel in progress CI: develop

---

.github/workflows/ci.yml

See https://github.com/marketplace/actions/rust-cache

Enable rust-cache GH action

---

.github/workflows/ci.yml

See https://github.com/o1-labs/proof-systems/pull/2596

[develop] Enable rust-cache GH action

---

o1vm/src/pickles/main.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/proof.rs

See https://github.com/o1-labs/proof-systems/blob/5b687813895fef22a5fc199103b70c3fb0d2360e/optimism/src/main.rs#L84

o1vm/pickles: importing proof and building it in main

---

poly-commitment/benches/poly_comm.rs

Remove useless duplicated method. Use more the type system.

Poly_commitment: refacto benchmark

---

poly-commitment/benches/poly_comm.rs

Remove useless duplicated method. Use more the type system.

Poly_commitment: refacto benchmark [develop]

---

ivc/src/ivc/mod.rs
kimchi/src/precomputed_srs.rs
msm/src/fec/mod.rs
mvpoly/src/pbt.rs
mvpoly/tests/monomials.rs
mvpoly/tests/prime.rs

Make some tests heavy and fix some wrong tests values.

Improving CI speed

---

poly-commitment/src/commitment.rs
poly-commitment/src/srs.rs
utils/src/field_helpers.rs

Poly_commitment/utils: move inner_prod into field_helpers

---

o1vm/src/interpreters/mips/column.rs
o1vm/src/interpreters/mips/constraints.rs
o1vm/src/interpreters/mips/interpreter.rs
o1vm/src/interpreters/mips/tests.rs
o1vm/src/interpreters/mips/witness.rs
o1vm/src/legacy/trace.rs
o1vm/src/pickles/main.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/tests.rs

Running the o1vm with this code seems to work.
cc @Fizzixnerd

Suggestions for dynamic selectors

---

o1vm/README.md

The other way did not work for me
This one does

O1vm/readme : add another way to install go1.21

---

poly-commitment/Cargo.toml
poly-commitment/benches/ipa.rs

Following a discussion during our pair-coding session with Marc.

Poly-commitment: add bench for IPA open

---

o1vm/src/pickles/prover.rs

Will be used by the quotient polynomial in a next PR

o1vm/pickles: evaluate all polynomials on d8

---

o1vm/src/pickles/column_env.rs
o1vm/src/pickles/main.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/prover.rs

Will be used by the quotient polynomial.
Built on top of https://github.com/o1-labs/proof-systems/pull/2651

o1vm/pickles: import column_env

---

arrabiata/src/constraints.rs
arrabiata/tests/constraints.rs

See comments. It might not be complete, but providing an interface for now.

Arrabiata: gather all constraints for the IVC

---

poly-commitment/src/ipa.rs

Poly-commitment: remove prover_plms_to_verif_evals as unused

---

ivc/tests/folding_ivc.rs
kimchi/src/tests/generic.rs
msm/src/precomputed_srs.rs
msm/src/test/logup.rs
o1vm/src/legacy/main.rs
poly-commitment/src/kzg.rs
poly-commitment/src/lib.rs
poly-commitment/tests/kzg.rs

Poly-commitment/KZG: add tests regarding exp nb of chunks

---

mvpoly/README.md
mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/pbt.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs

See individual commits.
It is mostly from https://github.com/o1-labs/proof-systems/pull/2702/ to split it in small target chunks.
Built on top of https://github.com/o1-labs/proof-systems/pull/2710.

MVPoly: improve the library + fix sub in monomials

---

book/src/specs/poseidon.md

Commit 1501267b039a7321b9d75d7f1c16f3bc033e951e moved the location of the `test_vectors/kimchi.json`. This PR adjusts sources to changes.

Update test vectors in posedion

---

o1vm/src/cannon_cli.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2727/

o1vm: update description

---

o1vm/src/interpreters/riscv32im/interpreter.rs

The initial author is Sai Vegasena. The changes are imported from the history ending at c1b7433836c8ddadca7de05e6a1635b204a57cfa. More commits will follow using the code of the original author. The commit author will be changed accordingly.
Some aesthetic changes have been incorporated to get cleaner code, like adding documentation and removing some obsolete comments.
The documentation has been added to be readable when generating it using rustdoc.

o1vm/interpreter: sketch interpret_rtype, add documentation

---

o1vm/src/interpreters/riscv32im/interpreter.rs

I did not find the license for the course at Cornell.

o1vm/riscv32: continue instruction doc + add credits

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

Will be used to implement MInstruction::Divu

o1vm/riscv32: implement div for unsigned 32bits

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

It will be used to implement MInstruction::Remu in a follow-up PR.

o1vm/riscv32: implement mod_

---

mvpoly/src/monomials.rs

Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2702/

MVPoly/monomials: improve generation of random generation

---

mvpoly/README.md

I reviewed the entire repository, no more typos found in docs. 
Hope this helps streamline the project!
Best regards,
Bilogweb3

 correct typo doc

---

book/src/plonk/domain.md
book/src/specs/urs.md

fixed:
straight forward - straightforward 
hidding - hiding 
I hope my corrections will help you. Thank you for your work.

Fix typos and spelling errors

---

mvpoly/tests/monomials.rs

Checking that the specification is correctly followed.

mvpoly/tests: check the output size of ct_scaled

---

.github/workflows/ci.yml
arrabbiata/src/witness.rs
folding/src/error_term.rs
folding/src/expressions.rs
hasher/src/poseidon.rs
ivc/src/poseidon_55_0_7_3_2/interpreter.rs
ivc/src/poseidon_55_0_7_3_7/interpreter.rs
ivc/src/poseidon_8_56_5_3_2/interpreter.rs
ivc/tests/simple.rs
kimchi/src/snarky/boolean.rs
kimchi/src/snarky/union_find.rs
kimchi/src/tests/foreign_field_add.rs
msm/src/witness.rs
o1vm/src/cannon.rs
tools/kimchi-visu/src/lib.rs

Previous versions will be dropped step by step. Upgrading step by step to avoid big diffs.

Support Rust 1.78

---

folding/src/instance_witness.rs
ivc/src/lib.rs
kimchi/src/tests/framework.rs
mvpoly/src/lib.rs

chore: remove redundant words

---

.github/workflows/ci-nightly.yml
.github/workflows/ci.yml

See commits
A follow-up will be to fix the nightly builds https://github.com/o1-labs/proof-systems/actions/runs/13319693799/job/37201804924

CI: remove code coverage to speed up

---

arrabbiata/src/column.rs
arrabbiata/src/constraint.rs

This will be used in a future PR. I might change in the future by an indexed (by gadget) array. It is mostly to know which polynomials are activated for each row to compute the cross-terms later.

Arrabbiata: introduce new method to get all constraints by gadget

---

arrabbiata/Cargo.toml
arrabbiata/README.md
arrabbiata/src/cli.rs
arrabbiata/src/lib.rs
arrabbiata/src/main.rs
arrabbiata/tests/cli.rs

The second commit is to fix an issue noticed by @querolita yesterday.
Reviewers are encouraged to check the whole commit messages.

Arrabbiata: better CLI + support test started in debug mode

---

arrabbiata/src/column.rs
arrabbiata/src/constraint.rs
arrabbiata/src/interpreter.rs
arrabbiata/src/witness.rs
arrabbiata/tests/constraint.rs
arrabbiata/tests/witness.rs

Addressing https://github.com/o1-labs/proof-systems/pull/3053#discussion_r1969859314 and https://github.com/o1-labs/proof-systems/pull/3053#discussion_r1969865525

Arrabbiata: rename PoseidonPermutation into PoseidonFullRound

---

o1vm/src/interpreters/mips/mod.rs
o1vm/src/interpreters/mips/tests.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/tests.rs

The test has nothing to do with the Pickles flavor.

o1vm/mips: move tests reg. total nb of constraints and max degree

---

.github/actions/ocaml-shared/action.yml

See https://github.com/ocaml/setup-ocaml/releases/tag/v3.2.17

CI: move back to latest release to setup ocaml

---

scripts/bench-criterion-mina-circuits.sh

I introduced a regression commit and tested that with the 1 line fix it indeed catches regressions.

Fix regression failure condition in bench yml [easy]

---

plonk-wasm/src/plonk_verifier_index.rs

See context https://github.com/o1-labs/proof-systems/pull/3157
Counterpart PR:
- https://github.com/o1-labs/o1js/pull/2137
- https://github.com/o1-labs/proof-systems/pull/3158
- https://github.com/MinaProtocol/mina/pull/16888
- https://github.com/o1-labs/o1js-bindings/pull/356

plonk-wasm/verifier index: appease clippy

---

plonk-wasm/src/srs.rs

- https://github.com/o1-labs/proof-systems/pull/3159
- https://github.com/o1-labs/o1js/pull/2138
- https://github.com/o1-labs/o1js-bindings/pull/357
- https://github.com/MinaProtocol/mina/pull/16889

plonk-wasm/srs: annotate unsafe method and add doc accordingly

---

plonk-wasm/src/arkworks/pasta_fp.rs
plonk-wasm/src/arkworks/pasta_fq.rs

- https://github.com/o1-labs/o1js-bindings/pull/358
- https://github.com/o1-labs/o1js/pull/2139
- https://github.com/o1-labs/proof-systems/pull/3160
- https://github.com/MinaProtocol/mina/pull/16890

plonk-wasm/arkworks: appease clippy by avoiding with_capacity

---

saffron/src/utils.rs

Fix documentation after merge of https://github.com/o1-labs/proof-systems/pull/3172

Saffron/Utils: fix doc

---

book/src/pickles/accumulation.md

Some typo/small improvements to the accumulation part of the mina book

mina book typo

---

saffron/src/lib.rs
saffron/src/read_proof.rs

Subj. Adding the read proof attesting to `d * q - a = 0`.

Saffron: Add simple read proof

---

saffron/benches/read_proof_bench.rs
saffron/src/folding.rs
saffron/src/lib.rs
saffron/src/read_proof.rs

This adds simple interactive folding: two functions for folding specifically (`folding_prover`, `folding_verifier`), and prover/verifier for the relaxed statement. No IVC/verification-in-circuit.

PU: Implement naive folding & prover/verifier

---

saffron/src/blob.rs
saffron/src/commitment.rs
saffron/src/diff.rs
saffron/src/storage.rs

- harmonize diff structure with protocol side
- add a Commitment structure
- add a unit test for commitment update

Saffron: add update commitment logic

---

saffron/benches/read_proof_bench.rs
saffron/src/commitment.rs
saffron/src/read_proof.rs
saffron/src/utils.rs

- Factorize / clean some code
- Add structures
- Change the logic and argument provided to the functions

Saffron: read proof refactor

---

.github/workflows/saffron.yml
Cargo.toml
saffron/Cargo.toml
saffron/README.md
saffron/benches/folding_bench.rs
saffron/benches/read_proof_bench.rs
saffron/src/commitment.rs
saffron/src/diff.rs
saffron/src/folding.rs
saffron/src/lib.rs
saffron/src/main.rs
saffron/src/read_proof.rs
saffron/src/storage.rs
saffron/src/storage_proof.rs

- cleans up / fixes cargo & lib
- centralize the curve import logic in lib
- switch commitment curve from Vesta to Pallas

Saffron: switch base curve to Pallas

---

book/src/snarky/vars.md

chore: fix comment

---

poseidon/tests/poseidon_tests.rs

---
This pull request introduces small but meaningful improvements:
- Fixes minor typos and clarifies comments in `msm/src/logup.rs`.
- Improves code readability and corrects function naming in `poseidon/tests/poseidon_tests.rs`.
---

Minor Documentation and Test Improvements
