o1-labs/proof-systems

marlin-succinct/circuits/src/compiled.rs
marlin-succinct/circuits/src/index.rs
marlin-succinct/commitment/src/commitment.rs
marlin-succinct/commitment/src/urs.rs
marlin-succinct/commitment/tests/batch.rs
marlin-succinct/commitment/tests/single.rs
marlin-succinct/commitment/tests/urs.rs
marlin-succinct/protocol/src/prover.rs

URS G2 elements trimming. The set of URS G2 elements needed by the protocol is determined by the set of maximal degrees of the polynomials that are committed. This set of polynomials is determined by the set of circuits supported by the same instance of the URS. This commit removes all other URS G2 elements.
NOTE: the Index "constructor" creates single URS instance to support the protocol for that index. Next commits should generalize this to one URS instance being able to support multiple indexes/circuits.

This commit implements the following:

---

marlin-succinct/circuits/Cargo.toml
marlin-succinct/commitment/Cargo.toml
marlin-succinct/oracle/Cargo.toml
marlin-succinct/protocol/Cargo.toml

This changes all the dependencies on the algebra and ff-fft crates to the versions in the o1-labs fork of the zexe repo.

change the dependencies to o1-labs versions

---

marlin-succinct/circuits/src/index.rs
marlin-succinct/protocol/src/lib.rs
marlin-succinct/protocol/src/marlin_sponge.rs
marlin-succinct/protocol/src/prover.rs
marlin-succinct/protocol/src/verifier.rs

This PR changes the sponges used to reflect the usage in the snarky implementation. It is done this way for efficiency of the verifier circuit. The way it works is as follows.
- Before the prover sends their evaluations, we use a `BaseField`-based sponge
- After the prover sends their evaluations, we switch to using a `ScalarField` based sponge, initializing it with a digest from the `BaseField` based sponge.
I also did the following:
- The prover's evaluations are factored out into a struct. This was useful for absorbing the evaluations into the sponge, and will also be useful in reusing code with the DLog-based Marlin, since the batching in that protocol causes the evaluations data to be quite different (we require an evaluation of every polynomial on every point). 
- Challenges are now …

Sponge hand-off

---

marlin-succinct/circuits/src/index.rs
marlin-succinct/commitment/src/commitment.rs
marlin-succinct/protocol/src/prover.rs
marlin-succinct/protocol/src/verifier.rs

This PR makes a separate verifier index which only contains those values that are needed by the verifier. The one thing that still needs to be done is only taking the subset of G2 elements from the index that are needed for the degree checks, but I figured that could be done after the degree-bounded verifier is implemented.

separate out verifier index

---

Cargo.toml
dlog/circuits/Cargo.toml
dlog/circuits/src/index.rs
dlog/protocol/src/prover.rs
dlog/protocol/src/verifier.rs
dlog/tests/group_addition.rs
evaluation_domains/Cargo.toml
evaluation_domains/src/lib.rs
pairing/circuits/Cargo.toml
pairing/circuits/src/index.rs

This PR splits out the evaluation domains and splits out SRS generation for the dlog based proof.

Split out eval domains for dlog proof

---

dlog/commitment/Cargo.toml
dlog/commitment/src/commitment.rs
dlog/tests/batch.rs

This PR
1. Optimizes the computation of the "g" array in the bulletproofs opening.
2. Adds the "sg" polynomial to opening proofs so that we don't have to recompute them individually.

optimize commitment opening a bit, add sg to opening proofs

---

dlog/commitment/src/commitment.rs
dlog/commitment/src/srs.rs
dlog/protocol/src/marlin_sponge.rs
dlog/protocol/src/prover.rs
dlog/protocol/src/verifier.rs
oracle/src/marlin_sponge.rs
pairing/circuits/src/index.rs
pairing/protocol/src/marlin_sponge.rs
pairing/protocol/src/prover.rs
pairing/protocol/src/verifier.rs

This PR defines an injective map f: 2^128 -> F, and replaces a subset of the challenges `c` in marlin with `f(c)`. 
The reason is that for these challenges, the verifier previously computed `c * P` (for some point `P`), but, it is much cheaper to compute `f(c) * P` inside the circuit. Therefore, one thinks of the value `c` squeezed from the sponge as an encoding of the field element `f(c)`.
Or another way of thinking about it is that instead of sampling challenges as a uniform random 128 bit string, we select a uniformly random element from the set { f(c) | c a 128 bit challenge } and since f is injective this is ok.
The technique (which uses an endomorphism on the curve) is described in the halo paper.

Modified scalar challenge

---

dlog/commitment/src/combine.rs
dlog/commitment/src/commitment.rs
dlog/commitment/src/lib.rs
dlog/tests/batch.rs

This PR implements the affine version of the combining function for the dlog commitment. Runtime is about 20-25% better than the previous best.
E.g.,
```
$ cargo test bench_combine --release -- --nocapture
combine 100000 7.490999722s
affine_window_combine 100000 5.190810545s
affine_combine 100000 6.07763902s
window_combine 100000 6.652958733s
```
The current best is `affine_window_combine`, the previous was `window_combine`.

Affine "combine" for dlog commitment

---

dlog/plonk/src/verifier.rs

This is needed for the OCaml bindings, so that we can construct a properly-initialised oracles value.

Separate logic for initialising oracle values and actual verification

---

dlog/commitment/src/commitment.rs
dlog/commitment/src/srs.rs
dlog/marlin/src/verifier.rs
dlog/tests/marlin_group_addition.rs
dlog/tests/marlin_reduction.rs

This PR changes the marlin verify function to batch verification across proofs with different verification indexes. It requires that the indexes all have the same CRS length. This limitation shouldn't be necessary but I couldn't get it to work for now.
It also reorganizes the CRS so that if `n < m` then `create(n, 0, 0).g` is a prefix of `create(m, 0, 0).g` and `create(n, 0, 0).h == create(m, 0, 0).h`. This property is useful for batching verification across indexes of varying CRS length.

batch verification across different vks

---

circuits/plonk/src/gate.rs
circuits/plonk/src/wires.rs
dlog/plonk/src/verifier.rs

This PR implements the following additions for SNARK recursion and Plonk - Snarky bindings:
* Gate and Wire primitives for translating Snarky's wire equivalence classes into Plonk constraints
* Access to the sponge digest before evaluations from Snarky

additions for Plonk Snarky bindings and for recursion

---

circuits/plonk/Cargo.toml
circuits/plonk/src/constraints.rs
circuits/plonk/src/gate.rs
circuits/plonk/src/lib.rs
circuits/plonk/src/polynomials/endosclmul.rs
circuits/plonk/src/polynomials/poseidon.rs
circuits/plonk/src/polynomials/varbasemul.rs
circuits/plonk/src/scalars.rs
circuits/plonk/src/wires.rs
dlog/commitment/src/commitment.rs
dlog/commitment/src/srs.rs
dlog/marlin/src/index.rs
dlog/plonk/src/index.rs
dlog/plonk/src/plonk_sponge.rs
dlog/plonk/src/prover.rs
dlog/plonk/src/verifier.rs
oracle/Cargo.toml
oracle/src/poseidon.rs
oracle/src/utils.rs

This PR
- adds some functions for serialization
- changes the order of polynomial commitments in the batch to match the verifier circuits
- does batch plonk proof verification
- exposes a method to generate the plonk constraint system shifts (r, o)
- stores the underlying scalar challenge values for zeta, v, and u

Tweaks for circuits

---

dlog/plonk-5-wires/src/plonk_sponge.rs
dlog/plonk/src/plonk_sponge.rs
dlog/tests/turbo_plonk.rs
dlog/tests/turbo_plonk_5_wires.rs
oracle/src/poseidon.rs
oracle/src/sponge.rs
oracle/tests/poseidon_tests.rs

This simplifies the sponge interface so we don't need to repeatedly pass the `ArithmeticSpongeParams` everywhere.
See #116

Simplified sponge interface

---

dlog/commitment/src/commitment.rs
dlog/commitment/tests/commitment.rs

This commit cleans the batch commitment test to make it clearer. It also creates types in order to make it easier to create aggregated proofs and pass them to the verify API.
I also added a simpler unit test.

[commitment] refactored the batch commitment

---

circuits/plonk-5-wires/src/scalars.rs
circuits/plonk/src/scalars.rs
dlog/commitment/src/commitment.rs
dlog/plonk-5-wires/Cargo.toml
dlog/plonk-5-wires/src/prover.rs
dlog/plonk/Cargo.toml
dlog/plonk/src/prover.rs
oracle/src/sponge.rs

The upgrade from zexe to arkworks has removed the `ocaml::FromValue` and `ocaml::ToValue` implementations on a number of foreign types (e.g.`Fp`). Because of this, we're now working on wrapper types (e.g. `CamlFp(Fp)`) that don't necessarily implement the same traits, which makes things like this not work:
```rust
use ark_ec::AffineCurve;
// ...
#[cfg_attr(feature = "ocaml_types", derive(ocaml::ToValue, ocaml::FromValue))]
struct CamlProverProof<G: AffineCurve> {
pub commitments: ProverCommitments<G>,
pub proof: OpeningProof<G>,
// OCaml doesn't have sized arrays, so we have to convert to a tuple..
pub evals: (ProofEvaluations<Vec<Fr<G>>>, ProofEvaluations<Vec<Fr<G>>>),
pub public: Vec<Fr<G>>,
pub prev_challenges: Vec<(Vec<Fr<G>>, PolyComm<G>)>,
}
```
This PR creates (or refactor) …

[step 6] refactoring the ocaml bindings to accomodate arkworks 

---

.circleci/config.yml
Cargo.toml
circuits/plonk-15-wires/Cargo.toml
circuits/plonk-15-wires/src/lookup/scalars.rs
circuits/plonk-15-wires/src/nolookup/scalars.rs
circuits/plonk-15-wires/src/polynomials/permutation.rs
circuits/plonk/Cargo.toml
circuits/plonk/src/scalars.rs
dlog/commitment/Cargo.toml
dlog/commitment/src/commitment.rs
dlog/commitment/tests/commitment.rs
dlog/plonk-15-wires/Cargo.toml
dlog/plonk-15-wires/src/prover.rs
dlog/plonk-15-wires/src/verifier.rs
dlog/plonk/Cargo.toml
dlog/plonk/src/prover.rs
dlog/tests/poseidon_vesta_15_wires.rs
ocaml-gen/Cargo.toml
ocaml-gen/derive/Cargo.toml
ocaml-gen/derive/src/lib.rs
ocaml-gen/src/conv.rs
ocaml-gen/src/lib.rs
oracle/Cargo.toml
oracle/src/sponge.rs
rust-toolchain.toml

The idea of this PR is to avoid writing the OCaml bindings by hand, and generate them automatically from the Rust code. ([I also recorded myself going over the code a bit if that helps](https://www.loom.com/share/a96000d653614e248f6b7639838db9fb).)
In the end, you end up writing this kind of code (taken from https://github.com/MinaProtocol/mina/pull/9525):
```rust
fn main() {
println!("(* this file is generated automatically *)\n");
let env = &mut Env::default();
decl_fake_generic!(T1, 0);
decl_fake_generic!(T2, 1);
decl_module!(env, "Types", {
decl_type!(env, CamlScalarChallenge::<T1> => "scalar_challenge");
decl_type!(env, CamlRandomOracles::<T1> => "random_oracles");
decl_type!(env, CamlProofEvaluations::<T1> => "proof_evaluations");
decl_type!(env, CamlPolyComm::<T1> => "poly_comm"); …
```

[ocaml] generate bindings from Rust code

---

oracle/src/sponge.rs

In this PR I fix three issues:
* when we absorb a curve point with Poseidon, we panic if the curve point is zero
* when we use the Fq sponge to create a digest for the Fr sponge we panic if the value is too large.

[15-wires] some bug fixes

---

.github/workflows/rust.yml
circuits/plonk-15-wires/src/expr.rs
circuits/plonk-15-wires/src/nolookup/constraints.rs
circuits/plonk-15-wires/src/polynomials/chacha.rs
circuits/plonk-15-wires/src/polynomials/complete_add.rs
circuits/plonk-15-wires/src/polynomials/endomul_scalar.rs
circuits/plonk-15-wires/src/polynomials/endosclmul.rs
circuits/plonk-15-wires/src/polynomials/generic.rs
circuits/plonk-15-wires/src/polynomials/mod.rs
circuits/plonk-15-wires/src/polynomials/poseidon.rs
circuits/plonk-15-wires/src/polynomials/varbasemul.rs
circuits/plonk/src/polynomials/addition.rs
circuits/plonk/src/polynomials/endosclmul.rs
circuits/plonk/src/polynomials/permutation.rs
circuits/plonk/src/polynomials/poseidon.rs
circuits/plonk/src/polynomials/varbasemul.rs
dlog/commitment/src/commitment.rs
dlog/plonk-15-wires/src/index.rs
dlog/plonk-15-wires/src/prover.rs
dlog/plonk-15-wires/src/range.rs
dlog/plonk-15-wires/src/verifier.rs
dlog/plonk-15-wires/tests/endomul_scalar.rs
dlog/tests/endomul.rs
dlog/tests/turbo_plonk.rs

the first commit fixes the `cargo fmt` check in CI, it works as intended now:
the second commit runs `cargo fmt`

[CI] fix cargo fmt in CI

---

circuits/plonk-15-wires/src/gate.rs
circuits/plonk-15-wires/src/nolookup/constraints.rs
circuits/plonk-15-wires/src/polynomials/chacha.rs
circuits/plonk-15-wires/src/polynomials/endomul_scalar.rs
circuits/plonk-15-wires/src/polynomials/permutation.rs
dlog/plonk-15-wires/src/prover.rs
dlog/plonk-15-wires/tests/ec.rs
dlog/plonk-15-wires/tests/endomul_scalar.rs
dlog/plonk-15-wires/tests/generic.rs
dlog/tests/chacha_test.rs
dlog/tests/endomul.rs
dlog/tests/poseidon_vesta_15_wires.rs
dlog/tests/varbasemul.rs
oracle/src/rndoracle.rs
oracle/tests/poseidon_tests.rs

We currently add zero-knowledge rows to the witness on the OCaml side. This is not great as this library might be used by all sorts of people who might not think about adding the zero-knowledge stuff.

[kimchi][proof] add zero-knowledge rows in witness

---

circuits/plonk-15-wires/Cargo.toml
circuits/plonk-15-wires/src/gate.rs
dlog/plonk-15-wires/Cargo.toml
dlog/plonk-15-wires/src/index.rs

Quickly went through the different serialization format that we can use, and msgpack seems to be one of the smallest/fastest/most well-supported format.
The only other contestant is cbor, which seems to be originated from msgpack, and has an RFC. People have mix feelings, and the two standards seem close enough, that I chose the one with the best Rust support.

[kimchi] choosing messagepack as our serialization format

---

circuits/kimchi/src/expr.rs
circuits/kimchi/src/gate.rs
circuits/kimchi/src/gates/endosclmul.rs
circuits/kimchi/src/gates/generic.rs
circuits/kimchi/src/gates/poseidon.rs
circuits/kimchi/src/gates/varbasemul.rs
circuits/kimchi/src/nolookup/constraints.rs
circuits/kimchi/src/polynomials/chacha.rs
circuits/kimchi/src/polynomials/complete_add.rs
circuits/kimchi/src/polynomials/endomul_scalar.rs
circuits/kimchi/src/polynomials/endosclmul.rs
circuits/kimchi/src/polynomials/generic.rs
circuits/kimchi/src/polynomials/lookup.rs
circuits/kimchi/src/polynomials/permutation.rs
circuits/kimchi/src/polynomials/poseidon.rs
circuits/kimchi/src/polynomials/varbasemul.rs

ran `cargo clippy` in circuits/kimchi and fixed most of the links. The rest of the lints are a bit more subtle as they complain about functions that either take too many arguments or return too many values. I'm happy that clippy lints these, but we have to think a bit more about how to transform these to types.

[kimchi][circuits] fix most clippy lints

---

circuits/kimchi/src/gates/generic.rs
circuits/kimchi/src/polynomials/generic.rs
dlog/kimchi/Cargo.toml
dlog/kimchi/benches/proof_criterion.rs
dlog/kimchi/benches/proof_iai.rs
dlog/kimchi/src/bench.rs
dlog/kimchi/src/lib.rs

This PR adds a benchmark using:
* [criterion.rs](https://github.com/bheisler/criterion.rs) a benchmark crate
* [iai](https://github.com/bheisler/iai) a benchmark crate better suited for CI
@mrmr1993 @imeckler is this enough to benchmark what we want? I'm not sure how you've run the bench so far. This benchmark only uses a circuit of a few thousands of generic gates. We can add other gates into the mix, Ideally we would test all gates here. Also, this only benches:
- the witness creation (very basic one, since we don't do what's being done on the OCaml side like the creation of the permutation)
- the proof creation
- the verification of the proof
we could also separate the proof creation from the verification of the proof in two different benchmarks.

[kimchi] adding benchmarks code

---

dlog/Cargo.toml
dlog/commitment/Cargo.toml
dlog/kimchi/Cargo.toml
dlog/plonk/Cargo.toml
groupmap/Cargo.toml

Part of #230 
Hi @mimoo thanks for adding the license file in #230. However, our linter depends on license identifier too in `Cargo.toml`. This PR adds the license identifier for the required crates in this repository.
cc @willemolding

add license identifier to Cargo.toml

---

circuits/kimchi/src/gate.rs
circuits/kimchi/src/gates/endosclmul.rs
circuits/kimchi/src/gates/generic.rs
circuits/kimchi/src/gates/poseidon.rs
circuits/kimchi/src/gates/varbasemul.rs
circuits/kimchi/src/nolookup/constraints.rs
circuits/kimchi/src/polynomials/complete_add.rs
circuits/kimchi/src/polynomials/endomul_scalar.rs
circuits/kimchi/src/polynomials/generic.rs
dlog/kimchi/src/bench.rs
dlog/kimchi/tests/ec.rs
dlog/kimchi/tests/endomul_scalar.rs
dlog/kimchi/tests/generic.rs
dlog/tests/chacha_test.rs
dlog/tests/endomul.rs
dlog/tests/varbasemul.rs

I removed the field row from the CircuitGate struct. It was redundant information, as we are creating circuits by adding CircuitGate elements to an array (so their row is their position in that array). Apart from the definitions of the struct, there are changes in the verification functions for each CircuitGate, which now include a row parameter that is used to index the witness (as it was used before, but now the row is no longer a field in CircuitGate, but another parameter in those functions). This provides a less prone error instantiation of tests, as we don't need to keep track of the row index for each gate we create (in fact, I think we can still remove some variables such as first_row, last_row that appear in some tests, but I kept them for now until this change is accepted).

Removing field row from CircuitGate struct

---

.github/workflows/benches.yml

benching is a bit noisy at the moment, it writes a comment on a PR (any PR) every time there's a change there. I change the behavior so that it only benches if we apply the benchmark label. Testing in this PR (actually not sure if I can properly test this before it gets checked in).

[CI] only bench if the label benchmark is applied

---

circuits/kimchi/src/nolookup/constraints.rs
circuits/kimchi/src/polynomials/lookup.rs
dlog/kimchi/src/prover.rs

This PR removes `lookup_table_lengths` from the index, and tweaks the construction of the sorted table so that it handles duplicate values correctly.
This PR also fixes the `ValueNotInTable` error: this error now triggers when a looked-up value is absent from the source table, where previously it only fired in an edge-case.

Remove unnecessary lookup_table_lengths field in index

---

ocaml/tests/src/dune
ocaml/tests/src/lib.ml
ocaml/tests/src/ocamlgen_test.ml

This PR
* removes the `+nightly` flag to `cargo build`, which is currently unsupported on mina's CI (and unneeded for these tests)
* removes the fake `inline_tests` stanza from the dune file, replaces it with an executable and a `runtest` rule.

Update OCamlgen test for mina compatibility

---

.github/workflows/sourcegraph.yml

This github action will allow us to have better browsable source code on [sourcegraph](https://sourcegraph.com/github.com/o1-labs/proof-systems@mimoo/ra/-/blob/circuits/kimchi/src/polynomials/lookup.rs).

[CI] add github action to enable sourcegraph.com

---

circuits/kimchi/Cargo.toml
dlog/commitment/src/commitment.rs
utils/src/dense_polynomial.rs

I accidentally committed some debug lines which were computing completely unused polynomial commitments inside the opening function. This removes that and also optimizes the code for combining polynomials to an improved version. In testing this improved prover performance by about 15-20% :sweat_smile:

Fix performance bug

---

circuits/kimchi/Cargo.toml
dlog/commitment/src/combine.rs
dlog/commitment/src/commitment.rs

This PR uses the endomorphism to compute the `g1 + x * g2` step of the commitment opener. The result is a roughly 2x overall speedup in prover time. E.g., with domain size 2^14, prover time has gone from 2.830285628s to 1.440663255s.
Algorithm 1 of https://eprint.iacr.org/2019/1021.pdf (on page 19) was used as a reference.

2x-ish speedup from endomorphism

---

kimchi/src/circuits/gate.rs

This PR moves the lookup `table_id` from `SingleLookup` to `JointLookup`.
Since we never want to do a 'joint lookup' from multiple tables -- the values we look up will all come from the same table, combined in the same row -- it makes sense for it to live on the `JointLookup` instead.
This is a small part of the work towards implementing #250.

Move table_id from SingleLookup to JointLookup

---

kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/index.rs
kimchi/src/prover.rs
kimchi/src/tests/chacha.rs

I perform several changes to the chacha gate:
* separate the different chacha gates into different functions (the previous code wasn't making it clear that we're dealing with 4 gates)
* closures -> functions, this will facilitate changes when we use the alpha iterator later
* move functions for testing in a `testing` module

[gate][chacha] refactor to distinguish the different subgates

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/gate.rs
kimchi/src/tests/chacha.rs

This PR
* tracks the table associated with each gate that uses lookups
* generates the table when used, automatically inserting it into the list of tables considered when creating the proof
* removes the explicit use of `xor_table` in the chacha test

Automatically infer and expose used tables from used gates

---

kimchi/src/circuits/gate.rs
utils/Cargo.toml
utils/src/hasher.rs
utils/src/lib.rs

this introduces the CryptoHash trait, which you can implement for a type to get access to a `digest()` function:
```rust
#[derive(Serialize)]
struct A {
thing: u8,
}
impl CryptoDigest for A {
const PREFIX: &'static [u8; 15] = b"kimchi-circuit0";
}
println!("digest: {:?}", a.digest());
```
The `PREFIX` is a domain-separation string that is simply prepended to the real input.
Benefit of this approach:
* less error-prone since we generate the boilerplate by implementing the trait
* uses a domain-separation string by default
It would be nice if:
* we could just use a macro
```rust
#[derive(Serialize, CryptoDigest("kimchi-circuit")]
struct A { 
```
* we could make sure all types that implement CryptoDigest use different prefixes
* the hash state with the prefix is pre-computed (for example …

Introduce a CryptoHash trait to easily hash types

---

kimchi/src/circuits/expr.rs

This PR is the minimal possible fix for the poseidon failure in the WASM version of the code.
This was caused by the assumption that `usize` is always 64-bit -- where it's 32-bit under WASM -- and is a symptom of misusing `usize` for unsigned integers that aren't related to memory accesses.

Fix 32-bit arch expr::pow by using the correct number of bits

---

kimchi/src/bench.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/poseidon.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/verifier.rs

before:
* we expected the verifier to pass enough lagrange bases that we have public inputs
* verify was a batch verify function
after:
* we rely on the pre-computed lagrange bases we already have
* verify -> batch_verify

[verifier] reuse pre-computed lagrange bases we already have

---

kimchi/src/tests/generic.rs
kimchi/src/verifier.rs

no need to return a bool since it's always `true` anyway

[esy][verifier] return () instead of bool

---

kimchi/src/bench.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/tests/poseidon.rs
kimchi/src/verifier_index.rs
tools/kimchi-visu/src/lib.rs

refactors `Index` to `ProverIndex` as mentioned in #379
`cargo test`, `cargo check` and `cargo build` all run successfully
closes #379

rename Index to ProverIndex

---

kimchi/src/circuits/gates/poseidon.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/tests/poseidon.rs
oracle/src/poseidon.rs

This PR:
- re-orders consts in `SpongeConstants` trait such that sponge and permutation params are grouped.  
- Adds a `PERM_` prefix to permutation params in the `SpongeConstants` trait. 
- Rename `SPONGE_BOX` to `PERM_SBOX` in the `SpongeConstants` trait.
closes: #390

re-order and rename consts in SpongeConstants trait

---

kimchi/src/alphas.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/lookup.rs
kimchi/src/linearization.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/verifier_index.rs

This is PR #405 cherry-picked onto master. To quote from there:
> This PR builds upon https://github.com/o1-labs/proof-systems/pull/400, splitting out a LookupConfig structure from the rest of the LookupConstraintSystem. LookupConfig doesn't depend on the contents of the lookup tables, and so can be shared across multiple different constraint systems.
> In particular, this is useful for generating a linearisation in the OCaml bindings, since we can specify the 'shape' of lookup tables in the verifier, but we can't be confident of the table's contents.

Split out non-table-specific parts of `LookupConstraintSystem` (redux)

---

kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/lookup.rs

This PR generalises `JointLookup` so that it can handle `SingleLookup<F>`s, `F`s, or `Expr<ConstantExpr<F>>`s as arguments, and relaxes the constraints on `combine_table_entry`.
This allows us to
* store the 'dummy' lookup value as a `JointLookup` in the constraint system, rather than unpacking and re-packing it
- not done here; this will be in a follow-up PR
* unify the 3 different implementations of `combine_table_entry` into one
- happily, the 'fold' implementation in `combine_table_entry` minimises the number of multiplications compared to the others, so this is also an efficiency gain
* have a single point to change when we add `table_id`s

Use a single implementation for `combine_table_entry`

---

kimchi/src/bench.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/poseidon.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
utils/src/lib.rs
utils/src/math.rs

moves `ceil_log2` into the package `o1_utils::math` under `utils/src/math.rs`
see https://github.com/o1-labs/proof-systems/issues/386

move ceil_log2 into o1_utils::math package

---

kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/complete_add.rs
kimchi/src/circuits/polynomials/endomul_scalar.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/varbasemul.rs

looks like we forgot to remove those when we moved away from using the `Argument` type for lookup.

[easy][gates] remove Default implementation

---

poly-commitment/src/commitment.rs
utils/src/math.rs

This is a follow-up to https://github.com/o1-labs/proof-systems/pull/436 which moves the corresponding test case of `ceil_log2` into the newly created `math` module in order to keep the code and structure clean (forgot it with last PR)

move ceil_log2 tests into math module

---

book/src/specs/kimchi.md
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
tools/kimchi-visu/src/lib.rs
utils/Cargo.toml
utils/src/lib.rs
utils/src/types.rs

This PR renames and migrates commonly used field types.  The types have been renamed from `Fr` and `Fq` to `ScalarField` and `BaseField`.  They have been migrated to `o1_utils::types::fields::*` where they can be used across crates.  I have added explicit type declaration for:
```
//~ 18. Derive $\alpha$ from $\alpha'$ using the endomorphism (TODO: details)
- let alpha = alpha_chal.to_field(&index.srs.endo_r);
+ let alpha: ScalarField<F> = alpha_chal.to_field(&index.srs.endo_r);
```
but received a compilation error when applying the following change so it has not been included:
```
- let alpha_chal = ScalarChallenge(fq_sponge.challenge());
+ let alpha_chal: BaseField<F> = ScalarChallenge(fq_sponge.challenge());
```
It should be noted that this PR also includes changes to the kimchi book …

Field aliases

---

utils/src/math.rs

unit test case for `ceil_log2` wasn't being asserted, only printed. Add `assert!(res == *expected)` to it

add assert to test

---

hasher/README.md
hasher/src/lib.rs
hasher/src/roinput.rs
hasher/tests/hasher.rs

This PR allows chaining multiple `append_*` functions in `ROInput`.
@jspada  plz take a look and let me know your feedback, thx!
e.g.
```rust
let mut roi: ROInput = ROInput::new();
roi.append_bool(false)
.append_bool(true)
.append_bool(false)
.append_bool(false)
.append_bool(true);
```

ROInput append_* fn chaining

---

hasher/Cargo.toml
hasher/README.md
hasher/src/lib.rs
hasher/tests/hasher.rs

This PR re-exports the Hash type (`Fp`) of the `Hasher<H: Hashable>` trait, so that the caller doesn't need to explicitly depend on the `mina-curves` crate to use this Hash type. 
@jspada plz take a look and let me know your feedback, thx!

Re-export Hash type of the Hasher trait

---

kimchi/src/prover.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
poly-commitment/tests/batch_15_wires.rs
poly-commitment/tests/commitment.rs
utils/src/chunked_polynomial.rs
utils/src/dense_polynomial.rs
utils/src/lib.rs

This PR (related to issue #432):
- add a new module  in `utils/chunked_polynomial.rs` with an abstract struct `ChunkedPolynomials`.
- the new `ChunkedPolynomials` struct contains two method: `linearize` and `compress_polynomial`. `linearize` evaluates all the chunked polynomials in the same point. `compress_polynomial` compresses all the chunked polynomials into one with `zeta_n`.
- refactor the original struct `ChunkedPolynomial` with `ScaledChunkedPolynomials` based on the above abstract. This struct contains `(Vec[F], Vec[P])`.
-  add a function `to_chunked_polynomials` in trait `ExtendedDensePolynomial`, which allows to transfer polynomials into multiple chunks.
- modify accordingly in the `prover.rs` file.

refactor ChunkedPolynomials

---

ocaml/ocaml-gen/derive/src/lib.rs

This PR tweaks ocaml-gen to use snake-case for type parameters. This makes it far easier to use OCaml derivers etc., which are currently broken by the capitalisation that we use for variables.
Example output:
```ocaml
type nonrec 'caml_f scalar_challenge = { inner : 'caml_f } [@@boxed]
type nonrec 'caml_f random_oracles =
{ joint_combiner : 'caml_f scalar_challenge * 'caml_f
; beta : 'caml_f
; gamma : 'caml_f
; alpha_chal : 'caml_f scalar_challenge
; alpha : 'caml_f
; zeta : 'caml_f
; v : 'caml_f
; u : 'caml_f
; zeta_chal : 'caml_f scalar_challenge
; v_chal : 'caml_f scalar_challenge
; u_chal : 'caml_f scalar_challenge
}
```

Fixup ocaml-gen to emit snake-case type parameters

---

hasher/README.md
hasher/src/roinput.rs

This PR changes the signature of `append_hashable` in `mina_hasher::Hashable` from `fn append_hashable(&mut self, input: impl Hashable)` to `fn append_hashable(&mut self, input: &impl Hashable)`
When it takes an owned value, it forces an unnecessary `clone` or `copy` at caller, like in the original doc example, `roi.append_hashable(self.a1);` works because `struct A` derives `Copy` and an implict `copy` happens here.

[mina-hasher] Change append_hashable to take borrow param

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/endomul_scalar.rs

This is a specification of the `endomul_scalar` gate. 
It includes the previous documentation comments as part of the spec now, together with a bunch of new content to explain more verbosely the resulting constraints.

specify endomul_scalar gate

---

signer/src/pubkey.rs

It would be great if you could add derivations of `Debug` `PartialEq` and `Eq` to the public API for `CompressedPubKey`. This makes it consistent with `PubKey` and makes it much easier to integrate into our internal types which use the above traits for tests.
I've also included a helper for `from_address`, this is just a nice-to-have and not required.

Add derives to compressed pub key

---

book/src/specs/kimchi.md
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/tables.rs
kimchi/src/error.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

- added an `LookupCommitmentMissing` error instead of crashing if a commitment is missing in the proof
- added some spec comment

[easy][lookup] light cleanup

---

kimchi/src/prover.rs
poly-commitment/src/evaluation_proof.rs

Whenever both `UniformRand` and `UVPolynomial` traits are used, the rust-analyzer complains when accessing the `rand` function inside `UniformRand` (using only 1 argument), and expects the 2 arguments of the `rand` in `UVPolynomial`. Nonetheless, the execution correctly chooses the correct function. I will create an issue (here https://github.com/rust-lang/rust-analyzer/issues/12119) for the rust-analyzer team to fix this conflict. In the meantime, @mimoo suggested to cast `ScalarField<G>` as `UniformRand`, so that the `rand` function is interpreted correctly even at the rust-analyzer level.

fix rust-analyzer complaint about `rand` function

---

book/src/specs/kimchi.md
kimchi/src/circuits/expr.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/scalars.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

In this PR I do three things:
* I create a `LookupContext` struct in `prover.rs` to keep track of variables that are related to the lookup flow. This is so that we can track them across optional blocks (as lookup is an optional feature) instead of tracking a bunch of variables that pollute the scope
* I enclose each steps related to the lookup feature within a `if let Some(lcs) = &index.cs.lookup_constraint_system {`
* I add specification comments where relevant
(I tried to split the changes incrementally in commits)

[lookup] refactor prover + spec

---

book/src/fundamentals/custom_constraints.md

fix broken `code` highlighting
https://o1-labs.github.io/proof-systems/fundamentals/custom_constraints.html, under `Under such configuration, a circuit is specified by`, point 2

fix broken markdown code highlighting

---

kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/prover.rs

check the commits, they:
1. remove the type `UncombinedEntry` as it was deadcode
2. remove the type `CombinedEntry` (which allows us to remove the trait `Entry`) as it doesn't seem to serve much purpose
3. simplify `sorted` to take an iterator instead of a closure, this simplifies the signature and the code

[lookup] simplify code

---

kimchi/src/verifier.rs

The lookup table commitment is linearized, thus we do not use it to compute the commitment to the "combined linearized constraints" (we should really find a name for that polynomial).

[lookup] remove unreachable code

---

cairo/src/memory.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/circuits/polynomials/range_check/witness.rs

* Add connect_cell_pair() helper
* Wire up copy constraints
* Change create_range_check interface to take start row and return next row
* Improve verify_range_check() to handle perm_aggreg exceptions
* Fix witness creation (size from 8 to 4 rows) to work on single set of three 88-bit limbs
Closes #558

Implemented range-check gate wiring for permutation argument

---

book/src/specs/kimchi.md
kimchi/Cargo.toml
kimchi/src/bench.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/mod.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/circuits/polynomials/chacha.rs
kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/error.rs
kimchi/src/linearization.rs
kimchi/src/plonk_sponge.rs
kimchi/src/proof.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/lookup.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs

This PR implements runtime tables, following [RFC: Extended lookup tables](https://github.com/o1-labs/proof-systems/pull/250). 
**setup**:
**prover side**: 
**verifier side**:
**ocaml**:
**tests**:
proof:
```diff
pub struct LookupCommitments<G: AffineCurve> {
// ...
+    /// Optional Commitment to concatenated runtime tables
+    pub runtime: Option<PolyComm<G>>,
}
pub struct LookupEvaluations<Field> {
// ...
+    /// Optionally, a runtime table polynomial
+    pub runtime: Option<Field>,
}
```
prover index:
```diff
pub struct LookupConstraintSystem<F: FftField> {
// ...
+    /// An optional runtime table selector. It is 0 everywhere,
+    /// except at the rows where the runtime tables apply.
+    pub runtime_selector: Option<E<F, D<F>>>,
// ...
}
pub struct LookupConfiguration<F: …
```

implementation of runtime tables

---

kimchi/src/error.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

in practice it is possible that using SRS that have a smaller size than the domain could work, as we support splitting every polynomials we use, but I'm not sure we did think of every corner cases. It's probably safer to just not allow this edge-case.

enforce length of SRS to be at least the domain size

---

kimchi/src/linearization.rs

https://github.com/o1-labs/proof-systems/issues/352

[easy] enforce that alpha^0 is used for generic gate

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/prover_index.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/lookup.rs

currently the first column of all runtime tables is an indexed column (0, 1, 2, ...)
this PR allows the first column to be determined arbitrarily at setup

[lookup][runtime] making first column of runtime tables customizable

---

.github/workflows/rust.yml
book/book.toml
book/src/specs/kimchi.md
kimchi/src/circuits/lookup/index.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

New version of cargo spec allows us to use `//~~` for nested lists, which will make it nicer to write specs.
Also, I just use `1.` everywhere for lists, which is easier to maintain as we move things around or add/remove steps.

[specs] moving to cargo-spec 0.4.1

---

kimchi/src/circuits/lookup/lookups.rs

This PR builds upon #579, separating out the different built-in lookup patterns as an explicit enum that maps into the patterns.

Factor out lookup layouts by LookupPattern

---

kimchi/src/proof.rs

This PR tweaks the OCaml types conversions so that the OCaml code can access the lookup evaluations.

Expose lookup evaluations to OCaml

---

book/src/specs/kimchi.md
kimchi/src/circuits/gate.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/circuits/lookup/tables/range_check.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/circuits/polynomials/range_check/witness.rs
kimchi/src/verifier.rs
utils/src/field_helpers.rs

This adds the lookups needed in the range check gate. 
TODO:
Closes #559

[WIP][gates][range] add lookups

---

book/src/specs/kimchi.md
kimchi/src/circuits/expr.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs

This PR builds on top of #583.
This refactors the `lookup_selectors` store to use a structured `LookupSelectors` record. This allows us finer-grained control over which selectors are used or unused, which we couldn't previously have with the vector-position system.

Use explicitly-labelled lookup selectors

---

kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/chacha.rs

This PR builds upon #584.
This tweaks the logic in `ConstraintSystem::create` so that it only uses the lookups for gates that are present in the circuit. In particular, this allows us to migrate the pickles recursion layer to using these lookups without needing to support the `LookupPattern`s for all possible gates.

Only add lookup selectors for used gates

---

kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/circuits/polynomials/range_check/mod.rs
kimchi/src/circuits/polynomials/range_check/witness.rs

This adds 64-bit range check support.  This can be done with a single `RangeCheck0` circuit gate / row by copying the cells in columns 1 and 2 to zero, i.e. by adding two copy constraints.
Closes #592

64-bit range check support

---

circuit-construction/src/prover.rs
circuit-construction/src/writer.rs

Cache constants the same way the OCaml code does.
When writing this, and the double generic gate, it feels like I'm writing redundant or unnecessary code sometimes. It makes me think that if `Cs` was implemented on a single struct, combining both `System` and `WitnessGenerator`, it would be leaner. IIUC this is what the OCaml code is doing, but this is also what arkworks r1cs std is doing

[kombucha] implement cached constants

---

kimchi/src/circuits/polynomials/range_check/gate.rs
kimchi/src/prover_index.rs
kimchi/src/verifier_index.rs
tools/kimchi-visu/src/lib.rs

This PR fixes the Cargo Clippy warnings detected by rust 1.62.0 and it's compatible with current fixed rust 1.58.0.

Fix cargo clippy warnings in rust 1.62.0

---

book/src/specs/kimchi.md
kimchi/src/prover.rs
kimchi/src/verifier.rs

This PR tweaks the prover and verifier to absorb the previous challenge commitments at the beginning of proving and verification. This ensures that these previous challenge commitments are involved with the Fiat-Shamir non-interactivity modification, so that Kimchi is sound without the use of pickles.

Absorb previous challenge commitments at the start of proving / verification

---

utils/src/chunked_polynomial.rs
utils/src/field_helpers.rs
utils/src/lib.rs

Since everything is well commented in the `utils` crate, let's enforce docs there while we still can

[utils] enforce docs in utils

---

kimchi/src/lib.rs
kimchi/src/oracles.rs
kimchi/src/verifier.rs

this PR tries to get rid of that logic on the OCaml side: https://github.com/MinaProtocol/mina/blob/f01d3925a2/src/lib/crypto/kimchi_bindings/stubs/src/oracles.rs#L28
by moving the code here

[ocaml] moving the oracle logic from stubs to proof-systems

---

hasher/README.md
hasher/src/roinput.rs
hasher/src/tests/hasher.rs
hasher/src/tests/mod.rs
signer/src/schnorr.rs
signer/tests/transaction.rs

This PR proposes API change in `ROInput` to use the [builder(-like) pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) to remove boilerplate code of defining mutable local variable in most cases.
before:
```rust
fn to_roinput(&self) -> ROInput {
let mut roi = self.input.to_roinput();
roi.append_field(self.pub_key_x);
roi.append_field(self.pub_key_y);
roi.append_field(self.rx);
roi
}
```
after:
```rust
fn to_roinput(&self) -> ROInput {
self.input
.to_roinput()
.append_field(self.pub_key_x)
.append_field(self.pub_key_y)
.append_field(self.rx)
}
```

Update ROInput API to use builder pattern

---

utils/src/field_helpers.rs
utils/src/foreign_field.rs

This PR fixes the to/from_big functions for field elements that used our own functions inside and now just uses Into/From implementations in PrimeField as suggested by David.

[easy] Fix BigUint converters

---

signer/src/pubkey.rs

The default value aligns with `empty` in [`non_zero_curve_point.ml`](https://github.com/MinaProtocol/mina/blob/develop/src/lib/non_zero_curve_point/non_zero_curve_point.ml#L90), it's useful for implementing default account etc.
```OCaml
let empty = Poly.{ x = Field.zero; is_odd = false }
```

fn CompressedPubKey::empty()

---

Cargo.lock
kimchi/src/snarky/constants.rs
kimchi/src/snarky/constraint_system.rs
kimchi/src/snarky/mod.rs

from https://github.com/o1-labs/proof-systems/pull/542:

[snarky] completing missing elements

---

Cargo.lock
poly-commitment/Cargo.toml
poly-commitment/src/tests/commitment.rs

This PR adds a deterministic version of the commitment test, to ensure that we are reliably testing commitments that feature a 'zero' commitment.
This is part of the work on #724, but separated since it is orthogonal and good-to-have anyway.

Add a deterministic version of the commitment unit test

---

kimchi/src/verifier.rs
poly-commitment/src/commitment.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs

This PR renames `xi` and `r` to `polyscale` and `evalscale` respectively, so that the same descriptive names are used for `open` in `evaluation_proof.rs` and `verify` in `commitment.rs`.

[Trivial] Rename function parameters to be consistent between different functions

---

poly-commitment/src/evaluation_proof.rs

This PR tidies up the code in `open`, unifying the two implementations and using more idiomatic rust.

Tidy up `open`

---

kimchi/src/prover.rs
kimchi/src/tests/generic.rs
kimchi/src/verifier.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
utils/src/dense_polynomial.rs

This PR tweaks the handling of public inputs, so that the public input commitment can be allowed to be all-zero.
The handling of zero polynomials and commitments is special-cased in lots of places in the code, so this was a rather tricky change to make. In particular, the 'commitments' test is still broken (via a probabilistic flake), since it depends more closely on some of those special cases.
This is ready for review, but should not be merged until the flaking test is fixed.

Allow an all-zero public input

---

kimchi/src/circuits/expr.rs
kimchi/src/tests/range_check.rs

* This enables direct printing of the constraints or values therein (e.g. for debugging)
* Depending on the `ArgumentEnv`, displays either text for `Expr<ConstantExpr<F>>` or actual values for `Field`
* Remove range-check use of `Wire::create` (by the way improvement)

Implement fmt::Display for ExprOps types

---

kimchi/src/prover.rs
kimchi/src/verifier_index.rs

This PR introduces the concept of 'fixed hiding' for commitments. This is equivalent to using a blinding value of `1`, which we can use to transform zero commitments into non-zero commitments that can be consumed by pickles.
This PR only updates the generic and poseidon selectors; in order to convert the remaining commitments, we will need to propagate the blinding constants more carefully to unsure that the linearization works correctly. A PR implementing this will follow.

Use 'fixed hiding' commitments for generic and poseidon selectors

---

circuit-construction/src/lib.rs
circuit-construction/src/prover.rs
circuit-construction/src/tests/example_proof.rs
poly-commitment/src/commitment.rs
poly-commitment/src/srs.rs

Ideally we shouldn't need to add additional bounds when we use a `KimchiCurve` type. It looks like I can't write `trait KimchiCurve : CommitmentCurve<BaseField: PrimeField>` so this is another way to encode that in the trait. It seems to work.

[SRS] encode bound on basefield of commitmentcurve in trait

---

kimchi/src/circuits/mod.rs
kimchi/src/circuits/polynomials/foreign_field_add/witness.rs
kimchi/src/circuits/polynomials/range_check/witness.rs
kimchi/src/circuits/witness/constant_cell.rs
kimchi/src/circuits/witness/copy_bits_cell.rs
kimchi/src/circuits/witness/copy_cell.rs
kimchi/src/circuits/witness/copy_shift_cell.rs
kimchi/src/circuits/witness/mod.rs
kimchi/src/circuits/witness/variable_cell.rs
kimchi/src/circuits/witness/variables.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/range_check.rs

Extract common witness computation code from range-check and foreign-field-add gates into reusable generic kit for foreign field multiplication and other custom gates

Implement generic witness layout for custom gates

---

kimchi/src/alphas.rs
kimchi/src/bench.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/xor.rs
kimchi/src/circuits/wires.rs
kimchi/src/snarky/asm.rs
kimchi/src/snarky/constraint_system.rs
kimchi/src/snarky/mod.rs
kimchi/src/tests/chacha.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/lookup.rs
kimchi/src/tests/poseidon.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/tests/xor.rs
tools/kimchi-visu/src/main.rs

This PR adds an ASM-like language that's useful to inspect circuits and debug. (It also adds the public input size to the `Circuit` type, and adds some convenience functions, to make this work.)
It looks like this:
```
row0.pub.Generic<1,0,0,0,0>
.l1 -> row4.l1
row1.pub.Generic<1,0,0,0,0>
.l1 -> row2.l1
row2.Generic<-1,0,0,1,0><-1,0,0,1,0>
.l1 -> row4.r1, .r1 -> row1.l1
.l2 -> row0.l1, .r2 -> row2.l2
row3.Generic<-1,0,0,1,0><-1,0,0,1,0>
.l1 -> row4.r2, .r1 -> row3.l1
.l2 -> row4.l2, .r2 -> row3.l2
row4.Generic<0,0,1,-1,0><0,0,1,-1,0>
.l1 -> row2.r2, .r1 -> row2.r1, .o1 -> row5.l1
.l2 -> row3.r2, .r2 -> row3.r1, .o2 -> row4.o1
row5.Generic<1,0,0,0,-1>
.l1 -> row4.o2
```
See https://github.com/MinaProtocol/mina/pull/12125 to see it used in tests

introduce an ASM-like language for debugging

---

utils/src/dense_polynomial.rs

**What's been done here:**
Replace the horner method of [here](https://github.com/o1-labs/proof-systems/blob/master/utils/src/dense_polynomial.rs#L45-L53) with the standard method(`DensePolynomial::from_coefficients_slice(coeffs).evaluate(&point)`) of `arkworks` crate.
Reference: #437

Replace the horner method with arkworks(ark_poly) method

---

book/book.toml

Add the `[output.katex]` line to `book/book.toml` file for the compatibility of using the `mdbook-katex` crate(**v0.2.17**)

Fix the mdbook build issue coming from CI(`gh-page.yml`)

---

book/src/plonk/inner_product.md

**What's been done:**
Add the NOTE message of possible misunderstanding of IPA scheme explain
in `book/src/plonk/inner_product.md` file
Reference: #502

Fix the error of `inner product scheme` explain in mina book

---

.github/workflows/rust.yml
kimchi/src/circuits/witness/variables.rs

`cargo test` runs doc tests by default. This PR fixes them so that they pass, and adds a command to CI to ensure that they don't break again.

Fix doc-tests, add them to CI

---

kimchi/src/alphas.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/expr.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/permutation.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/xor.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/verifier_index.rs

This PR moves the polynomials out of the `ConstraintSystem` structure, and into sub-structures.
This is part of a longer term plan to remove them from `ConstraintSystem` entirely, and to place them in `ProverIndex`. The constraint system should define the layout of the circuit; these precomputations don't contribute to that goal.

Move polynomials out of ConstraintSystem

---

kimchi/src/alphas.rs
kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/constraints.rs
kimchi/src/linearization.rs
kimchi/src/prover_index.rs

This PR adds a `FeatureFlag` structure, marking the 'optional features' used by the constraint system, and uses it for the linearization.

Add feature flags for optional gates

---

kimchi/src/circuits/constraints.rs

This PR simplifies the logic in `constraints::Builder::build`, using the `selector_polynomial` helper wherever possible.
This PR builds upon #867.

Use `selector_polynomial` helper for all unevaluated selectors

---

kimchi/src/prover.rs
kimchi/src/verifier.rs
poly-commitment/src/commitment.rs

This PR updates the prover and verifier to absorb the shifted commitments in `PolyComm`, via a new helper function `absorb_commitment`.
This builds upon #870.

Absorb shifted commitments

---

poly-commitment/src/commitment.rs

clearer, but also it returns early when it can, and it only computes the `into_repr()` of the scalars once

[commitment] rewrite MSM function over polycomm to make it clearer

---

kimchi/src/prover.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs
poly-commitment/src/commitment.rs
poly-commitment/src/srs.rs

This PR tweaks the SRS precomputations to calculate a 'chunked' representation of the Lagrange commitments.
The lack of this prevented the 'chunked' approach from working with public inputs. This brings us closer to a working version of the chunked prover.

Compute 'chunked' Lagrange commitments

---

kimchi/src/alphas.rs
kimchi/src/circuits/expr.rs
kimchi/src/linearization.rs
kimchi/src/prover_index.rs

This PR
* adds an `EnabledIf` constructor for `Expr` (and a `SkipIf` counterpart for the `PolishToken` variant)
- the implementation for these is still to-do; they're not used by anything here, so everything still works
* tweaks the `linearization` functions to accept an `Option<FeatureFlags>`, which uses the `EnabledIf` form if no feature flags are given
This then generates code on the OCaml side that can be used to (optionally) enable the logic for these gates, making it easier to update pickles for new gate kinds.

Allow feature-flagged gates to be exposed to OCaml

---

poly-commitment/src/srs.rs

This PR fixes an oversight in #870, which is triggered by proofs on the Mina side with very small circuit sizes.

Don't create a shifted segment when the domain size is smaller than srs

---

book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/foreign_field_mul/witness.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/range_check/witness.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/range_check.rs
utils/src/foreign_field.rs

This PR adds the ability to constrain 2-limbs format (i.e. compact limbs) values with the multi-range-check gadget.
Normally the gadget can only constrain 3 limbs (`v0, v1, v2`) that are copied to column 0 of the first 3 gates of the gadget, like this
| 0  `RangeCheck0` | 1   `RangeCheck0`  | 2    `RangeCheck1` | 4 `Zero`  |
| -- | -- | -- | -- | 
| `v0` (copy) | `v1` (copy) | `v2` (copy) | ... |
| ... | ... | ... | ... |
This change allows one to copy the limbs in compact form: `v01`, `v2` to the gadget in order like this
| 0   `RangeCheck0`  | 1   `RangeCheck0`  |  2    `RangeCheck1` | 4 `Zero`  |
| -- | -- | -- | -- | 
| `v2` (copy) | `v0` | `v1` | ... |
| ... | ... | `v01` (copy) | ... |
| ... | ... | ... | ... |
where $v_{01} = v_0 + 2^{88} \cdot v_1$.
The change is comprised of two …

Add support for compact limbs (2 limb mode) to multi-range-check gadget

---

book/src/rfcs/foreign_field_mul.md
book/src/specs/kimchi.md
kimchi/src/circuits/gate.rs
kimchi/src/circuits/lookup/lookups.rs
kimchi/src/circuits/polynomials/foreign_field_mul/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/witness.rs
kimchi/src/tests/foreign_field_mul.rs

* Halve the number of plookups
* Eliminate custom constraint for scaling carry1_hi
* Remove unused CircuitGateErrors (n.b. clippy doesn't detect these)
* Add native modulus constraint test case
Speedup:
- time to create prover index: 62.8/62s ~ 1.3%
- time to create proof: 36/27s ~ 33%
- time to verify: 870/837ms ~ 3.9% 
```text
OPT1
- time to create prover index: 62s
- time to create proof: 27s
- time to verify: 844ms
- time to create prover index: 62s
- time to create proof: 27s
- time to verify: 838ms
- time to create prover index: 62s
- time to create proof: 27s
- time to verify: 834ms
- time to create prover index: 62s
- time to create proof: 27s
- time to verify: 837ms
- time to create prover index: 62s
- time to create proof: 27s
- time to verify: 832ms
=== averaged over 5 runs === …
```

Non-native field multiplication optimization 1

---

book/src/rfcs/foreign_field_add.md
book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/foreign_field_add/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/foreign_field_add/witness.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs

This PR addresses the final pending TODO inside the FFAdd gate that consists on moving the sign value to the coefficients of the gate. This is not only an aesthetic change, as it indeed makes sense that the operation being performed is known and part of the relation itself, but it also brings soundness to the final bound check of any FFAdd chain. In other words, we did not have enough space in copyable cells to both constrain that the sign of the final check is a "+" and that the final overflow flag is 1. By removing the sign from the layout, we can now constrain the overflow flag, and the sign can be publicly checked to be the right value. 
It is not clear to me though if we want to keep the `(sign - 1) * (sign + 1) = 0` constrain, as it is just a coefficients check and thus reducing …

FFAdd sign update inside coefficients

---

kimchi/src/circuits/gate.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs

This PR adds a function `connect_ffadd_range_checks` inside the `Connect` trait to more easily configure the wiring of foreign field additions, given the row of the actual addition, and (optionally) any number of rows of the range checks of the left input, right input, and result. It can be reused by setting Left and Right to None for the bound check range check.

[easy] Add a connect function for the range checks in FFAdd

---

book/src/specs/kimchi.md
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/permutation.rs
kimchi/src/lagrange_basis_evaluations.rs
kimchi/src/lib.rs
kimchi/src/prover.rs
kimchi/src/prover_index.rs
kimchi/src/verifier_index.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs

This PR removes dense polynomial forms of evaluated columns from the prover index, instead using evaluations forms directly to evaluate and open those polynomials. The result is (currently) one more size n FFT in the opening proof and reduced prover memory. It also paves the way for opening all the polynomials (in order to remove the linearization technique) without any increase in prover memory usage.
It does not currently allow the evaluations form polynomials to have size greater than n. This would require changing chunking to happen post-accumulation (rather than on a per-polynomial basis) which can be done in a follow up PR.

Remove dense polynomial forms

---

kimchi/src/circuits/polynomials/and.rs
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/not.rs
kimchi/src/circuits/polynomials/rot.rs
kimchi/src/circuits/polynomials/xor.rs
kimchi/src/tests/and.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/not.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/xor.rs

This PR provides extend functions to all of Xor, And, Not, Rot.  This function allows the gadgets to appear anywhere in the circuit (not only assuming the row 0).

[easy] Extend function for custom gates

---

.github/workflows/rust.yml

This ensures that we don't get to the end of the slow CI run only to realise that one of the faster checks is failing right at the end.

Run fast checks first in CI

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/tables/mod.rs
kimchi/src/circuits/lookup/tables/range_check.rs
kimchi/src/circuits/lookup/tables/xor.rs
kimchi/src/tests/and.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/keccak.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/xor.rs

This PR builds upon #1014, using the size of the lookup tables to calculate the domain size required for a proof. The domain size is now at least `max(num_gates, num_lookups+1)+ZK_ROWS`.
This PR also removes the copy-pasted `1 << 13` padding from a large number of tests. Despite mostly using smaller lookup tables, it seems that this was blindly pasted everywhere, which contributed at least in part to the slow tests in CI.

Account for lookup tables when computing the domain size

---

kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/prover_index.rs
kimchi/src/tests/framework.rs
kimchi/src/tests/range_check.rs

This PR restructures some tests to be less wasteful. Previously, they were taking about 3-4 mins each on CI because of poor caching.

Stop re-running a whole test setup for small tweaks to the witness

---

.github/workflows/rust.yml
CONTRIBUTING.md

CI is failing with
```
error: failed to run custom build command for `ocaml-sys v0.22.3`
```
even for things like adding a line to a markdown file.
This PR is to figure out why and hopefully fix it.

Figure out what's broken in CI (and fix it)

---

kimchi/src/snarky/constraint_system.rs
kimchi/src/tests/and.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/lookup.rs
kimchi/src/tests/not.rs
kimchi/src/tests/poseidon.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/recursion.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/tests/xor.rs

This replaces the `assert!(foo.is_ok())` in tests with `foo.unwrap()`, emitting the underlying error message instead of a non-descriptive assertion.

Tweak tests to emit useful errors

---

book/src/plonk/overview.md

I'm trying to build ebook with mdbook-epub and found this linked image is not found.

Fix image link for plonk/overview.md

---

book/src/rfcs/foreign_field_mul.md
kimchi/src/circuits/polynomials/foreign_field_add/gadget.rs
kimchi/src/circuits/polynomials/foreign_field_add/witness.rs
kimchi/src/circuits/polynomials/foreign_field_mul/gadget.rs
kimchi/src/circuits/polynomials/foreign_field_mul/witness.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs
utils/src/foreign_field.rs

* Fail fast at circuit or witness creation time
* Since non-native modulus is public (coeff) parameter
we don't need constraints for this
* However, this is helpful for the circuit designer

Prevent user from accidentally specifying invalid non-native modulus

---

kimchi/src/circuits/argument.rs
kimchi/src/circuits/gate.rs
kimchi/src/circuits/polynomials/complete_add.rs
kimchi/src/circuits/polynomials/endomul_scalar.rs
kimchi/src/circuits/polynomials/endosclmul.rs
kimchi/src/circuits/polynomials/foreign_field_add/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/gadget.rs
kimchi/src/circuits/polynomials/generic.rs
kimchi/src/circuits/polynomials/poseidon.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/gadget.rs
kimchi/src/circuits/polynomials/rot.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/circuits/polynomials/varbasemul.rs
kimchi/src/circuits/polynomials/xor.rs
kimchi/src/linearization.rs
kimchi/src/prover.rs
tools/kimchi-visu/src/lib.rs

This is #1019, rebased onto master.

Use the same cache for all constraints, to avoid accidental aliasing

---

.gitignore
tools/kimchi-visu/README.md

It seems the SRS loading is strict in terms of path location (parent directory). Add a note if the user wants to run kimchi-visu from kimchi-visu directory.
It might be better to provide the path in a environment variable. Not in the scope of this PR.

Add note about SRS directory

---

kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/runtime_tables.rs
kimchi/src/tests/lookup.rs

Previously, we were considering two types of runtime table configurations, indexed and custom.
Indexed were supposed to represent "standard" array access, using indexed from 0 to N, which can be easily represented as a "custom" runtime table configurations whose first column is from 0 to N.
It also simplifies the wasm binding as enum with structure values can not be represented using wasm-bindgen.
Cherry-picked from https://github.com/o1-labs/proof-systems/pull/1070

Normalize the runtime table configuration to "custom"

---

Cargo.lock
internal-tracing/Cargo.toml
kimchi/Cargo.toml
poly-commitment/Cargo.toml
poseidon/Cargo.toml

ocaml-gen includes some fixes including bindings with more than 5 parameters, a bug related to array conversions and implement OCamlDesc for i32, required for https://github.com/o1-labs/proof-systems/pull/1112.

Bump up ocaml-gen to 0.1.5

---

book/src/specs/kimchi.md
kimchi/src/plonk_sponge.rs
kimchi/src/proof.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs

This PR builds upon #1110, adding evaluations for all of the 'non-optional' gates, which will allow them to be removed from the linearization (in an upcoming PR).
This PR replaces #1105 as part of a rebase to make reduce the scope of changes needed for berkeley.

Evaluate selectors for non-optional gates

---

kimchi/src/circuits/expr.rs
kimchi/src/linearization.rs

This PR builds upon #1105, removing the newly-evaluated selectors from the linearization.
This PR is separated for the purposes of the corresponding Mina PR, where it results in the update of a large generated file, along with some other pickles changes.

Remove evaluated columns from linearization

---

kimchi/src/prover.rs
kimchi/src/verifier_index.rs

This PR is a follow-on from #1106, adjusting the blinding factor of selector commitments for the remaining optional gates, so that a 'zero' commitment does not occur for an unused gate.

Use 'fixed hiding' for selector commitments

---

kimchi/src/linearization.rs

This PR builds upon #1111, using the evaluations that it adds in place of the linearization.

Stop linearizing optional gate selectors

---

.github/workflows/rust.yml

Addressing https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
There are always warnings when you go in the actions tab. This PR will fix these warnings. We should keep an eye on it.

Bump up actions/checkout to v3

---

kimchi/src/circuits/constraints.rs

iter() was applied on the option, not the list.
Fixes https://github.com/MinaProtocol/mina/issues/14072

Domain computation: runtime table cfg is given as option, not list

---

kimchi/src/circuits/lookup/index.rs
kimchi/src/circuits/lookup/tables/mod.rs

Using `self.data.len()` can be error-prone, and an index is easily introduced. It is also always better to abstract with an API using methods. In the future, I would recommend making the data field abstract.
Also, the length method is not fully correct. It supposes the user built the lookup table and know that all columns must have the same length. The first column, by construction, might have a different length.

Lookup tables: introduce width method to get the width

---

kimchi/src/circuits/lookup/lookups.rs

This is #1245 rebased to the `o1js` branch
Companion for https://github.com/o1-labs/o1js-bindings/pull/146

Add creation function for lookup structures used in Wasm

---

poseidon/Cargo.toml
poseidon/src/poseidon.rs
poseidon/src/sponge.rs

This PR removes the `debug_sponge` feature. This currently makes the test output extremely noisy, and the OCaml counterpart that would have made this useful was never implemented.

Remove noisy `debug_sponge`

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/domains.rs
kimchi/src/error.rs

This PR tweaks the errors returned around domain creation so that they have informative content.
This comes from the debugging for chunking, where the current messages are effectively useless.

Improve errors around domain creation

---

kimchi/src/circuits/constraints.rs

This PR fixes an error where we calculate `0` chunks (and then get an underflow, with predictably disastrous results).

Fixup edge-case around chunking in constraint system

---

Cargo.lock
optimism/Cargo.toml
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/mod.rs
optimism/src/mips/registers.rs
optimism/src/mips/witness.rs

This PR introduces the `witness::Env` used by the MIPS interpreter to generate the witness. The initial environment is generated from the cannon `State`.
The VM is then run by calling `step` on the env; currently this is stubbed as immediately halting.

Add initial `witness::Env` for MIPS VM

---

poly-commitment/src/srs.rs

This adds a method to create the SRS in parallel; generation of points is distributed over threads using rayon's `par_iter()`

Parallel SRS creation

---

kimchi/src/circuits/polynomials/rot.rs
kimchi/src/tests/rot.rs

This is to match the interface being created in o1js [in this PR](https://github.com/o1-labs/o1js/pull/1182).
This does not modify the constraints. This only affects the witness generation code for the Kimchi gadgets, which are only used for internal testing.
Now rotation by 0 and 64 bits are allowed. Nonetheless, it is not recommended since it adds 3 unneeded rows to the circuit, as it is trivial that the rotated word is just the same as the input.

Adds trivial support for rotation by 0 and 64 bits

---

kimchi/src/circuits/constraints.rs

This PR abstracts out the logic for inferring feature flags. This will allow us to call this logic from OCaml/JS, instead of having the user manually pass the flags alongside their circuit.

Add helpers for inferring feature flags

---

optimism/src/cannon.rs
optimism/src/mips/witness.rs

This was improperly deserialized as `String`, while we know it's a 256 bits key. Hence a `[u8; 32]` is more appropriate.

Fix serialization of preimage key

---

kimchi/src/circuits/constraints.rs
kimchi/src/circuits/lookup/tables/mod.rs

This PR fixes a bug in the domain size computed for lookup tables. This allows us to prove with a smaller domain size when ffmul and some other range check lookup gate is used, and also to revert the workaround [here](https://github.com/MinaProtocol/mina/pull/14405/commits/c2d9b3b844630ddb3d604ec8b9ea76edd5360ab5).

Deduplicate lookup tables

---

optimism/src/preimage_oracle.rs

This PR builds upon #1338. This does several things:
* splits the reading and writing ends of pipes between the client (VM interpreter) and server processes
* keeps around references to all of the pipes, so that they don't get `drop`-ed and cause a reference to a freed file descriptor
* passes the correct ends of pipes to the processes, so that the corresponding read/write calls don't immediately fail.
This was tested by sending a dummy hint to the server process and logging a message to show it being received. Also, this now does not immediately crash.

Add cross-process pipes, ensure that they aren't free'd

---

kimchi/README.md
kimchi/benches/proof_criterion.rs
kimchi/src/bench.rs
kimchi/src/precomputed_srs.rs

Trying to run the criterion benchmarks for kimchi, I ran into a couple of minor issues (documentation, a macOS dependent thing, and duplicated names for different benchmarks which prevented criterion from running).
With these changes, I am able to run the criterion benchmarks for kimchi.
There's also a minor refactoring to remove some code duplication.

Update criterion benchmarks for kimchi

---

optimism/src/mips/interpreter.rs

This PR fixes the abstraction leak. `Variable` isn't `u32`, this PR unwinds the code that pretends that it always is.

Fixup environment trait to avoid abstraction leaks

---

optimism/src/mips/column.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/mod.rs
optimism/src/mips/witness.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/1380, adding the `alloc_scratch` helper to the environment trait. This will be the basis of all intermediate storage for the gate constraints.
In order to do this, this PR adds
* a `Column` type (currently missing: `InstructionCounter`, since it's unused here)
* a `Position` type to the trait
* `alloc_scratch` to allocate a new position in the scratch state
* a `write_column` helper in the witness environment, to allow for writing to the scratch state (currently unused).

Add support for scratch_state to MIPS VM

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR uses the scratch state implemented in https://github.com/o1-labs/proof-systems/pull/1381 to pull values into the local witness from memory.
The access function is marked `unsafe`, following the rust guidelines: users of the function should be careful to add the constraints manually, because it will not do it for them. We are not currently being this careful.

Use scratch allocations when fetching memory

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/1382, adding counterpart operations for
* writing to memory
* reading the 'access index' for a memory address
* writing the 'access index' for a memory address.
These primitives are essential for the correct operation of RAMLookup, ensuring that reads are 'temporal' (i.e. you can't read a value in the past that you wrote in the future).

Add other accessors necessary for zkVM memory

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/1384. This adds the minimal interface for adding lookups from within the interpreter, by exposing `add_lookup` from the interpreter environment.

Add (stubbed) lookups to InterpreterEnv

---

optimism/src/mips/interpreter.rs

This PR adds helpers for safely reading and writing memory. This PR builds upon https://github.com/o1-labs/proof-systems/pull/1385 and its ancestors, emitting lookups for the RAMLookup read/write operations.
This PR also adds a stub `range_check64` helper; this is easy to fill in later, and orthogonal to the main body of the PR.

Add safe helpers for reading and writing memory

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR mirrors https://github.com/o1-labs/proof-systems/pull/1386, but for registers instead of RAM.
This current implementation comes with some caveats:
* a register may be accessed multiple times in the course of an operation, and so we need to handle the accesses more deliberately than with memory. This is not included in this PR.
* the zero register is handled incorrectly. Writing to it will change the value of the register.
- This requires the `numerator` in the register to be a variable, which is out of scope for this PR.

Add safe helpers for reading and writing registers in the zkVM

---

optimism/src/mips/interpreter.rs

This PR builds on https://github.com/o1-labs/proof-systems/pull/1387, refactoring the code so that the explicit mentions of `InstructionParts` are contained to the top of the interpreter functions, in preparation for their removal.

Prepare for removal of `InstructionParts`

---

optimism/src/mips/witness.rs

This PR adds a fix for the e2e test after https://github.com/o1-labs/proof-systems/pull/1389. This resets the 'scratch state' before running an instruction, isolating the witnesses for each instruction from those before and after.

Reset the scratch state before executing an instruction

---

optimism/src/main.rs
optimism/src/mips/witness.rs

Currently, we spend about 1/3 of each instruction cloning the same strings from the same `VmConfiguration` structure. This PR fixes that, passing a reference, and thus speeding up the interpreter by ~50%.

zkVM: Spend *way* less time cloning on every step

---

optimism/src/mips/interpreter.rs
optimism/src/mips/registers.rs
optimism/src/mips/witness.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/1404, moving the instruction pointers into the registers so that instructions may be executed out of sequence.

Store instruction pointers in registers

---

optimism/src/mips/interpreter.rs

This PR builds on https://github.com/o1-labs/proof-systems/pull/1405. This adds a `Signed` type (and a `Sign` enum to support it), so that the numerator of a register write can be invalidated by passing a zeroed variable to it.

Add a sign to lookup numerators

---

optimism/run-op-program.sh
optimism/run-vm.sh

This PR adds the ability to pass `INFO_AT` and `STOP_AT` to the scripts for running cannon and the zkVM. This makes it significantly easier to debug / bisect for inconsistencies.

Add helpers for setting INFO_AT and STOP_AT in the runner script

---

optimism/src/mips/interpreter.rs

This PR updates the definition of the `SyscallOther` instruction, using the newly-defined constants in place of the literals.

Use the defined constants for syscall selection

---

optimism/src/mips/interpreter.rs

This PR fixes an oversight where we were not updating the last access time for registers and memory.

Update the access times when accessing registers and memory

---

optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR
* adds an `add_constraint` helper
* adds assertions `assert_is_zero`, `assert_equal`, and `assert_boolean`
* adds `is_zero` and `equal` helper functions
* replaces existing unsafe uses of `test_zero` with `is_zero` or `equal`.

Add constraints, use them for `test_zero` and friends

---

optimism/src/mips/interpreter.rs

This PR removes the list of register names from the VM.
The names clutter the interpreter file, and the semantic meanings are meant for users of MIPS (i.e. they provide a standard for how variables should be used so that functions etc. compose cleanly), but they only serve as a distraction/confusion for the VM implementation itself.

Remove register names

---

kimchi/src/tests/lookup.rs

Regression test for https://github.com/o1-labs/proof-systems/blob/master/kimchi/src/circuits/lookup/tables/mod.rs#L85

[develop] Lookup: a table with ID 0 *must* contain a row with 0 only

---

optimism/src/mips/interpreter.rs
optimism/src/mips/registers.rs
optimism/src/mips/witness.rs

This PR implements the Mmap syscall. In order to do this, it
* adds support for optionally writing to registers,
* moves the heap pointer into the registers,
* adds a heap pointer increase function,
* implements the mmap syscall.

Implement mmap syscall

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/lib.rs
optimism/src/mips/witness.rs

This PR adds a `KeccakEnv` struct and `KeccakEnvironment` trait that can be used to easily access parts of the Keccak computation for the witness creation code and gate constraints generation. It builds upon KeccakCols introduced in the [previous PR](https://github.com/o1-labs/proof-systems/pull/1444)

Keccak environment

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs

This PR adds a few basic boolean operations for the Keccak environment (that will be used inside constraints). It updates the `KeccakEnvironment` trait to use them in flags.

Boolean trait for the Keccak environment

---

kimchi/src/circuits/polynomials/keccak/mod.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs

This PR adds a few basic arithmetic operations for the Keccak environment (that will be used inside constraints). It updates the KeccakEnvironment trait to use them in functions to create expressions from quarters of words and of shifts of words.

Arithmetic operations for Keccak environment

---

optimism/src/cannon.rs
optimism/src/mips/witness.rs

Allow to define a range in a `rust`-like manner `lo..[hi]`, that is from `lo` until `hi` (excluded) if specified, or until the end if not.

Extension to frequency specification

---

optimism/src/cannon.rs

It will make more sense to call the serializer "serialize_preimage_key"

zkVM: rename to_preimage_key into deserialize_preimage_key

---

optimism/src/mips/witness.rs

This PR aims to help us debug when the zkVM halts unexpectedly, by printing the offending instruction and step number so that we can reproduce it.

Print the current instruction and step on halt

---

optimism/src/cannon.rs
optimism/src/mips/witness.rs

Aims to fix
```
thread 'main' panicked at 'to have a preimage if we're requesting it at a non-zero offset'
```
when we use a snapshot with a non-zero preimage offset.

Save preimage in Env/State, and add it in the snapshot

---

optimism/run-vm.sh
optimism/src/cannon_cli.rs

There's a typo in our command line wrt cannon's: It's `pprof.cpu` not `pprof-cpu`

Cli: `pprof.cpu` 

---

kimchi/src/circuits/polynomials/keccak/circuitgates.rs
kimchi/src/circuits/polynomials/keccak/witness.rs
kimchi/src/tests/keccak.rs

This contains the changes from https://github.com/o1-labs/proof-systems/pull/1301, ignoring the changes to the proof system. 
It gets rid of redundancy in the Keccak layout to reduce the number of columns by ~400. 
- Remove intermediate states and embed them in constraints
- Simplify rotation inside Theta removing bound_c and lookups for quotient_c (which just needs a boolean check)
- Remove bound_e following the discussion about optimizing rotation with the product team
- 64 Less constraints in squeeze, only for the 256-bits of the output instead of the whole state.
The main reason for getting these changes in, is to be able to avoid code duplication between the kimchi crate and the mips crate (mainly regarding witness creation).

Single row Keccak optimizations (without proof-systems modifications)

---

kimchi/src/circuits/polynomials/keccak/witness.rs

This PR makes some structs accessible from other crates to avoid code duplication for the Keccak integration of MIPS.

[easy] Making some Keccak structs publicly accessible for MIPS

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs

This PR reduces the amount of Keccak columns because `IotaStateG` and `SpongeXorState` was referring to the same category of `NextState`. It also fixes a flaky definition of `SpongeNewState` which used redundant columns for `SpongeZeros` (which can be accessed with a helper instead).

[easy] Reduce redundant Keccak columns

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/mips/column.rs
optimism/src/mips/witness.rs

This way helps with separation of concerns between mips and keccak.

[easy] Move write_column for Keccak to its own environment

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs

This is a preliminary trigger for the Keccak interpreter, on input the preimage data. More PRs are coming. In particular, take into account that this still does not implement the communication channel, so the preimage is passed as input instead of being read from memory.

[easy] Implement `hash` function inside `KeccakInterpreter`

---

optimism/src/keccak/witness.rs

This function is meant to be the step that repeats over and over again in the execution of the Keccak circuit.

[easy] Implement step of Keccak interpreter

---

optimism/src/keccak/witness.rs

These flags will be used in the constraints to "select" the right constraints for each mode of operation, depending on the type of step being executed.

[easy] Set mode flags in the interpreter

---

optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs

Includes `run_sponge`, `run_squeeze` and `run_absorb`.

Implement sponge execution inside Keccak interpreter

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/witness.rs

This reuses the witness code in Kimchi. It adds some methods to obtain the fields of the Theta struct.

Witness creation for Theta permutation in the interpreter

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/witness.rs

This reuses the witness code in Kimchi. It adds some methods to obtain the fields of the PiRho struct.

Witness creation for PiRho permutation in the interpreter

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/witness.rs

This reuses the witness code in Kimchi. It adds some methods to obtain the fields of the Chi struct.

Witness creation for Chi permutation in the interpreter

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/witness.rs

This reuses the witness code in Kimchi. It adds some methods to obtain the fields of the Iota struct.

Witness creation for Iota permutation in the interpreter

---

optimism/src/keccak/constraints.rs

These constraints were not in the Kimchi gate because flags were publicly accessible as gate coefficients encoding the mode of operation.

Constraints for flags configuration

---

optimism/src/keccak/constraints.rs

The difference between these and the ones found in the Kimchi gate are the additional degree resulting from multiplying by the selector flag in each constraint, and removing the constraints related to the padding because this will be handled differently in the MIPS project.

Constraints for the Keccak sponge

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs

This is the first of a series of PRs meant to add support for padding in the MIPS Keccak module. 
This PR adds a few columns needed to select bytes involved in the padding, access the value $2^{len}$, and the claimed correct padding for a given length. 
It also provides some helpers in the environment to access these columns, and combinations of them that will be used inside the constraints.

Add columns and environment helpers for padding

---

Cargo.lock
optimism/Cargo.toml
optimism/src/mips/constraints.rs
optimism/src/preimage_oracle.rs

This PR fixes the halt caused by deadlocks between the zkVM and the preimage oracle, by setting the `DIRECT` flag in the pipes that we pass to the oracle process. There isn't a nice API for this, so there's some low-level detail here, but the zkVM now runs end-to-end unsupervised!
Massive thanks to @jspada talking over the problem and proposing the solution :heart:

Fix zkVM IPC deadlock

---

kimchi/src/circuits/polynomials/keccak/constants.rs

This small PR just fixes some offsets that are not aligned with the future layout of the MIPS columns meant to reduce the number of effective columns by 800.

[easy] Fix offsets of Keccak constants

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs

And some slight clean-up of the files where these are being used.

[easy] Rename confusing names of functions to precede with `is_`

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/witness.rs

Even if this PR seems to increase the number of total columns by 100, a coming PR will eventually reduce it by 800. This is just a preliminary step so the diff is smaller.
It also fixes a notation deviation between `new_block` (which referred in Kimchi to just 1088 bits) and `new_state` (which refers to all 1600 bits).

[easy] Split `NextState` column across 2 variants for readability

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/witness.rs

This PR includes a missing update that was not being performed inside the interpreter when running rounds. In particular, the output `state_g` was not being stored inside `self.prev_block`, so subsequent rounds could be loading old states instead.
For the rest (sponges), I have checked that the `prev_block` was being updated accordingly, this seems to be the only place where this was missing.
I realized about this issue when going through Misha's related comment in [this PR](https://github.com/o1-labs/proof-systems/pull/1637), asking about constraints between consecutive steps.

Fix: `prev_block` was not being updated with value of `state_g` in-between rounds

---

optimism/src/keccak/lookups.rs

This is to make the coming structure of the columns more readable.
This PR is a no-op. It just moves code blocks around and gets rid of some indentations.

[easy] Clean-up of Keccak lookups (no-op)

---

optimism/src/keccak/column.rs
optimism/src/keccak/mod.rs

This PR adds two more elements inside the `KeccakColumns` struct in order to keep track of the columns located in the `Curr` and `Next` rows of the Kimchi implementation. The goal of this addition is to be able to remove 800 columns eventually by providing an unified "storage", but allowing for a fine-grained access to each `KeccakColumn` variant.
This PR is meant to make the diff look smaller. Coming PR will actually remove those redundant columns.

[easy] Add `curr` and `next` row vectors inside `KeccakColumns`

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs

The reason for this PR is that when columns get reduced by ~800, there won't be any more vectors inside `KeccakColumns` for individual states, and we need some helpers to access them.

[easy] Create functions to access columns as slices

---

optimism/src/keccak/constraints.rs

No-op, just clean-up before those fields are removed in a coming PR.

[easy] Use function calls instead of direct struct field access inside constraints

---

optimism/src/keccak/lookups.rs
optimism/src/mips/interpreter.rs

This PR adds an enum `LookupMode` whose variants are `Read` and `Write`, which act as wrappers for the positive and negative signs of the numerator of RAMLookups. Together with a flag selector argument which acts as the magnitude of elements added to the tables, these changes will facilitate the creation of lookups inside the Keccak workflow. In particular:
- thanks to the mode, witness and constraints will be able to reuse the same `lookups()` function to either "create" or "consume" the values in the table; and,
- thanks to the flag, lookups will be easily "switched on/off" depending on whether the Keccak step is a sponge or a round, without conflicts due to the reused vector positions to save 800 columns.

[easy] Read/Write modes for Signed numerators in Lookups

---

.github/workflows/rust.yml
book/Cargo.toml

The maintainer of the `time` crate is a known bad-actor for bumping `rust-version` in a way that will automatically break CI pipelines.
See https://github.com/time-rs/time/issues/575 and the discussion linked from there for more.

[berkeley] Fix CI, and stop `time` crate from periodically breaking CI

---

optimism/src/keccak/lookups.rs
optimism/src/mips/interpreter.rs

This PR is the third one trying to simplify the `Lookup` trait for `KeccakEnv` by adding a helper to easily create lookups to the `Byte` lookup table. Not only does it clean up the interface, but it also allows for switch on/off functionality thanks to the flag argument of `Signed`.

[easy] Helper for `Byte` lookup table

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs
optimism/src/mips/interpreter.rs

This PR uses memory-styled lookups to constrain information in-between consecutive Keccak steps. Meaning, that the output of the i-th step is the input of the (i+1)-th step. Although steps consecution was already handled within a `KeccakEnv` instance and the input/output witness was code was done, it was not constrained anywhere else. This PR fixes that.
In the code there's 2 TODO's accounting for the final output of the hash and the inputs for it. This should be done in a similar fashion to encode the communication channel between the syscalls and keccak.
Closes https://github.com/o1-labs/proof-systems/pull/1676

Constrain input and output between consecutive Keccak steps

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs

It will be used for an alternative definition of `is_round()` for Keccak, but could be used elsewhere.

[easy] Helper to check if a witness is nonzero using inverses

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/witness.rs
optimism/src/mips/witness.rs

This PR executes the hash of the `KeccakInterpreter` inside `request_preimage_write()`, which is called from the `interpret_rtype()` function, when the instruction is a `SyscallReadPreimage`. 
The idea here is to add a counter of the number of bytes of the preimage read so far inside the MIPS `Env`. When this value reaches the total length of the preimage, it's time to call the hash inside the interpreter of Keccak. This creates a new `KeccakEnv`, which triggers the witness creation code.
Some things remain to be done:
- Lookups between MIPS and Keccak (hash [here](https://github.com/o1-labs/proof-systems/pull/1687) and preimage [here](https://github.com/o1-labs/proof-systems/pull/1688))
> How and where to trigger Keccak constraints?
> - TBD when constraints of MIPS are also integrated …

Trigger hash of `KeccakInterpreter` from Syscall

---

optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR adds lookups on the Keccak side and the MIPS side to communicate that the preimage key corresponds to the claimed hash. 
Here, because only 31 bytes are needed (the MSB of the hash is dropped to store the identifier 0x02 in most cases), these 248 bits can be stored as a single field element in the table. A leading value encoding the hash index is included.
A similar approach shall be followed for the preimage data, except that here they will be stored as bytes (https://github.com/o1-labs/proof-systems/pull/1688).

Communication channel of preimage key

---

kimchi/src/circuits/polynomials/keccak/circuitgates.rs
optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs
optimism/src/mips/witness.rs

This PR adds lookups on the Keccak side and the MIPS side to communicate that the preimage data used.
We could have optimizations later (like blocks of bytes as used inside padding), but for now each byte is passed to the channel as a two-column value `[hash idx, byte idx, byte value]`.

Communication channel of preimage bytes

---

optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/witness.rs
optimism/src/main.rs
optimism/src/mips/witness.rs

This PR partially addresses issue https://github.com/o1-labs/proof-systems/issues/1695. 
Before this PR, the syscalls used to run the hash for the whole preimage in one go. But this approach overwrites individual Keccak steps witness data after every step update. Conversely, this PR solves that problem essentially thanks to moving parts of existing code around, so that the loop inside the old `hash()` function is executed as a sub-loop inside the halting condition loop inside `main.rs`. That way, a subsequent PR will be able to propagate the witness of each individual step, populating the folded instance for Keccak. In addition, now the function `request_preimage_write()` will only create an "empty" but non-`None` instance of `KeccakEnv` using as input the hash index and the preimage …

Split hash function into individual steps inside the main loop

---

optimism/src/keccak/column.rs

This is to replicate the behavior of `WitnessColumns` of MIPS for `KeccakColumns`, so the code containing the proof is closer to that of MIPS and it is easier to review.

Make contents of `KeccakColumns` arrays instead of vectors

---

CONTRIBUTING.md

This introduces a paragraph that mirrors branching policy for `mina` introduced here: https://github.com/MinaProtocol/mina/pull/14684

Add branching policy

---

optimism/src/keccak/column.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/proof.rs

This PR implements the Default trait for the struct `KeccakProofInputs` in a similar way as `ProofInputs` inside the mips module.

[easy] Implement default for `KeccakProofInputs`

---

optimism/src/keccak/proof.rs

This PR creates the struct `KeccakProof`, replicating the struct `Proof` inside the mips module. 
Disclaimer: we can probably avoid code duplication by making the contents of `mips/proof.rs` more generic. But for now, let's create an independent one inside the keccak module, make sure it works, and refactor later. Created issue to track it https://github.com/o1-labs/proof-systems/issues/1705.

[easy] Create `KeccakProof` struct

---

kimchi/src/circuits/polynomials/keccak/witness.rs
optimism/src/keccak/witness.rs

As Matthew said, characters are free.

[easy] Avoid use of `rc` and use `round_constants` instead

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/witness.rs

This is just a refactor, but the diff is long because it propagates into many parts of the code.
This PR makes the variants inside the `KeccakColumn` enum single-indexable, as opposed to 1,2,3,4 indices as they used to have. This is to facilitate the creation of chunks of variables when I fully address https://github.com/o1-labs/proof-systems/issues/1723.
This does not affect the usability of the interface, because the functions of `KeccakEnvironment` still can be indexed with the desired number of indices, which is more convenient for constraints and witness loops.

[easy] Make `KeccakColumn` variants single-indexed

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs

Closes https://github.com/o1-labs/proof-systems/issues/1723
This adds the `variable` function in order to create variables from a given `KeccakColumn`. 
Similarly, it fixes the function `write_column` so that it gives a field value to witness columns instead of expressions.
It adapts the trait `KeccakEnvironment` accordingly to deal with the change that `KeccakColumns<E<Fp>>` is now `KeccakColumns<Fp>` instead.
The diff looks very large because all functions needed to be changed in order to compile. Otherwise I would have created smaller PRs. The changes are quite straightforward, but please take a look in case I could have missed any naming in the refactor, or more importantly, if you think variables should be created differently.

Make Keccak witness `Fp` instead of expressions

---

optimism/src/keccak/witness.rs

I often need to go on the website to find it, and I always spent some minutes finding the link.
Better to have it at the top of the file IMO.

Keccak/doc: adding link to "official" pseudo-code

---

.github/workflows/gh-page.yml
internal-tracing/src/lib.rs
kimchi/snarky-deriver/src/lib.rs
kimchi/src/circuits/polynomials/keccak/mod.rs
kimchi/src/snarky/cvar.rs
kimchi/src/snarky/runner.rs
kimchi/src/snarky/snarky_type.rs
kimchi/src/snarky/union_find.rs

This PR makes the CI stops ignoring the warnings while building the doc. It also includes multiple fixes, mostly the ones introduced by the recent integration of `snarky`.

Stop ignoring doc warnings

---

.github/workflows/gh-page.yml

We use `-Zunstable-options` in the command, therefore we need to enforce nightly

Update nightly version used + force to use nightly

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/proof.rs
optimism/src/keccak/witness.rs
optimism/src/main.rs

This PR reduces lines of code. 
It is part of https://github.com/o1-labs/proof-systems/issues/1709, as I am planning to aggregate them further when it comes to sponge-only columns, so they can take the space we already have between columns 800 and 1965 (so we don't always pay 200 extra columns for no reason).

Aggregate mode flags of `KeccakColumns` into an array

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/proof.rs
optimism/src/main.rs

Closes https://github.com/o1-labs/proof-systems/issues/1709.
This PR leverages the fact that plenty of columns are only accessed during sponge rows, which only use 800 of the 1965 available `curr` columns. Storing those coefficients in `curr` saves us 145 columns (meaning additional field elements in the witness) whose consumed space is redundant otherwise.
As a side effect, this reduces the lines of code needed in the proof of Keccak.

Reduce Keccak columns by 145

---

kimchi/src/circuits/polynomials/keccak/constants.rs

The goal of this small PR is to fill the content of the HTML page generated by
```
RUSTDOCFLAGS="--enable-index-page -Zunstable-options -D warnings" cargo +nightly doc --workspace --all-features --no-deps
```
that we can find published [here](https://o1-labs.github.io/proof-systems/rustdoc/kimchi/circuits/polynomials/keccak/constants/index.html).

Keccak doc: adding some comments in the constants file

---

.github/workflows/gh-page.yml
.github/workflows/rust.yml
poly-commitment/src/commitment.rs
poseidon/src/sponge.rs

Recent changes to GH page deployment made doc warnings critical, but this was not caught in CI. This PR adds the missing CI warning and fixes some newly introduced doc warnings.

Fix CI: Make cargo doc warnings critical

---

optimism/src/keccak/column.rs
optimism/src/keccak/lookups.rs

While updating the [Keccak RFC](https://github.com/o1-labs/rfcs/pull/27/commits/5845e645508e3c847b3df4ecd5dee1385cebb7bb) with the novel changes regarding the layout, I realized that the lookups being performed for the iota algorithm were not correct. In particular, the code was previously adding 4 lookups, one for each quarter of a round constant; whereas it really only needs 1 lookup containing all 4 quarters so that the order matches the actual values. Otherwise, there is no way to tell apart what is the ordering of the quarters and a malicious prover could be using an alternative round constant without being noticed.
I used the same branch to update a few outdated comments, matching the new RFC.

Fix iota lookups

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/proof.rs
optimism/src/main.rs

This PR adds some more comments to the `keccak/column.rs` module. 
As part of the documentation and spec process, this PR also introduced a renaming from `KeccakColumns` to `KeccakWitness` for better clarity: now `KeccakColumn` refers to the aliases, used to identify variables, whereas `KeccakWitness` contains the actual field elements composing the witness of the circuit.

[easy] Add docs for `keccak/column.rs`

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs

This PR improves the documentation of the `keccak/constraints.rs` module. In particular, it includes the constraint count for better traceability, including their degree.
Only 5 constraints have degree 3, so we shall expect that after quadricization is applied, we will need just a few more witness columns and constraints to make them degree 2.
Alternatively, we can intentionally shift the beginning of the sponge columns (since they have about 1k less used columns than the round), so that the `quotient_c` values are located in witness columns which would be set to zero regardless in sponge steps. That way, we could rephrase the constraint to be instead of `is_round * is_boolean (quotient_c)` to just `is_boolean(quotient_c)`. Opening issue to trace this optimization -> …

Add constraint count and degree in docs

---

optimism/src/keccak/column.rs
optimism/src/keccak/environment.rs

This PR adds documentation comments inside the `keccak/environment.rs` file. 
As part of the documenting process, I realized that the `from_shifts` function was not behaving as expected. In the sense that it was giving support for shifts of length 100, which do not exist. Instead, I changed the match branch to be 80, which will fix it.
It also addresses this comment by Danny https://github.com/o1-labs/proof-systems/pull/1749#discussion_r1464876470

[easy but long] Improve documentation of environment and fix `from_shifts` function

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs

While adding doc comments to the `keccak/interpreter.rs` file, I realized that the `PadSuffix` columns of the witness were being assigned in every absorb sponge, even when they are only used in padding absorbs. This is not really a bug, given that constraints and lookups would still hold. But I thought it made more sense to do it only in padding rows.

Add docs to interpreter and change location where `PadSuffix` columns were assigned

---

book/src/kimchi/final_check.md
book/src/kimchi/maller_15.md
book/src/pickles/accumulation.md

This PR primarily (commit #1) fixes the notation regarding `(v,u)` -- the polynomial combiner and the evaluation combiner. The code used them consistently with the plonk paper (`v` is `polyscale` and `u` is `evalscale`), however in the book they were swapped. This PR makes them all consistent across our code and documentation by fixing the book mistake.
The other two commits are purely cosmetic -- they fix some absent parentheses, add some `\cdot` for readability, and align long equations so they more clearly separate the terms in big sums/products.

Book: Fix Kimchi syntax regarding u/v + cosmetics

---

kimchi/src/precomputed_srs.rs

While updating to arkworks 0.4.x, I realised the default encoding changed. Adding this as a regression test.
See https://github.com/o1-labs/proof-systems/pull/1747/commits/d680bb4a449bc53a4451cc5a42ff5f5b19ac5ce5

SRS: regression tests for Pallas and Vesta

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs
optimism/src/lib.rs
optimism/src/lookup.rs
optimism/src/mips/constraints.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/mod.rs
optimism/src/mips/witness.rs

This PR is mainly a code reorganization of lookup-related code that was already present in other parts of the zkvm code, and aggregate it into one lookup module instead.
Apart from that, it lays the foundations to start keeping track of lookups on the mips side as well (they were only being saved in keccak so far). ~This will be subject to changes, as we decide when and how these lookups should be added -> should this happen in the interpreter/witness side or constraints? Also, there's the question of whether lookups should be a Vec<Lookup<E<Fp>>> (meaning of variables), or directly Vec<Lookup<Fp>>.~
~As a reference for the upcoming PRs, I will be using this draft PR as a baseline, as it contained some code for lookups that was removed from the current demo -> …

Preliminary work for zkVM lookups

---

optimism/src/keccak/lookups.rs
optimism/src/keccak/witness.rs
optimism/src/mips/witness.rs

After a meeting with Matthew, he explained that the lookups should only be added from the constraints side of the interpreters, and not from the witness side.
This was the case for normal read-only lookups. But for read-write (communication channel) lookups, these were happening from the witness interpreter code, both on the Keccak and MIPS sides.
This PR easily fixes the rw lookups on the Keccak side, making use of the `write_if` and `read_if` interfaces, substituting the old `write_one` and `read_one`. That way, these will only be nonzero when the condition holds (for preimage, at every absorb; for hash, at squeeze steps). Similar with inter-step lookups.
Nonetheless, moving the MIPS side of the read/write lookups for the syscalls channel is still not addressed in this PR. I am still …

Fix location where channel lookups are executed

---

.github/workflows/rust.yml

0.39.0 has been released during the night CET. It makes the CI unhappy.

Use 0.38.0 instead of the latest release 0.39.0

---

curves/Cargo.toml
curves/src/pasta/curves/tests.rs

After some time of investigation about a failing test for https://github.com/o1-labs/proof-systems/pull/1747, I noticed that an addition using the inplace operator `+` on Pallas was giving a different output.
I introduce this regression test to be confident regarding the changes in https://github.com/o1-labs/proof-systems/pull/1747.

Tests: add regression tests for addition and biguint conversion

---

kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs

It is important to ensure we use the affine coordinates. The addition might not always be returning a point in the affine coordinates, and therefore accessing the individual curve coordinates might lead to undefined behavior, potentially critical bugs.
Actually, it is the case between arkworks 0.3.0 and arkworks 0.4.x.

Tests: ensure we use the affine coordinates

---

Cargo.lock
Cargo.toml
msm/Cargo.toml
msm/src/columns.rs
msm/src/lib.rs
msm/src/main.rs
msm/src/proof.rs
msm/src/prover.rs
msm/src/verifier.rs

This commit sets the basic structure for the Kimchi MSM circuit which aims to be a circuit allowing to prove a large MSM with group elements formed from a foreign field.
It defines a generic prover and verifier over a indexed number of columns called X_i, and using KZG over the curve BN254.
In following PRs, the prover and verifier will use iterators to absorb commitments and evaluate points.
Also, MVLookup will be integrated.
Run `cargo run --bin main --release` to verify the verifier accepts a random proof.

Starting Kimchi MSM circuit

---

msm/src/main.rs
msm/src/proof.rs
msm/src/verifier.rs

It makes the code more generic, and DOMAIN_SIZE is only used once to instantiate a domain variable. The domain variable is used everywhere else.

Kimchi MSM: use domain variable instead of crate var DOMAIN_SIZE

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/lookup.rs

I realized there was a notation incoherence between the `if` conditionals inside the Lookup trait (when `if_is_true` is 1, it is supposed to insert the lookup, nothing otherwise), and the `is_` conditionals in constraints, where sometimes a `0` was being seen as a `true`, given that this is what makes the constraints satisfiable. 
I unified the notation in this PR, and clarified what is the meaning of each variable in the doc comments.

Fix conditionals used in constraints and lookups of Keccak

---

msm/src/columns.rs
msm/src/constraint.rs
msm/src/lib.rs
msm/src/main.rs
msm/src/precomputed_srs.rs
poly-commitment/src/pairing_proof.rs

Review by commit. 
Contains some basic stuff (constants, circuits, generating simple expression/witness) that was written 1.5 weeks ago, but somewhat adjusted to the new datatypes now in `master`. E.g. I generalized a few things/added some traits as we discussed we want this project to be slightly more generic.
The main intention of the PR is to discard the `dw-mv/large-msm` branch which contained some useful stuff (hopefully all/mostly ported now), but is otherwise unsynchronized with `master`.
*Not an intention*: to make any actual final decisions on traits/structs and architecture in general.

MSM: Merge existing feature work on SRS and constraints

---

kimchi/src/verifier.rs

commitments.lookup is an option. By using iter followed by for_each, the reader might suppose it is a list.
IMO, it seems more readable to check if lookups are used, unwrap the lookup commitments, without verifying if an error is raised as it should never happened, and get the commitment to the lookup aggregator.

Kimchi/verifier: stop relying on iterator on option

---

msm/README.md
msm/src/constraint.rs
msm/src/lib.rs
msm/src/mvlookup.rs
msm/src/proof.rs
msm/src/prover.rs
msm/src/verifier.rs

Current bug (expected): does not handle multiplicity different than one. Coming in a following PR with a test.
Also support only one table. Change coming in another PR, it is straightforward to generalize.
Fix https://github.com/MinaProtocol/mina/issues/15089
It is not sound, yet. Missing constraints.
TODO:

Generic MVLookup - MSM

---

optimism/src/mips/column.rs
optimism/src/mips/constraints.rs
optimism/src/mips/witness.rs

Closes https://github.com/o1-labs/proof-systems/issues/1813
The idea is to add a flag to determine if the syscall is reading preimage data or the bytelength. The lookups are only created if the bytes read correspond to the actual preimage bytes.

Prevent MIPS from writing bytes corresponding to preimage bytelength

---

optimism/src/lookup.rs
optimism/src/mips/witness.rs

I missed committing this change inside the commit fe1c5473cc420dccd3615614748e8670cbf39d06 of https://github.com/o1-labs/proof-systems/pull/1826
Basically without this, the behavior is the opposite -> sets to 1 when it is reading the bytelength, and to 0 when it reads the actual bytes of the preimage.

[easy] Fix typo in PR 1826

---

kimchi/src/prover.rs
kimchi/src/tests/recursion.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs
poly-commitment/src/chunked.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs
poly-commitment/src/lib.rs
poly-commitment/src/pairing_proof.rs
poly-commitment/src/srs.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs

This removes the unused and obsolete functionality of shifted polynomial commitments from the `poly-commitments` crate, and from its usages in `kimchi`. 
- Resolves https://github.com/MinaProtocol/mina/issues/14628
- `mina` PR counterpart: https://github.com/MinaProtocol/mina/pull/15071
Probably better to review commit-by-commit.

Remove commitment shifting functionality

---

msm/src/lib.rs

We do use 15 bits long limbs, and therefore we have 17 limbs

Change limbs size

---

kimchi/src/folding/mod.rs
optimism/src/keccak/column.rs
optimism/src/mips/column.rs

Here all columns are witnesses. Perhaps when circuits are split into multiple instances, some of them might be non-witnesses, but that would come later.

Implement FoldingColumnTrait for MIPS and Keccak

---

msm/src/prover.rs

The env for the quotient polynomials need the evaluations. Coming in a following PR.

Keeping evaluations in a variable to build the environment

---

msm/src/lib.rs
msm/src/main.rs
msm/src/prover.rs

It makes the tests reproducible

Pass a rng instance in prover

---

msm/src/proof.rs

It is used later to build witness in the subdirectory serialization

Make witness fields public

---

msm/src/serialization/interpreter.rs
msm/src/serialization/witness.rs

Interpreter: add bitmask to extract bits from foreign field limbs

---

msm/Cargo.toml
msm/src/lib.rs
msm/src/serialization/main.rs
msm/src/witness.rs

This PR introduces the main binary for the serialization. This can be moved later in a test if we notice we don't need a binary.
The prover and verifier will be run once the constraints are added and https://github.com/o1-labs/proof-systems/pull/1839 is done and merged.
The witness file has been picked from the zkVM. As said offline, we will move to this structure later.
There is still a change to make the prover/verifier generic. Atm, cols[i] must be extended after each execution of the interpreter. It will be made generic soon.

Serialization/MSM: create the main file

---

msm/src/constraint.rs
msm/src/lib.rs
msm/src/main.rs
msm/src/serialization/main.rs

Fix https://github.com/o1-labs/proof-systems/issues/1881

MSM: rename var for number of cols

---

Cargo.lock
Cargo.toml
msm/src/lib.rs
msm/src/mvlookup.rs
optimism/Cargo.toml
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/lookups.rs
optimism/src/lib.rs
optimism/src/lookups.rs
optimism/src/mips/constraints.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs
optimism/src/ramlookup.rs

This PR includes some initial interfaces to deal with RAMLookups, built on top of the MVLookups from the kimchi-msm crate. It provides a converter from RAMLookups into MVLookups, with the idea of being able to reuse the argument being built for MSM. Nonetheless, if we realize that the protocol is not general enough, further PRs will build on top of these changes to adapt the existing argument and make it more flexible.

RAMLookups initial interfaces

---

msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/witness.rs

Instead of Field.
It makes more sense as it is supposed to be values of a circuit

MSM/Serialization: InterpreterEnv param by PrimeField

---

msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/witness.rs

Asserting for now on the witness side.
The multiplicities are computing while we are computing the witness. In the next PRs, we will build the lookup witness from it.
~Note: box is added in 68ae3581439feff26f312272077be5615e2b3432 (next PR)~. Added now for CI

MSM/Serialization: split range checks implementations + add multiplicities

---

Cargo.lock
msm/Cargo.toml
msm/src/ffa/main.rs
msm/src/lib.rs
msm/src/prover.rs
msm/src/serialization/main.rs

Closes #1708. Adds `ProverError` that can be used instead of panicking in `prover.rs`.

Add ProverError to prover.rs

---

Cargo.lock
msm/Cargo.toml

Makes MSM project use top level workspace dependencies instead of individual one, as other crates in the repository do unless necessary.

Make MSM dependencies use workspace pattern as other crates

---

msm/src/verifier.rs

Bringing back the iterator, reversing some changes introduced by https://github.com/o1-labs/proof-systems/pull/1839.
Changed related to https://github.com/o1-labs/proof-systems/pull/1839#discussion_r1511607711

MSM: using iterator in the verifier

---

msm/src/prover.rs

Continue on https://github.com/o1-labs/proof-systems/pull/1914. Reintroducing previously removed changes.

MSM: reintroduce parallelism in the prover

---

kimchi/src/folding/error_term.rs
kimchi/src/folding/mod.rs
kimchi/src/folding/test.rs

Closes https://github.com/o1-labs/proof-systems/issues/1879
For now, the full test in `mod.rs` is commented out (and still incomplete). This PR gives now an example implementation of the folding traits, as well as some doc comments for each of them.
This branch is based on that in https://github.com/o1-labs/proof-systems/pull/1821

Improve folding docs

---

msm/src/prover.rs
msm/src/verifier.rs

The generation of the challenges should be at the same round for both the prover and the verifier.
We do not have a typed sponge unfortunately to detect that we coin at the right time. Maybe later.
I am integrating lookups for the serialization subcircuits. We will have tests when this is done.

MSM/MVLookup: add challenges into column environment

---

msm/src/ffa/columns.rs
msm/src/ffa/constraint.rs
msm/src/ffa/interpreter.rs
msm/src/ffa/main.rs
msm/src/ffa/mod.rs
msm/src/ffa/witness.rs
msm/src/lib.rs

Resolves #1791 . 
This PR splits existing test `a * b - c` and `a + b - c` circuit (together with witness generation) into interpreter-witness-circuit pattern. Does not change the circuit itself, only how it's represented. Moving some code around.
Previous part: https://github.com/o1-labs/proof-systems/pull/1904
Next part will implement the actual FFA addition circuit (or part of it, depending on the diff size).

MSM FFA Addition: Rewrite test circuit using interpreter pattern

---

optimism/src/keccak/column.rs

I realized that the optimization about moving sponge-related flags into shared column positions (starting on column 800) is not fully correct. Even if that seemed to reduce the number of total witness columns, because they are not supposed to be used in round steps, booleanity constraints would need to increase their degree by 1 or 2 so that they are only run when it is a sponge. Thus, because quadricization would increase the columns regardless, by a higher amount, I decided to revert that optimization for the sake of completeness and less complex constraints.
A similar PR is coming moving the rest of padding flags into the mode flags as well.

Keccak bug fix: move root flag into mode flags

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs
optimism/src/lookups.rs

Related to https://github.com/o1-labs/proof-systems/pull/1938, this PR fixes some constraints bugs due to having the padding flags in shared columns in sponge steps. Again, this could have been fixed otherwise by increasing the degree of the constraints by adding the `is_sponge` selector. But it is not worth it given that quadricization would have to increase the column width regardless.
This PR also includes other fixes in definitions of `pad_at_end` and `padding_blocks`. I had also forgotten about instantiating the inverse length column inside the witness.

Keccak bug fix: move padding flags out from sponge columns

---

optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs

The function used to access the zero bytes in sponges had an index mismatch, so I defined a new alias and adapted the functions accordingly. This is less error prone.

Keccak bug fix: index mismatch for zero bytes in sponge

---

optimism/src/keccak/witness.rs

The shifts were not being correctly instantiated from the witness in squeeze steps.

Keccak bug fix: instantiate squeeze shifts

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs
optimism/src/main.rs

This PR introduces the notion of a witness environment, which will substitute the plain witness that was being stored inside `KeccakEnv`. It provides some basic creation functions for it and renames the contents of the struct accordingly. More PRs will build on top of this change. A similar PR will come afterwards, referring to a constraints environment instead.

[easy] Create witness environment for Keccak

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/lookups.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs

This PR inlines `ArithOps` inside `KeccakInterpreter` and implements it for both the constraints and the witness environments. It also comments out a lot of the code so that it compiles, because at this point the functions are still not completely moved into the right traits.

Move `ArithOps` inside the interpreter trait

---

optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs

Boolean counterpart of https://github.com/o1-labs/proof-systems/pull/1950. Because the implementation is not different for witness and constraints, it can be generically described inside the trait description itself.

Move `BoolOps` inside the Keccak interpreter

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/witness.rs

Note that here `variable` and `constrain` are defined differently for witness and constraints environments.

Move variable-related functions inside the interpreter

---

optimism/src/keccak/column.rs
optimism/src/keccak/mod.rs

This PR addresses a follow-up issue brought up by Danny, who was suggesting to include a more ASCII-like type of comment to better visualize the content of the Keccak columns. 
While doing so, I realized that 4 columns were being reserved for the round constants both inside `mode_flags` and inside `curr`. I removed this redundancy to only be stored inside the former. That makes the column count 2220. This "fix" was not really a bug, but rather a non-necessary duplicate. Thus, tests worked both with it and without it.
TODO: when the instances are split into types (probably just round and sponge), we will be able to split the columns further and use less columns for sponge instances, and run fewer constraints on them.

ASCII Keccak doc comment + remove redundancy

---

optimism/src/keccak/interpreter.rs
optimism/src/keccak/tests.rs

This PR simply moves the constraints of the Keccak circuit into smaller functions, each of them targeting "one type" of constraints. This is just a cosmetic change, meant to provide more fine grain access to each part of the checks for future negative tests that can attack specific constraints separately. This will come in a future PR building on top of this one.

[no-op] Split Keccak constraints into smaller functions

---

optimism/src/keccak/column.rs

Some time ago, @volhovm pointed out that we could perhaps include more asserts in the Keccak code to make sure that we are always using right indices for the aliases. This PR addresses that, and the existing test verifies that no "index out of bounds" were being accessed in the first place.

[easy] Assert right index bound for Keccak columns

---

msm/src/column_env.rs
msm/src/expr.rs
msm/src/ffa/constraint.rs
msm/src/prover.rs
msm/src/serialization/constraints.rs
msm/src/verifier.rs

We want to keep it generic for the future. Part of https://github.com/o1-labs/proof-systems/pull/1966

Get rid of some MSM prefixes

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/witness.rs

This PR adds negative tests for the Keccak constraints with a fine-grain design.
In particular, I created an error enum to keep track of which constraint failed throughout execution. This way, when the constraints (either all, or just a subset of them) are run over a witness row, they keep track of the errors accumulated so far (if any) inside the `errors` variable in the witness environment. 
This way, each constraint is now paired with a tag with a name. That is the identifier used in the tests to assert that the expected errors were produced.

[easy] Fine-grain negative tests for Keccak constraints

---

msm/src/lookups.rs
msm/src/mvlookup.rs
msm/src/serialization/mod.rs
optimism/src/lookups.rs

When starting to create the multiplicities inside the Keccak witness environment, I realized that having the functionality of accessing a table's fixed length would come in handy. For this reason I modified the trait of lookup table ids to provide not just the converter into field index, but also a length function. 
@dannywillems Feel free to use it in any way you find useful in your code.

[easy] Implement length function inside the table trait

---

optimism/src/keccak/environment.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/witness.rs
optimism/src/lookups.rs

This PR addresses the `todo!()` inside `add_lookup()` of the witness environment of Keccak.  Here, when the lookup is a "fixed table lookup" (as opposed to read/write lookups, where it is a no-op for the witness), and the condition is satisfied (example, `is_round()` or `is_sponge()`), then it checks that the desired value is indeed in the given table. If this is not the case, the function pushes a lookup error to the list of errors in the environment. This latter behavior will be used in a coming PR in negative tests.
I added one simple positive test just to show that it works. But for now, it seems to be too slow when the tables and the variables are F. Perhaps I will create a follow-up PR where `Self::Variable = i128` instead for witnesses, so it is faster. No priority for now, as this …

Compute multiplicities of Keccak lookups in the witness environment

---

msm/src/serialization/constraints.rs

Cherry-pick from https://github.com/o1-labs/proof-systems/pull/1966

MSM: add rangecheck4 and rangecheck15 lookups in constraints

---

msm/src/column_env.rs

No-op. Only reorganizing the method `get_column` to handle case by case the lookup columns.

Logup: prepare the column environment to add the lookup

---

msm/src/mvlookup.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/witness.rs
optimism/src/lookups.rs

Note that now the tests can run all of the `lookups()` at each step (before, I was just running a subset of them) and the running time is FAST. 
TODO: this still does not address the generalization to use hash maps for the multiplicities. Also, I would like to abstract away the exact tables being used and infer them from a generic which is instantiated only once in the general environment.
Closes https://github.com/MinaProtocol/mina/issues/15171

Improve complexity of multiplicities computation from linear to constant

---

msm/src/ffa/mod.rs

The previous PR (https://github.com/o1-labs/proof-systems/pull/1934) introduces the circuit and witness builder, and it works end-to-end using the code in `main.rs`. 
This PR creates an explicit test that a built witness satisfies the constraints. Note that it's implicit, since witness building function checks the constraint internally, so we just need to build some witnesses in essense.

MSM FFA Addition: Add test for circuit consistency

---

.github/workflows/rust.yml

The CI is currently broken as it does use the most recent release (16th March '24).
From 0.9.68, nextest is only available from 1.73.
Getting rid of Rust 1.71 and 1.72 would be also an option, but it is not in the scope of this PR, and we must also check the consequences on minaprotocol/mina.

CI: use cargo-nextest@=0.9.67 instead of latest

---

kimchi/src/circuits/expr.rs

In a following PR, I will try to get rid of GenericColumn, and move it into ColumnEnvironment.
See https://github.com/o1-labs/proof-systems/pull/1990
Depends on https://github.com/o1-labs/proof-systems/pull/1991

Add error message when assert! fails

---

msm/src/column_env.rs
msm/src/prover.rs
msm/src/witness.rs

To keep the number of columns abstract through the type, and rely on types.
Later, this variable changes.
Cherry-picked commits from [dw/tmp-eval-8/](https://github.com/o1-labs/proof-systems/commits/dw/tmp-eval-8/)

MSM: witness_evals_env as a Witness structure

---

msm/src/prover.rs

We do not have any alpha in our expressions
Cherry-picked commits from [dw/tmp-eval-8/](https://github.com/o1-labs/proof-systems/commits/dw/tmp-eval-8/)

Remove wrong comments

---

msm/src/mvlookup.rs

We always use d8 (as we always suppose degree 7 for the lookup constraints).

Environment/Lookup: evaluations on d1 are not necessary

---

msm/src/column_env.rs

It is not useful anymore, as the code answers the concern.

ColumnEnvironment: remove old comments

---

poly-commitment/src/tests/commitment.rs

It seems to have changed, and clippy does not complain anymore.

Clippy: remove old annotation regarding type complexity

---

.github/workflows/rust.yml

From 0.9.68, nextest is only available from 1.73.

[develop] CI: use cargo-nextest@=0.9.67 instead of latest

---

poly-commitment/src/evaluation_proof.rs
poly-commitment/src/tests/batch_15_wires.rs
poly-commitment/src/tests/commitment.rs

After enforcing chunking size to be as expected (See PR #2010) the test_commit became flaky (and got into `master`). The issue was related to the sometimes appearing polynomials of zero degree: whereas previous code would always create at least one chunk, the new code was sometimes requiring and creating zero chunks.

Fix test_commit chunking issue

---

msm/src/ffa/witness.rs
msm/src/proof.rs
msm/src/serialization/mod.rs
msm/src/test/mod.rs
msm/src/test/witness.rs
msm/src/witness.rs
optimism/src/main.rs
optimism/src/proof.rs

Problem: When dealing with long columns (200+), msm/prover.rs was failing with stack overflow while creating the first witness evaluations. The tests were passing if stack size was increased via an environment variable (`RUST_MIN_STACK` it was I think).
Solution: Insead of storing a potentially long array directly in the witness, storing just a reference to it (Box) solves the problem.

MSM: Store Boxed array in Witness

---

msm/src/ffa/main.rs
msm/src/lib.rs
msm/src/mvlookup.rs
msm/src/proof.rs
msm/src/prover.rs
msm/src/serialization/mod.rs
msm/src/test/mod.rs
msm/src/verifier.rs

I want to enforce at the type level that the proof is only for a set of tables.
Also, coming in a following PR, we use a hashmap for the multiplicities and the fixed lookup tables, as discussed in previous PRs.

Logup: add table ID as a parameter for proofs

---

kimchi/src/circuits/expr.rs
kimchi/src/folding/example.rs
kimchi/src/folding/expressions.rs
kimchi/src/folding/mock.rs
optimism/src/folding.rs

This PR adds a `as_literal()` function inside the `Literal` trait of the `Expr` framework which is meant to transform expressions with special constants (meaning, EndoCoefficient, MDS, etc) to be represented as plain literal constants using as field value the content of a `Constants` variable passed as argument. 
This way, when using the folding library, one can first "literize" your expressions before converting them into folding compatible expressions. Otherwise, `from` will panic when reaching any special constant.
Closes https://github.com/o1-labs/proof-systems/issues/2034

Improve `Literal` so that folding expressions can take special constants as well

---

msm/src/fec/interpreter.rs
msm/src/fec/mod.rs
msm/src/fec/witness.rs
msm/src/test/mod.rs

Somehow https://github.com/o1-labs/proof-systems/pull/2006 managed to trick CI into thinking it compiles well. Probably CI result was outdated. Here's a few lines fix.

MSM: Add lookup IDs in tests, fixes broken master

---

msm/src/serialization/column.rs
msm/src/serialization/constraints.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs
msm/src/serialization/witness.rs

Creates some columns for FF multiplication in serialization circuit + describes how they're going to be used + lots of cosmetics to unify `serialization` with other two crates somewhat...
Addresses #1792 
Master PR: https://github.com/o1-labs/proof-systems/pull/2048

MSM FF Mul: Outline column structure

---

msm/src/fec/interpreter.rs
msm/src/serialization/interpreter.rs

Some functions between `fec/interpreter.rs` and `serialization/interpreter.rs` were copy-pasted. This removes some of them. Some others need to refer to the same interpreter to be removed (future work).
Parent PR: https://github.com/o1-labs/proof-systems/pull/2029

MSM: Remove duplicated mul code between fec/ and ser/

---

.github/workflows/rust.yml

From 0.9.68, nextest is only available from 1.73.

[o1js-main] CI: use cargo-nextest@=0.9.67 instead of latest

---

optimism/src/mips/constraints.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/witness.rs

This PR reates a wrapper called `variable` inside the interpreter that can be used inside `constraints.rs` to reduce the number of lines of code used before every time a variable was being returned.

Create `variable` function inside the MIPS interpreter to improve readability

---

kimchi/src/circuits/polynomials/keccak/constants.rs
kimchi/src/circuits/polynomials/keccak/mod.rs
optimism/src/keccak/column.rs
optimism/src/keccak/constraints.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/folding.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/witness.rs
optimism/src/lookups.rs
optimism/src/main.rs

This PR manages to split the all-purpose Keccak circuit into separate specialized steps so that each row can be made part of an independent instance for folding. In particular, it now has 6 different modes of operation: `Round`, `Sponge::Squeeze`, `Sponge::Absorb(First)`, `Sponge::Absorb(Middle)`, `Sponge::Absorb(Last)`, and `Sponge::Absorb(Only)` (they reuse the `Step` enum used previously).
Now, less constraints and actual columns are used in comparison with `master`. In particular, 2079 columns instead of 2219 (140 columns less), and the sub-circuit with more constraint is the `Sponge::Absorb(Only)`, which uses 474 constraints instead of 887. Also, constraints checking the correct composition of the flags are no longer needed, because now there will be a "public" selector for each of …

Split Keccak circuit into steps with specialized constraints

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/witness.rs

This PR builds on top of https://github.com/o1-labs/proof-systems/pull/2051 to bring splittability onto lookups. This way, each row of the circuit only adds the lookups that are specific to that step type. 
I modified the regression test accordingly.
Note that the maximum number of lookups per row corresponds to `Round` steps, with 1623 lookups (as opposed to 2361 that we had before, when all the lookups were run for all steps). 
Closes https://github.com/MinaProtocol/mina/issues/15163

Lookups counterpart of PR 2051

---

msm/src/mvlookup.rs
msm/src/proof.rs
optimism/run-code.sh
optimism/src/keccak/circuit.rs
optimism/src/keccak/environment.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/interpreter.rs
optimism/src/mips/mod.rs
optimism/src/mips/tests.rs
optimism/src/mips/witness.rs
optimism/src/proof.rs

This PR updates the `main.rs` file (and thus the zkvm demo) to split the instructions/steps into separate instances for MIPS and Keccak, as a prior step to folding. On top of that, the generic prover is being used with the actual constraints for both MIPS and Keccak. In order for this to work, I am creating a dummier folding algorithm which does not aggregate instances as a linear combination of the witnesses, but instead just keeps the last witness chunk. This for sure, will need to be modified when the folding library is fully in place, so that folded instances contain information about all the previous witnesses. The reason for this tweak now is that if I randomly aggregated witnesses without actually obtaining the corresponding error terms, the constraints would not be satisfied on …

Split MIPS and Keccak instances in `main` and proof with constraints

---

optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/column.rs
optimism/src/mips/mod.rs

Due to a missing reset of the scratch state index inside the `new` of the `CircuitTrait`, constraints were being created in the `main` with wrong indices coming from the accumulation of previous instructions.
This PR solves that issue.
Related to https://github.com/o1-labs/proof-systems/issues/2075, but still didn't fix the constraints failing.

Fix indexing in MIPS constraints environment

---

optimism/src/keccak/constraints.rs
optimism/src/keccak/helpers.rs
optimism/src/keccak/interpreter.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/witness.rs

After our chat about a general-purpose interpreter, I worked on this PR aiming to split the functionalities in the Keccak interpreter across different traits with separate scopes. In particular, I have split the old `KeccakInterpreter` into 5 traits: `Interpreter` (the most general type of interpreter I could think of for now), `KeccakInterpreter` (which contains Keccak-related functionalities for both witness and constraints environments), `ArithHelpers` (containing arithmetic operations), `BoolHelpers` (containing boolean operations), and `LookupHelpers` (containing lookup helpers for the tables used in the zkvm project).
Note that there is no need to parameterize these traits with any generic `Env` in particular. But instead, the use of the clause `where Self: Interpreter<F> + …

Separate functionalities of Keccak interpreter

---

optimism/src/keccak/column.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs
optimism/src/main.rs

This is to prevent having to manually create 
```
pub const STEPS = [ Round(0), Sponge(Absorb(First)), Sponge(Absorb(Middle)), Sponge(Absorb(Last)), Sponge(Absorb(Only)), Sponge(Squeeze)];
```
to iterate over all Keccak steps available.

[easy] Iterate over Keccak steps enum instead of static array of steps

---

optimism/src/main.rs
optimism/src/mips/constraints.rs

As pointed out in https://github.com/o1-labs/proof-systems/issues/2075#issuecomment-2072062084, some instructions were getting the prover process killed with memory overflow. Met with Danny, and confirmed that they are the ones with no constraints so creation of the quotient polynomial cannot be performed. Until the generic prover supports this corner case, this PR just ignores the instructions with zero constraints in the proving scope of the demo. 
NOTE: Even if they don't have any constraints, they will have lookups. So when lookups are added to the demo to compute the quotient polynomial, we should be able to generate proofs for them as well.
Partially addresses https://github.com/o1-labs/proof-systems/issues/2075
TODO: there are still a few instructions with failing constraints (they …

[easy] Ignore instructions with no constraints in main

---

msm/src/circuit_design/capabilities.rs
msm/src/circuit_design/constraints.rs
msm/src/circuit_design/mod.rs
msm/src/circuit_design/witness.rs
msm/src/fec/interpreter.rs
msm/src/fec/mod.rs
msm/src/lib.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs

* Creates a folder `circuit_designer` that now contains all "generic" code for designing circuits
* Splits the mono-trait "interpreter" into several "capabilities"
* `ColAccessCap`, `ColWriteCap`, `LookupCap` for now. 
* Future: Think also `RAMLookupCap`, `TransWireCommunicationCap` etc. The idea is that whenever one adds a "feature" (capability) to circuit building, it's a separate trait on a "interpreter environment". This makes things highly composable and (hopefully) future-proof.
* Also shows how "hacky" (IMO) helpers can be added for backwards compatibility -- example `bitmask_be` and `copy`.
Small bonus/side diff: I shrunk `deserialize_field_element` a bit. It was making things a bit easier.

Generic interpreter: Split into capabilities & move into separate folder

---

msm/src/circuit_design/composition.rs
msm/src/circuit_design/mod.rs

* Adds `composition.rs` which defines mechanics needed for calling one interpreter from another
* See https://github.com/o1-labs/proof-systems/pull/2036 for general POC end-to-end sketch
* Not adding "demo" as requested by @dannywillems https://github.com/o1-labs/proof-systems/pull/2036#pullrequestreview-2011009849
* Can write some `README.md` later. The "demo" is still in that old branch, so can be restored any minute.
* We'll start composing gadgets today anyway, which will be a real-world application to illustrate what's happening.

Generic interpreter: add composition (lenses)

---

msm/src/circuit_design/capabilities.rs
msm/src/fec/columns.rs
msm/src/fec/interpreter.rs
msm/src/fec/mod.rs

Before (for experimentation reasons) the columns in the FEC module were integer-based, so direct memory access by i:usize. Now the alias FECColumn explicitly names each column, which improves readability and safety.
+ it adds some helpers for convenience.

MSM FEC: Use labelled columns (easy)

---

ivc/src/poseidon/params.rs
poseidon/src/constants.rs

Test with `cargo nextest run "poseidon::params::tests::test_poseidon" --release`

Regression tests for poseidon over bn254

---

ivc/src/poseidon/interpreter.rs
ivc/src/poseidon/mod.rs

* Moves the code that writes Poseidon circuit wires into a separate `ColWriterCap`-type function
* Creates an additional lighter test just to verify if the circuit is correct without doing full prove/verify

Poseidon: separate generic builder + add a light circuit test

---

msm/src/fec/interpreter.rs
msm/src/fec/lookups.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/lookups.rs
msm/src/serialization/mod.rs

Previously: I thought we need 16 bit range checks to implement MSM FEC & Serialization circuits.
Now: 
* Actually managed to repack carries a bit tighter -- they're 79 bits and they were packed `[16 16 16 16 16 4]` so I repacked them into `[15 15 15 15 15 9]`. 
* I also added the "14abs" lookup table, so now these circuits have /all the/ range check tables they need :tada:

MSM: Use 15 bit carries in FEC/Serialization

---

folding/src/decomposable_folding.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/expressions.rs

`BinOp` was used in the previous version of the expression framework. It eases the translation between the new expression framework and the folding compatible one.

Folding: replace binop by mul/add/sub in FoldingCompatibleExpr

---

kimchi/src/circuits/expr.rs

It was only used by the FoldingCompatibleExpr enum, but it has been removed recently

Kimchi: remove Op2 enum

---

folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/examples/generic.rs
folding/src/examples/mod.rs

This can improved later. Maybe good already to merge a first iteration?
The initial idea was to get rid of duplicated code and improve my understanding of the implementation. If we want to expose the library later, it is good to have this kind of structure.
It can be mixed later with the generic interpreter/prover/verifier.

Folding: reorganize examples + add explanation for the user

---

msm/src/prover.rs
msm/src/verifier.rs

fq_sponge.challenge returns a correct scalar field element ScalarChallenge only wraps the scalar field element into a new structure to be passed to Caml/Pickles, apparently.

[easy] MSM: remove one unnecessary intermediary step

---

optimism/src/folding.rs
optimism/src/keccak/folding.rs
optimism/src/keccak/tests.rs
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/folding.rs

It seems we do redefine at multiple place the same types/structures. Uniformising it in this commit

Optimism: uniformising the imported/defined types

---

optimism/src/folding.rs
optimism/src/keccak/folding.rs
optimism/src/keccak/tests.rs
optimism/src/main.rs
optimism/src/mips/folding.rs

Based on discussion with Fabrizio, it seems that structure must contain data that is the same for the whole relation, like the matrices when we use R1CS. However, here, we do have nothing for MIPS/Keccak for now.

Folding/o1VM: make structure unit

---

folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/examples/generic.rs
folding/src/lib.rs
optimism/src/folding.rs

There must be only one definition of alphas, up-to-now. We don't need to
duplicate code N times.

Unify alpha structures

---

folding/src/checker.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/examples/mod.rs
folding/src/lib.rs
optimism/src/keccak/mod.rs
optimism/src/keccak/tests.rs

bn254 is always included.
If we only want to activate this test with a feature flag, we do have to use a different flag name than an optional feature flag used by another dependency and included by default in this crate.

Keccak tests: remove unecessary cfg(feature=bn254)

---

optimism/Cargo.toml

We do use ark-bn254 by default in optimism

Optimism: folding - always activate bn254 feature

---

optimism/src/mips/tests.rs

Ignore atm. Removed in https://github.com/o1-labs/proof-systems/pull/1401. Can be used later to verify true assignments after folding.

Reintroduce some tests in the zkVM interpreter.

---

folding/src/checker.rs
folding/src/decomposable_folding.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/instance_witness.rs
folding/src/lib.rs
optimism/src/folding.rs
optimism/src/keccak/folding.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/trace.rs
optimism/src/main.rs
optimism/src/mips/folding.rs
optimism/src/mips/tests.rs
optimism/src/mips/trace.rs
optimism/src/trace.rs

The goal of this PR is to fold one Keccak instruction in a test. In particular, it is folding `Sponge(Absorb(Only))` circuits together. For this to work, I had to make the following changes to the codebase, which are mostly collateral:
- For the domain size to be correctly spread out to the folding library, the `zero_vec()` vector inside `FoldingEnv` needed to be dynamically configurable. Otherwise, it was taking $2^{15}$ by default as the number of rows. 
- In particular, I realized that the `rows()` function inside `FoldingConfig` does not talk at all to the `zero_vec()` function, which was producing this mismatch. 
- Moreover, the `rows()` function was only being used by the examples, and never inside the actual code of folding. Thus, it looked quite superficial and I proceeded to …

Finish decompsable folding Keccak test

---

.github/workflows/gh-page.yml
.github/workflows/rust.yml
book/Makefile

Problem: 
* (recently added) mdbook linkcheck does not build with nightly.
* Checking that MDBook is not broken was not part of the build script, 
Solution:
* Now we check MDBook in CI (because we want to make sure contributions to the book are not buggy..?)
* Downgraded the book deployment version from `nightly` to `1.72` to be in line with the rust script/our main `rust-toolchain` version. 
Question:
* Why does our CI check the project builds with `1.74` but `rust-toolchain` is `1.72`? If we can upgrade it to `1.74` I can remove `--fixed` from the script, which is a way to make `mdbook` work on `1.72` which is our default version. Because lot of dependencies want `1.74` actually.

MDBook: Fix compilation + add CI check

---

optimism/src/folding.rs
optimism/src/keccak/folding.rs
optimism/src/keccak/tests.rs
optimism/src/keccak/trace.rs
optimism/src/lib.rs
optimism/src/main.rs
optimism/src/mips/folding.rs
optimism/src/mips/tests.rs
optimism/src/mips/trace.rs
optimism/src/trace.rs

This commit groups multiple changes.
First, it renames Trace and Tracer into `DecomposableTrace` and `DecomposableTracer`.
These names represent more the type of "objects"/traces the structure and the trait describe.
On top of that, additional documentation has been added at the top of the file trace.rs. Links to the structures using square brackets are added to detect old/inconsistent documentations mentioning code in the CI.
To finish, lines are broken into 80 characters long-lines to respect (old) coding conventions.

o1VM: rename `Trace(r)` into `DecomposableTrace(r)` + add docs

---

o1vm/src/keccak/folding.rs

This reverts commit f833cc04c9da2032d462aee30d98d45e64c754fc.
See https://github.com/o1-labs/proof-systems/pull/2206#issuecomment-2102833396

Revert "o1VM: remove type aliases in KeccakFolding"

---

o1vm/src/mips/folding.rs

This reverts commit 3d33602fb1f6bded4a3e77338c93a2862371b8d8.
See https://github.com/o1-labs/proof-systems/pull/2206#issuecomment-2102833396

Revert "o1VM: remove aliases MIPSFoldingWitness/MIPSFoldingInstance"

---

o1vm/src/folding.rs
o1vm/src/keccak/tests.rs
o1vm/src/keccak/trace.rs
o1vm/src/main.rs
o1vm/src/mips/folding.rs
o1vm/src/mips/tests.rs
o1vm/src/mips/trace.rs
o1vm/src/trace.rs

- SingleInstructionTrace into Trace
- DecomposableTrace into DecomposedTrace
- DecomposableMIPSTrace into DecomposedMIPSTrace
- Keep DecomposableTracer for trait
Addresses https://github.com/o1-labs/proof-systems/pull/2208#pullrequestreview-2048133087

o1VM: renaming trace related structures

---

folding/src/expressions.rs

Ease writing the expressions.
Used in future PRs.

[easy] Folding: implement std::ops on FoldingCompatibleExpr

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/lookups.rs
ivc/src/ivc/mod.rs
msm/src/circuit_design/capabilities.rs
msm/src/fec/interpreter.rs
msm/src/fec/lookups.rs
msm/src/serialization/interpreter.rs

This PR:
* Adds EC Addition stubs: wires are properly populated (but partially with dummy values, since we don't have buckets)
* Makes two types of lookups work together. See the `IVCFECLookupLens`. 
* Replaced `Abs1` lookup with `x^2 - 1` constraint. So much cheaper.
* Had to generalise/restructure some code along the way for readability.
Previous PRs:
1. https://github.com/o1-labs/proof-systems/pull/2139
2. https://github.com/o1-labs/proof-systems/pull/2140
3. https://github.com/o1-labs/proof-systems/pull/2141
4. https://github.com/o1-labs/proof-systems/pull/2144

IVC Circuit (Part 5): Add EC Addition Stubs

---

ivc/src/ivc/columns.rs
ivc/src/ivc/mod.rs
ivc/src/poseidon/columns.rs
ivc/src/poseidon/interpreter.rs
ivc/src/poseidon/mod.rs
msm/src/circuit_design/witness.rs
msm/src/column_env.rs
msm/src/columns.rs
msm/src/fec/columns.rs
msm/src/fec/mod.rs
msm/src/ffa/columns.rs
msm/src/ffa/mod.rs
msm/src/lib.rs
msm/src/proof.rs
msm/src/prover.rs
msm/src/serialization/column.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs
msm/src/test/columns.rs
msm/src/test/interpreter.rs
msm/src/test/mod.rs
msm/src/verifier.rs
o1vm/src/folding.rs
o1vm/src/keccak/column.rs
o1vm/src/keccak/tests.rs
o1vm/src/main.rs
o1vm/src/mips/column.rs
o1vm/src/trace.rs

Adding another column type, `FixedSelector`, to represent columns that are predefined for all instantiations of a given circuit.
Also:
* Added tests specifically for the fixed selector case
* Had to pass `N_FSEL` into MANY methods, but it's mostly boilerplate (we should generalise tests...). Similarly renamed `COL_N` into `N_COL` for consistency.
Addresses #2088

Fixed Selectors: Introduce support for

---

o1vm/src/mips/witness.rs

It makes the code safer, and we can run it with
RUSTFLAGS="-Coverflow-checks=y -Cdebug-assertions=y"
Also makes the code slightly faster as it might remove some equality testing if the implementation of overflow_add is done using assembly instructions

o1VM: use overflowing_add to handle overflow

---

folding/src/lib.rs
o1vm/src/folding.rs

At some point this was removed. Maybe a `mod tests` inside `o1vm/src/folding.rs` is not the perfect location for this, as it should ideally live inside the folding library. But for now let's have them there and then migrate them into `folding` with any additional changes that could be required.

Reintroduce folding expression conversion test

---

msm/src/circuit_design/witness.rs
msm/src/serialization/interpreter.rs

There were two `write_column` that acted in an uncoordinated manner. Now they interact and are called slightly differently.

Fix duplicate `write_column` [micro]

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
msm/src/fec/columns.rs
msm/src/fec/interpreter.rs

This PR:
* Adds IVC circuit design stubs related to one-off error computation & other misc parts (indices).
* Updates the diagram correspondingly.
* Modularises the FEC/Column structure for composing.
Previous PRs:
3. https://github.com/o1-labs/proof-systems/pull/2141
4. https://github.com/o1-labs/proof-systems/pull/2144
5. https://github.com/o1-labs/proof-systems/pull/2151

IVC Circuit (Part 6): Error computation in ECADDs

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs

This PR adds support for recombining alphas `alpha_O = alpha_L + r *alpha_R`, and u: `u_O = u_L + r` (generally, `u_O = u_L + r*U_R` but `u_R = 1`).
Previous PR:
- https://github.com/o1-labs/proof-systems/pull/2183

IVC Circuit (Part 8): Add support for u and alpha^i recombination

---

o1vm/src/folding.rs
o1vm/src/keccak/folding.rs
o1vm/src/keccak/tests.rs
o1vm/src/main.rs
o1vm/src/mips/folding.rs

Since https://github.com/o1-labs/proof-systems/pull/2239, no ProvableTrace is required.

Folding: use () instead of trace structures

---

msm/src/witness.rs
o1vm/src/folding.rs

It simplifies the code. At the end, we should have GenericWitness used instead of Witness for folding.
Follows https://github.com/o1-labs/proof-systems/pull/2238

Implement Foldable trait for GenericWitness

---

folding/src/checker.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/instance_witness.rs
folding/src/quadraticization_tests.rs
o1vm/src/folding.rs
o1vm/src/keccak/tests.rs

It seems it was only used for checking.
Using a parameter domain is more scalable, and let the user pick any kind of domain they want. It doesn't require the user to implement a new Witness implementation.
Driving the road to use generically the `GenericWitness` structure.

Folding: remove rows method in Witness trait

---

folding/src/checker.rs
folding/src/error_term.rs
folding/src/examples/example.rs
folding/src/examples/example_decomposable_folding.rs
folding/src/examples/example_quadriticization.rs
folding/src/instance_witness.rs
folding/src/lib.rs
folding/src/quadraticization_tests.rs
o1vm/src/folding.rs

The alphas can be inferred while evaluating. It removes a method to implement within the folding environment. For the challenges, it will be done in a follow-up PR.

Folding: remove alphas from FoldingEnv as it is obsolete

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/lookups.rs
ivc/src/ivc/mod.rs
msm/src/circuit_design/capabilities.rs
msm/src/circuit_design/composition.rs
msm/src/circuit_design/constraints.rs
msm/src/circuit_design/witness.rs
msm/src/test/test_circuit/mod.rs

Before: `ivc_circuit` was building all /witness/ wires, but /constraints/, e.g. `c_{b0,i}`, were available for every block separately. This means `c_{b0,i}` for block 0 would not work on rows of block 1.
Now:
* There are selectors for each block.
* Every constraint is now working for the /whole circuit/, since it's now multiplied by selector: `sel0 * c_{b0,i}`.
* Completeness test is added with lookups disabled.
Offtop:
* I added the `ID` lens because I wanted to generalise circuit generator to work for two tables simultaneously. This proved to /not/ be useful. But the `ID` lens is useful I think so I keep it.
Next step:
* Reduce stack usage. It overflows if stack is default 128KB, but fine with 2MB. Done in next PR https://github.com/o1-labs/proof-systems/pull/2247.

IVC: Add selector columns

---

ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
ivc/src/poseidon/mod.rs
msm/src/circuit_design/witness.rs
msm/src/column_env.rs
msm/src/fec/mod.rs
msm/src/ffa/mod.rs
msm/src/proof.rs
msm/src/prover.rs
msm/src/serialization/mod.rs
msm/src/test/logup.rs
msm/src/test/proof_system.rs
msm/src/test/test_circuit/mod.rs
msm/src/verifier.rs
msm/src/witness.rs
o1vm/src/keccak/tests.rs
o1vm/src/main.rs
utils/src/array.rs

With this PR, fixed selectors are not anymore part of the witness, and are passed separately. The intention is that they must be static for a given circuit.

Separate fixed selectors from the witness

---

ivc/src/ivc/mod.rs
ivc/src/poseidon/mod.rs
msm/src/circuit_design/witness.rs
msm/src/fec/mod.rs
msm/src/ffa/mod.rs
msm/src/precomputed_srs.rs
msm/src/serialization/mod.rs
msm/src/test/generic.rs
msm/src/test/mod.rs
msm/src/test/proof_system.rs
msm/src/test/test_circuit/mod.rs
o1vm/src/keccak/tests.rs

Reduces test code duplication by using generic completeness and soundness tests.

Use generic completeness/soundness tests

---

folding/tests/test_decomposable_folding.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_vanilla_folding.rs

It doesn't test that the computation happens correctly, but at least show that there is some non trivial computation.

Folding/tests: checking that commitments to error terms are non-zero

---

folding/src/decomposable_folding.rs
folding/src/lib.rs
folding/tests/test_vanilla_folding.rs

ins_i and wit_i variable names are reused. However, their semantics changed when
called compute_extension on the environment. The values contain the
commitments/evaluations added by quadriticization.
In a future PR, the values will be returned as part of the folded output to pass
them to the IVC circuit.

Folding: make the variable name more explicits

---

folding/src/decomposable_folding.rs
folding/src/error_term.rs
folding/src/instance_witness.rs
folding/src/lib.rs
folding/tests/test_decomposable_folding.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_vanilla_folding.rs

It is useful information to pass to the IVC circuit. I would suggest to improve the interface later.
Adding also documentation.
Regarding the usage of `clone`, I am not happy with it. It will imply a possible non-negligeable memory overhead. We should avoid this when the first version is released.

Folding: output the relaxed extended instances

---

Cargo.lock
kimchi/src/precomputed_srs.rs
kimchi/src/prover_index.rs
msm/Cargo.toml
msm/src/precomputed_srs.rs
poly-commitment/src/commitment.rs
poly-commitment/src/pairing_proof.rs
poly-commitment/src/srs.rs
utils/src/serialization.rs

What this PR does:
- Adds code for creating/reading BN254 "cached" SRS.
- Makes the "lagrange" field "optional on read". For future/past compatibility: it's not logically "essential", but very good to have.
- Generates the cached BN254 SRS with Lagrange bases (all up to the power), now used by tests.
- Makes serialization for these "test" SRS unchecked -- that helps to save time (5 sec for SRS, about as much for each Lagrange basis).
- Regenerates Pallas/Vesta SRS (with Lagrange bases), now applies to kimchi tests too. Renames them from `pallas.srs` to `test_pallas.srs` to emphasize that these are /not/ used in production and can be regenerated at any point if necessary.
Now many tests will be using the pre-computed SRS, which leads to approximately this kind of improvements for 2^15 SRS …

Improve SRS caching for tests

---

folding/src/error_term.rs
folding/src/expressions.rs
folding/src/instance_witness.rs
folding/src/lib.rs
folding/tests/test_decomposable_folding.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_quadraticization.rs
folding/tests/test_vanilla_folding.rs
ivc/tests/add.rs
o1vm/src/folding.rs
o1vm/src/mips/tests.rs
o1vm/src/trace.rs

We want to add blinders to our polynomials to handle commitments to zero.
We suppose the blinders are single scalars, and instead of committing to `P(X)`, we commit to `P(X) + r`, which results in `Comm(P) + r G` where `G` is the first element of our SRS.
We must coin a new random blinder for each folding execution, and use it for instance and witness.
~~The blinders must be coined *before* computing and absorbing the commitments to the error terms~~
We use the blinder `1`.

Folding: handling blinders

---

o1vm/src/mips/tests.rs

This PR initializes the RW memory and the general purpose registers of the dummy environment used in unit tests of MIPS instructions to random values. This gives us better guarantees.

Use random values for MIPS instructions unit tests

---

o1vm/src/mips/interpreter.rs
o1vm/src/mips/tests.rs

Added for `LoadWordLeft` (https://github.com/o1-labs/proof-systems/pull/2299), but making them a standalone PR for ease of review.

[easy] Unit tests for `sext` and `bitmask`

---

o1vm/src/mips/interpreter.rs
o1vm/src/mips/tests.rs

This PR makes some progress on top of the tracking issue https://github.com/o1-labs/proof-systems/issues/2075. 
In particular, because I didn't find any `Load16` instruction in the MIPS demo for the block I was testing, I added a unit test for `lh` replicating the one for `lw` done by @dannywillems some days ago. This way, we can have some certainty that the witness generated behaves as expected from the constraints.

Unit test for `Load16`

---

o1vm/src/mips/tests.rs
o1vm/src/mips/witness.rs

~TODO: add tests. DO NOT MERGE.~

Use overflow sub and unit test

---

o1vm/src/mips/constraints.rs
o1vm/src/mips/interpreter.rs
o1vm/src/mips/witness.rs

This PR proposes a different definition of the `equal` function of the MIPS interpreter so that it does not generate underflows when trying to subtract `x-y` and `y` is larger than `x` (for `u32` types). This is not a problem in fields, but it is when running unit tests built with unsigned types.
This is not the only place where subtraction underflows happen in unit tests. An upcoming PR will address the rest, which corresponds to the `FIXME` to allow multiple register accesses per instruction call.

Fix `equal` for witness interpreter

---

o1vm/src/mips/constraints.rs
o1vm/src/mips/interpreter.rs
o1vm/src/mips/witness.rs

This PR is meant to fix the subtraction underflows that appeared in unit tests when the same instruction was accessing the same register multiple times. This PR solves that issue by artificially increasing the instruction counter every time that register access takes place (so that the elapsed time is always a positive value). 
It compliments https://github.com/o1-labs/proof-systems/pull/2310. 
I tested it in a local branch with `LoadWordLeft` which used to fail for this reason (https://github.com/o1-labs/proof-systems/actions/runs/9447808562/job/26020430671?pr=2299), and now with the same seed the test `RUSTFLAGS="-Coverflow-checks=y -Cdebug-assertions=y" cargo test --package o1vm --lib --all-features --release -- mips::tests::unit::itype::test_unit_lwl_instruction --exact --show-output` …

Fix instruction counter to allow multiple register/memory accesses per instruction call

---

msm/src/test/test_circuit/mod.rs

To handle the case the polynomial evaluations are always the same

MSM: fixed selectors with fixed values, 42, instead of random

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
ivc/src/poseidon_55_0_7_3_2/columns.rs
ivc/src/poseidon_55_0_7_3_2/interpreter.rs
ivc/src/poseidon_55_0_7_3_2/mod.rs
ivc/src/poseidon_55_0_7_3_7/columns.rs
ivc/src/poseidon_55_0_7_3_7/interpreter.rs
ivc/src/poseidon_55_0_7_3_7/mod.rs
ivc/src/poseidon_8_56_5_3_2/columns.rs
ivc/src/poseidon_8_56_5_3_2/interpreter.rs
ivc/src/poseidon_8_56_5_3_2/mod.rs

Built on top of !https://github.com/o1-labs/proof-systems/pull/2306
in 2306, the round constants are considered as witness values. Simply making them public to not fold them later.

IVC/Poseidon: make the round constants public values

---

ivc/src/ivc/columns.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs

In https://github.com/o1-labs/proof-systems/pull/2269/files, it redefines the same structure. Removing here to avoid duplication.

IVC: reuse definitions of Poseidon parameters for bn254

---

folding/src/eval_leaf.rs

Because of this order in `bin_op`, the subtraction `a - b` was evaluated as `eval(b) - eval(a)` which is wrong.

Fix evaluation order error in folding

---

o1vm/src/lib.rs
o1vm/src/mips/column.rs
o1vm/src/mips/constraints.rs
o1vm/src/mips/interpreter.rs

As part of the debugging process I realized that the witness columns storing the values for the dynamic selectors (instructions) in MIPS were not being mapped to the right indices. In particular, they were appearing _at the beginning_ of the witness, instead of _at the end_, which could be causing potential overwrites of relation witness data (for example, the selector column for `SyscallReadPreimage` was 11 instead of 106, which is 95 (relation columns) + 11, but the scratch state 11 is meant to store other type of data).
I thought that could have been the problem behind the failing constraints containing `self.equal()` (these have a `-1` which can only hold when real data is used, meaning not all zeros). But those are still failing after this fix, so it must be something else. I am …

Fix `ColumnIndexer` in MIPS (wrong order of selector columns)

---

ivc/src/ivc/columns.rs
ivc/src/ivc/constraints.rs
ivc/src/ivc/helpers.rs
ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
ivc/tests/add.rs

The "interpreter" design aims to split the witness and constraint environment. This is a first step into the clean refactorisation of the IVC circuit.

IVC: move constraints related functions

---

ivc/src/poseidon_8_56_5_3_2/bn254/mod.rs
ivc/src/poseidon_8_56_5_3_2/mod.rs

The constants will be useful to the IVC library user to compute the number of challenges it does require.

IVC/Poseidon: add documentation and constants

---

kimchi/src/circuits/constraints.rs

Add the unit test for checking the `domain_size` of circuit, when the gates use the same table
- Resolve #1335 
- add the `test_lookup_domain_size_computation` in `kimchi/src/circuits/constraints.rs`

test: add the unit test for computing the `domain_size`

---

.github/workflows/gh-page.yml

See https://github.com/peaceiris/actions-gh-pages/blob/v4.0.0/CHANGELOG.md
Also, see https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Currently there are warnings in the CI when publishing the documentation

[EASY] CI: bump up actions-gh-pages to version 4

---

ivc/src/ivc/columns.rs

And clean old not functional/drafty code
In https://github.com/o1-labs/proof-systems/pull/2368 and in tests, we use this value to build real world examples.

[EASY] IVC: attempt to define the real number of columns

---

folding/src/expressions.rs
ivc/src/ivc/mod.rs
ivc/tests/add.rs

It is required to have a correctly shaped/sound IVC circuit.

[EASY] IVC: add the challenges required by the block selection and expose the IVC challenges count

---

ivc/src/ivc/columns.rs

This is useful to generate the doc, and verifying the code matches the specification while reviewing/implementing.
I noticed some inconsistencies between the code and the specification.
Also, changing 6 to 12 for the number of hashes required per commitment. See the comment in the code. I added https://github.com/o1-labs/proof-systems/pull/2368 to verify we can still handle the MIPS interpreter.

[EASY] IVC/Columns: simply move circuit layout to top-level + doc block height

---

ivc/src/ivc/mod.rs
ivc/tests/folding_ivc.rs

The tests pass, but it is only because the additional columns are not considered in the completeness tests for now. It will fail when we do use folding with it.

IVC: regression tests for the number of additional columns added by the reduction to degree 2

---

ivc/src/ivc/mod.rs
ivc/tests/add.rs
ivc/tests/folding_ivc.rs
msm/src/fec/columns.rs
msm/src/fec/interpreter.rs
msm/src/fec/mod.rs

FEC ADD had degree 3 because of `q1_sign`, and about `229` columns. Now it has degree 2 and about `245` columns because I did quadraticisation in place. I added "big" q1/q2/q3 limbs, and I multiply them by sign separately instead of multiplying all together.

FEC ADD: Decrease degree to 2

---

ivc/src/ivc/interpreter.rs

The columns were written twice: both in IVC and inside the ECC gadget. Not critical, just an artifact.

[#2313] Porting IVC+ADD 7: Remove double column writing for ECAdd

---

Cargo.lock
poseidon/Cargo.toml
poseidon/benches/poseidon.rs

Will be used later to bench https://github.com/o1-labs/proof-systems/pull/2394.
Output on my machine of `cargo bench`:
```
poseidon_absorb_permutation kimchi                                                                             
time:   [50.202 µs 50.240 µs 50.309 µs]
Found 8 outliers among 100 measurements (8.00%)
4 (4.00%) high mild
4 (4.00%) high severe
poseidon_absorb_permutation legacy                                                                            
time:   [52.858 µs 52.875 µs 52.894 µs]
Found 5 outliers among 100 measurements (5.00%)
4 (4.00%) high mild
1 (1.00%) high severe
```

mina_poseidon: bench poseidon block cipher [master]

---

poseidon/src/poseidon.rs

Cherry-picked https://github.com/o1-labs/proof-systems/pull/2394.
Output on my machine:
```
poseidon_absorb_permutation kimchi                                                                             
time:   [30.086 µs 30.131 µs 30.221 µs]
change: [-40.050% -39.774% -39.371%] (p = 0.00 < 0.05)
Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
1 (1.00%) low mild
1 (1.00%) high mild
10 (10.00%) high severe
poseidon_absorb_permutation legacy                                                                             
time:   [49.133 µs 49.157 µs 49.180 µs]
change: [-7.0440% -6.9919% -6.9411%] (p = 0.00 < 0.05)
Performance has improved.
Found 8 outliers among 100 measurements (8.00%)
1 (1.00%) low severe
5 (5.00%) low mild
1 (1.00%) high mild
1 (1.00%) high …
```

Manually unroll x^7 for poseidon for a ~50% speedup [master]

---

ivc/src/expr_eval.rs
ivc/src/lib.rs
ivc/tests/add.rs

Moves code into a separate module. This time it's the code that evaluates folding expressions.

Folding Prover 2: Move IVC folding expresion evaluation into separate module

---

folding/src/eval_leaf.rs
folding/src/expressions.rs
folding/src/lib.rs
folding/src/standard_config.rs
folding/tests/test_decomposable_folding.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_quadraticization.rs
folding/tests/test_vanilla_folding.rs
ivc/src/plonkish_lang.rs
ivc/tests/add.rs
ivc/tests/folding_ivc.rs
o1vm/src/folding.rs

This change is needed because:
* In the next PR we will need to generalize our evaluator
* Slices are enough, are strictly more generic then vectors, and allow to avoid cloning where one needs to unify vectors with e.g. tuples.

Folding Prover 3: Use slices instead of vecs in folding

---

Cargo.lock
ivc/Cargo.toml
ivc/src/expr_eval.rs
ivc/src/lib.rs
ivc/src/poseidon_8_56_5_3_2/columns.rs
ivc/src/prover.rs
ivc/src/verifier.rs
ivc/tests/add.rs

This PR:
* Adds prover and verifier together with some prover types. This is 95%+ copy paste from the MSM.
* Generalizes evaluator for folding expressions to support vectors. This is needed because in the prover we evaluate over columns (polynomials `P(X)`), while in the verifier we evaluate expressions over zeta-evals (evaluations `P(zeta)`).
* Fixer a minor bug where `N_COL` (total column number) for Poseidon was only counting `N_WIT` (total non-fixed column number).

Folding Prover 4: Add actual prover and verifier

---

ivc/src/ivc/mod.rs

`build_selectors` already contains building selectors for the Poseidon circuit, so these calls were unnecessary.

Remove unnecessary fixed_selector double-building

---

ivc/src/prover.rs
ivc/src/verifier.rs
msm/src/prover.rs
msm/src/verifier.rs

Explanation:
- The FT polynomial in Plonk is defined as Z_H(X) * (...) and is subtracted in construction of linearization polynomial
- In our case, FT polynomial already contains the minus.
- Therefore, we have to evaluate the negation of the expression (constraint), not the constraint itself.
- This PR makes this mechanics more clear, and brings this negative semantics into the IVC prover (which used the positive sign instead)
In essense, this documents the MSM generic prover, and makes IVC prover follow the logic.

Fix the sign of the ft poly in IVC prover/verifier

---

ivc/src/ivc/lookups.rs
msm/src/circuit_design/witness.rs
msm/src/fec/lookups.rs
msm/src/fec/mod.rs
msm/src/ffa/lookups.rs
msm/src/ffa/mod.rs
msm/src/logup.rs
msm/src/lookups.rs
msm/src/serialization/column.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/lookups.rs
msm/src/serialization/mod.rs
msm/src/verifier.rs
o1vm/src/lookups.rs

Work in progress branch. 
I'm extending the existing `logup` module to support non-compile-time-fixed tables.
Addresses #2089

Add support for runtime tables

---

ivc/src/ivc/lookups.rs
msm/src/circuit_design/witness.rs
msm/src/fec/lookups.rs
msm/src/ffa/lookups.rs
msm/src/logup.rs
msm/src/lookups.rs
msm/src/serialization/lookups.rs
msm/src/serialization/mod.rs
o1vm/src/lookups.rs

We'll have to support runtime tables, and this is a minor step towards it.

[#2089] Make ix_by_value return Option to support runtime tables

---

ivc/src/ivc/interpreter.rs
ivc/src/ivc/mod.rs
ivc/tests/simple.rs
msm/src/test/test_circuit/interpreter.rs
msm/src/test/test_circuit/mod.rs

This PR:
- Adds a single `build_fixed_selectors` into test circuits, so that we have a single place of reference for them. Fixed selectors have to be (compile-time preferably) fixed.
- Renames `build_selectors` into `build_fixed_selectors` to avoid confusion with dynamic selectors.
Backstory:
- As part of #2088 I was working on a unifying interface that'd allow to define fixed selectors for a particular gadget. 
- But I got progressively more convinced this would be too much of a "circuit language design". I'd like to do it but I think it misaligns with our current goals.
- Therefore, I'll try to focus on features and will close #2088 as soon as we have everything functionally. Feel free to object.

Fixed selectors cosmetics

---

folding/src/decomposable_folding.rs
folding/src/error_term.rs
folding/src/instance_witness.rs
folding/src/lib.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_vanilla_folding.rs
ivc/src/plonkish_lang.rs
ivc/tests/simple.rs

This PR:
- Adds code that checks instance-level folding (no witness, verifier side) where missing
- Adds tests to it
- Introduces the corresponding check into `simple.rs` IVC test, where we have to check the last fold validity natively.

[#2428] Add native-level folding checks into ivc/simple + folding lib

---

ivc/src/plonkish_lang.rs
ivc/src/prover.rs
ivc/tests/simple.rs

Previously, `simple.rs` was SNARKing the pre-last folded instance; in this PR we SNARK the last one.

IVC: Adding SNARK on the final fold

---

msm/src/circuit_design/witness.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs
msm/src/test/test_circuit/columns.rs
msm/src/test/test_circuit/interpreter.rs
msm/src/test/test_circuit/lookups.rs
msm/src/test/test_circuit/mod.rs

* Now one declare both multiple /reads/ and writes for runtime tables.
* Also tests for lookups are now in `msm/src/test/test_circuit` (and not `serialization`).

Lookups: Add support for multiple reads in runtime tables

---

kimchi/src/tests/framework.rs

The function is actually used (in tests), but was producing an annoying warning. So `allow(dead_code)` it is.

Fix setup_with_custom_srs warning

---

README.md
flake.nix

This is the start of a very simple flake.
In scope for this version of the flake:
1. `nix develop .` will open a dev shell with everything you need to develop on various parts of `proof-systems` in scope (caveat about rust and ocaml toolchain version in next point).
2. You must still use `rustup` to manage your rust toolchains.
3. You must still use `opam` to manage your ocaml toolchains.
Out of scope for this version of the flake:
1. Distributed caching -- only if the others in this list come.
2. Actually building things using `nix` -- likely to come.

Add initial flake for installing build dependencies for `proof-systems`

---

o1vm/src/mips/constraints.rs
o1vm/src/mips/interpreter.rs

Addressing feedback from @dannywillems in https://github.com/o1-labs/proof-systems/pull/2357 regarding range checks of 2 bits. Instead of using the general lookup to the byte table (which will use 2 lookups), this one makes use of another fixed table we already had that only includes the 0, 1, 2, 3 values.

[easy] Save 1 lookup when checking [0,4)

---

.github/actions/ocaml-shared/action.yml

Released earlier this year in July. No big changes. Only bumping up to stay up-to-date.

CI: bump up setup-ocaml version to v3

---

Makefile

We do use some unstable feature, like:
```
Warning: can't set `indent_style = Block`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
```

Makefile: use nightly for `format` target

---

kimchi/src/lagrange_basis_evaluations.rs

This PR is part of https://github.com/o1-labs/o1js/issues/1806 .
It is a no-op, simply adding more verbosity to the specs and comments related to the chunked Lagrange evaluations.

Improved comments for chunked Lagrange evaluations

---

kimchi/src/lagrange_basis_evaluations.rs

~~@querolita: evaluate_boolean could simply have a result variable equals to a `usize` (instead of `F::zero`) and is adding one only when it is non-zero. That way, we get a (potentially) non-negligible optimization as we simply add one to a machine word (usize) and perform no (potential) modular arithmetic operations. From there, we must also add a condition on the maximum number of evaluation points (which is 2^64 - 1 on 64bits CPU), which, IMO, looks fine at the moment.~~ Ignore. Wrong.
It seems that `evaluate_boolean` is used only by selectors in kimchi/provers.rs.
I would also add an `unsafe` keyword to mention that we do not check that the evaluations are actually one or zero only.

LagrangeBasisEvaluations: different suggestions

---

kimchi/src/tests/mod.rs
kimchi/tests/turshi.rs

We should do that for all tests, as toplevel directory tests is what a good rustacean would do. Not spending time on this for now, though. Not urgent at all.

Kimchi/tests: move turshi tests into top-level tests dir

---

mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs
mvpoly/tests/prime.rs

Will be used in https://github.com/o1-labs/proof-systems/pull/2502 and https://github.com/o1-labs/proof-systems/pull/2520
The tests using add_monomial implemented for `monomials` will be implemented for prime after https://github.com/o1-labs/proof-systems/pull/2531 is merged as it requires `add_monomial` to make it generic.

MVPoly: implement homogeneous_eval

---

mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/pbt.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs
mvpoly/tests/prime.rs

- https://github.com/o1-labs/proof-systems/pull/2540
- It was required for generic tests to extend the `MVPoly` trait with the:
```rust
fn modify_monomial_with_scalar(&mut self, scalar: F);
```
And implement it for `Sparse` and `Dense` structs.
Not sure though if it makes sense to do for `MVPoly` or maybe we should do it with some helper trait instead.

MVPoly tests generalization based on example.

---

Cargo.toml

* Added `parallel` and `asm` flags to `ark-std` and `ark-test-curves`
* Bumped requirements on `rmp-serde` and `serde_json`: the actual locked packages were already set to this new version, this is just for `Cargo.toml` files to look similar on proof-systems side & bindings side.

Unify cargo requirements with bindings, add asm flags

---

arrabiata/src/columns.rs
arrabiata/src/constraints.rs
arrabiata/src/interpreter.rs
arrabiata/src/lib.rs
arrabiata/src/witness.rs
arrabiata/tests/witness.rs

Note: we will certainly deprecate other versions later. Only leaving it for now.
Constraints checks come right after.
Fix https://github.com/o1-labs/proof-systems/issues/2565

Arrabiata: implement PoseidonNextRow - a variant of the gadget Poseidon using "next row"

---

o1vm/Cargo.toml
o1vm/src/pickles/main.rs

I am not able to run it now (unstable Internet connection).
Use
```
cargo run --bin pickles_o1vm \
--all-features \
--release \
-p o1vm -- \        
--pprof.cpu \
--info-at "${INFO_AT:-%10000000}" \
--snapshot-state-at "${SNAPSHOT_STATE_AT:-%10000000}" \
--proof-at never \
--stop-at "${STOP_AT:-never}" \
--input "${ZKVM_STATE_FILENAME:-./state.json}" \
-- \
./ethereum-optimism/op-program/bin/op-program \
--log.level DEBUG \
--l1 "${L1_RPC}" \
--l2 "${L2_RPC}" \
--network sepolia \
--datadir "${OP_PROGRAM_DATA_DIR}" \
--l1.head "${L1_HEAD}" \
--l2.head "${L2_HEAD}" \
--l2.outputroot "${STARTING_OUTPUT_ROOT}" \
--l2.claim "${L2_CLAIM}" \
--l2.blocknumber "${L2_BLOCK_NUMBER}" \
--server
```

o1vm/pickles: initialize the structure

---

o1vm/src/interpreters/keccak/tests.rs
o1vm/src/interpreters/mips/tests_helpers.rs
o1vm/src/legacy/folding.rs
o1vm/src/legacy/main.rs
o1vm/src/legacy/mod.rs
o1vm/src/lib.rs

The pickles flavor would use Pasta curves.

o1vm: only legacy version should be using bn254

---

poseidon/export_test_vectors/src/vectors.rs
utils/src/field_helpers.rs

Problem: in `export_test_vectors` instead of (`f_elem.into_repr() -> f_elem.into_bigint()`) the renaming during the arkworks upgrade was mistakenly (`f_elem.into_repr() -> f_elem.0`), which also returns a bigint, but it's a different bigint!
I also scanned for all `into_repr()` renamings in the original arkworks PR diff and only found another similar issue in `field_helpers`, but there it's immaterial (fixed anyway).
Regression test confirmed to work on `1494cf973d40fb276465929eb7db1952c5de7bdc` (last commit on `develop` before arkworks 0.4.2).

Arkworks 0.4.2: fix test vectors serialization issue

---

book/specifications/kimchi/template.md
book/src/specs/kimchi.md
kimchi/src/circuits/polynomials/foreign_field_add/circuitgates.rs
kimchi/src/circuits/polynomials/foreign_field_mul/circuitgates.rs
kimchi/src/circuits/polynomials/range_check/circuitgates.rs
kimchi/src/verifier.rs

During some of the recent sync PRs, the `develop` rust comments were not updated, but the book was updated. Since some parts of the book are auto-generated from the rust code (comments), this now produces diff on `develop` every time I run `cargo build`.
With this PR, the auto-generated book matches what is committed.

Fix the cargo docs to match the auto-generated ones (1min)

---

book/src/specs/kimchi.md

Different from https://github.com/o1-labs/proof-systems/pull/2599!
Can someone please double check? Whenever I'm on `develop` and run `cargo clean && cargo build --all-targets --all-features --tests` I get the changes in `kimchi.md` which are committed in this PR. If it's what `cargo` does then let's commit it I guess. If not, happy to close/investigate.

Auto-align kimchi md file (tabs/spaces?) [cosmetics/easy]

---

kimchi/src/prover.rs
poly-commitment/src/commitment.rs
poly-commitment/src/evaluation_proof.rs

It is more logical to move where OpeningProof is defined. This way, it follows the convention.

Poly_commitment: move CamlOpeningProof into eval_proof where defined

---

poly-commitment/src/commitment.rs
poly-commitment/src/srs.rs

In future PR, SRS will be moved into evaluation_proof, which will be called ipa. Step by step.

Poly_commitment: move SRS trait implementation where SRS is defined

---

poly-commitment/src/commitment.rs
utils/src/field_helpers.rs

It is strictly related to fields, and only used by poly-commitment. Worth moving into field_helpers

Poly_commitment/utils: move product into field_helpers

---

.github/workflows/ci.yml

Re-enable updated specification CI check for `develop`.

---

mvpoly/src/pbt.rs

The multiplication doesn't check that the resulting degree is higher than the one encoded in the type. We do have to change the type signature in the near future.

MVPoly/tests: fix maximum degree for multiplication

---

book/src/specs/kimchi.md

After this PR was merged (https://github.com/o1-labs/proof-systems/pull/2598), the book was updated, however this was not committed in the PR itself.
I think there was a CI test before that was checking whether auto-generated book matches the commited one. We should probably have this again.

Update book description with auto-generated stuff [1min cosmetic]

---

Cargo.lock
kimchi/src/circuits/expr.rs
kimchi/src/circuits/polynomials/turshi.rs
kimchi/src/lagrange_basis_evaluations.rs
kimchi/src/tests/and.rs
kimchi/src/tests/ec.rs
kimchi/src/tests/endomul.rs
kimchi/src/tests/endomul_scalar.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/foreign_field_mul.rs
kimchi/src/tests/lookup.rs
kimchi/src/tests/not.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/recursion.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/varbasemul.rs
kimchi/src/tests/xor.rs
poly-commitment/src/commitment.rs
poly-commitment/src/pairing_proof.rs
poly-commitment/src/tests/commitment.rs
poly-commitment/src/tests/serialization.rs
poseidon/export_test_vectors/Cargo.toml
poseidon/export_test_vectors/src/vectors.rs
utils/src/foreign_field.rs

Using `o1_utils::tests::make_test_rng` everywhere.
Porting the following from master to develop:
- PR https://github.com/o1-labs/proof-systems/pull/1942
- Commit 47aa2608a905786b207447dd064681cfa4d7292f
Continuing:
- https://github.com/o1-labs/proof-systems/pull/2614

Use make_test_rng in develop

---

poly-commitment/src/commitment.rs
poly-commitment/src/kzg.rs
poly-commitment/tests/ipa_commitment.rs
poly-commitment/tests/kzg.rs

The routine isn't used for IPA, it is only used by the KZG PCS.

Poly-commitment: move combine_evaluations in kzg module

---

arrabiata/src/witness.rs
arrabiata/tests/witness.rs
folding/src/decomposable_folding.rs
folding/src/instance_witness.rs
folding/src/lib.rs
folding/tests/test_decomposable_folding.rs
folding/tests/test_folding_with_quadriticization.rs
folding/tests/test_vanilla_folding.rs
ivc/src/plonkish_lang.rs
ivc/src/prover.rs
ivc/tests/simple.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs
kimchi/src/verifier_index.rs
msm/src/prover.rs
msm/src/test/generic.rs
o1vm/src/legacy/trace.rs
poly-commitment/src/chunked.rs
poly-commitment/src/commitment.rs
poly-commitment/src/ipa.rs
poly-commitment/src/kzg.rs
poly-commitment/tests/kzg.rs

It is more meaningful because it is actually chunks. In following pull requests, the abstraction over PolyComm will be changed, to avoid erroneous usage of PolyComm.
It is part of the implementation of the prover into pickles, as I noticed I made a small error while splitting the quotient polynomial in chunks.
I am breaking the usage of PolyComm in develop, and in Mina, cc @volhovm as you will work on merging develop into master for proof-systems.

Poly-commitment: rename elems field into chunks

---

folding/src/decomposable_folding.rs
folding/src/instance_witness.rs
folding/src/lib.rs
ivc/src/plonkish_lang.rs
kimchi/src/prover.rs
kimchi/src/verifier.rs
poly-commitment/src/ipa.rs

`len()` on PolyComm is exactly implemented as `chunks.len()` It is part of a work abstracting the structure `PolyComm`, and remove the access to the field `chunks`.

PolyComm: use method len directly instead of chunks.len

---

o1vm/src/pickles/main.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/proof.rs
o1vm/src/pickles/prover.rs

It is only a sketch, and only consists of committing to the polynomials at the moment, and evaluates them at \zeta and \zeta \omega.
We still need to:
- add the quotient polynomial -> will be in other PR, after !2604
- eval on a bigger domain. At the moment, we only interpolate on d1 and commit. We should evaluate on a bigger domain depending on the degree of the constraints.
Built on top of https://github.com/o1-labs/proof-systems/pull/2649

o1vm/pickles: prover

---

poly-commitment/src/commitment.rs
poly-commitment/src/kzg.rs

is_empty is exactly an alias for chunks.is_empty

PolyComm/KZG: use is_empty directly instead of accessing field

---

Cargo.lock
o1vm/Cargo.toml
o1vm/src/pickles/column_env.rs
o1vm/src/pickles/main.rs
o1vm/src/pickles/prover.rs

TODO:
- absorb the commitments
- add in the opening proof
Note that this will break the e2e tests because selectors polynomials are not defined correctly at the moment.

o1vm/pickles: introduce the computation of the quotient polynomial

---

o1vm/src/pickles/prover.rs

elems has been renamed in chunks previously (cf https://github.com/o1-labs/proof-systems/pull/2658), to map the actual meaning of the field of the structure

o1vm/pickles: using new instead of elems - fixing master

---

o1vm/src/pickles/prover.rs
poly-commitment/src/ipa.rs
poly-commitment/src/lib.rs
poly-commitment/src/pbt_srs.rs
poly-commitment/tests/ipa_commitment.rs

While working on the prover for o1vm/pickles, I was wondering the number of chunks `commit_non_hiding` was supposed to return in different cases, in particular when the polynomial has a degree higher than the number of chunks requested. This test clarifies it.
I hope it doesn't duplicate another test - I didn't look for.
As @querolita is (was?) working on chunking, cc'ing her as she might be interested in.

Poly-commitment/IPA: additional tests regarding expected nb chunks

---

kimchi/src/prover.rs

PolyComm/Kimchi: use into_iter instead of accessing chunks field

---

clippy.toml
poly-commitment/src/commitment.rs
poly-commitment/src/ipa.rs
poly-commitment/src/kzg.rs
poly-commitment/src/lib.rs

These are changes I was making while writing the prover in o1vm/pickles, and it is a follow-up on the pair-coding session we had early this week with @marcbeunardeau88
The changes are mostly esthetics for the online documentation generation, see https://o1-labs.github.io/proof-systems/rustdoc/

Poly-commitment: modestly improve documentation

---

arrabiata/src/main.rs

Might not be complete. Only to keep it in the master branch for external contributors.
Eventually, all steps will be moved into a single method in the witness environment.

Arrabiata/main: add multiple FIXME to remind the next steps

---

o1vm/src/pickles/mod.rs
o1vm/src/pickles/prover.rs
o1vm/src/pickles/tests.rs

To Reviewer: I didn't add the quotient polynomial to the OpeningProof.  Not sure if it's needed, but will if it is.

o1vm/pickles: Remove linearization and add quotient polynomial evaluations

---

book/src/specs/kimchi.md
circuit-construction/src/tests/example_proof.rs
kimchi/src/circuits/expr.rs
kimchi/src/lagrange_basis_evaluations.rs
kimchi/src/prover_index.rs
kimchi/src/tests/foreign_field_add.rs
kimchi/src/tests/generic.rs
kimchi/src/tests/range_check.rs
kimchi/src/tests/rot.rs
kimchi/src/tests/serde.rs
kimchi/src/tests/xor.rs
kimchi/src/verifier.rs
poly-commitment/src/commitment.rs
poly-commitment/src/hash_map_cache.rs
poly-commitment/src/lib.rs
poly-commitment/src/pairing_proof.rs
poly-commitment/src/srs.rs

This PR adds the concept of `HashMapCache` to remove the potential for errors / panics in code. In particular, this addresses https://github.com/o1-labs/o1js/issues/1411.

Make lagrange basis handling safe

---

o1vm/src/interpreters/mips/constraints.rs
o1vm/src/pickles/mod.rs
o1vm/src/pickles/tests.rs

the selectors were only constrained to be boolean
We add the constraint that one and only one
of them is activated.

o1vm/constraint : add a missing constraint for sel

---

arrabiata/src/columns.rs
arrabiata/src/constraints.rs
arrabiata/src/interpreter.rs
arrabiata/src/lib.rs
arrabiata/src/witness.rs
arrabiata/tests/constraints.rs
arrabiata/tests/witness.rs

These are leftovers from the initial draft of Arrabiata. The gadgets won't be used.
If we want to get them back, we can always revert the commit. But for now, I would remove them to clean the code.

Arrabiata: remove old gadgets

---

msm/src/precomputed_srs.rs
poly-commitment/src/kzg.rs

Introduced in fa8e6a38c021d943b7cf073b686743edfc70a27f. Also, making create_and_store_srs_with_path deterministic as before. The test is exactly testing encoding of the SRS for regression.
Reviewer should run:
```
cargo nextest run "precomputed_srs::tests::heavy_test_create_or_check_srs" --all-features --release --nocapture
```

Poly-commitment: revert change regarding trusted-setup

---

kimchi/src/circuits/expr.rs

The trait is only used once, and never used outside. It only consists of a single method. It is also only used by the verifier.

Kimchi/Expr: remove ToPolish trait, used only once

---

kimchi/tests/test_expr.rs

In other words, using the challenge `alpha` doesn't increase the degree. Testing with Berkeley configuration.
Pretty obvious, but when we want to fold expressions in a folding scheme, the challenge must be considered as a variable.

Kimchi/Expr: combining expressions does not increase the degree

---

mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/prime.rs

Both implementations were the same, the only different is how a variable is created.
Challenge and "next row" must still be supported.

MVPoly: move from_expr definition at the trait level

---

o1vm/src/interpreters/mips/constraints.rs

the constraints enforcing that one and only one sels is activated was
\sum_i sel_i instead \sum_i sel_i -1

o1vm/pickles: fix selectors constraints

---

o1vm/src/interpreters/mips/witness.rs
o1vm/src/pickles/main.rs

The instruction counter is the one scaled by the maximum of read/write into memory/register.

o1vm/snapshot: use normalized instruction counter

---

o1vm/src/interpreters/mips/constraints.rs
o1vm/src/interpreters/mips/interpreter.rs
o1vm/src/interpreters/mips/witness.rs
o1vm/src/pickles/main.rs

fixe the remaining failing Mips instr
see : https://github.com/o1-labs/proof-systems/issues/2075
Closes #2075

o1vm/mips: fix failing constraints

---

o1vm/src/lookups.rs

the lookup table id enum does not match the from_u32 function

fixing mismatched look up ids

---

o1vm/src/interpreters/mips/constraints.rs
o1vm/src/interpreters/mips/interpreter.rs
o1vm/src/interpreters/mips/witness.rs
o1vm/src/pickles/main.rs

see : https://github.com/o1-labs/proof-systems/issues/2075
Closes https://github.com/o1-labs/proof-systems/issues/2075

Fix the equality function in the o1vm interpreter

---

kimchi/src/circuits/constraints.rs
kimchi/src/prover.rs

This is the `develop` counterpart of the already merged PR https://github.com/o1-labs/proof-systems/pull/2590. It has been created cherry-picking those commits. The reason that I am creating this branch now is that I have realized that the commit of `proof-systems` inside the `mina` submodule from the `o1js` repo is a `develop` ascendant, and the changes proposed in that old PR targeting `master` were never ported back to `develop`.

[easy] `develop` counterpart of PR#2590

---

o1vm/src/interpreters/mod.rs
o1vm/src/interpreters/riscv32i/mod.rs
o1vm/src/interpreters/riscv32i/registers.rs

Import commits from https://github.com/o1-labs/proof-systems/pull/2727/

o1vm/riscv32i: define registers

---

o1vm/src/interpreters/mips/witness.rs
o1vm/src/lib.rs
o1vm/src/utils.rs

It will be shared by the MIPS and the RISC-V 32i ISA.
Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2727/

o1vm: move memory_size into a top-level utils module

---

o1vm/src/interpreters/riscv32i/constraints.rs
o1vm/src/interpreters/riscv32i/interpreter.rs
o1vm/src/interpreters/riscv32i/mod.rs
o1vm/src/interpreters/riscv32i/witness.rs

Mostly copying from MIPS for now.

o1vm/riscv32i: implement constraints, witness and interpreter env

---

o1vm/src/interpreters/riscv32im/interpreter.rs

Following previous changes when adding M instruction type, as agreed on the pull request.
More documentation will come.
Source: https://msyksphinz-self.github.io/riscv-isadoc/html/rvi.html

[no-op] o1vm/riscv32im: add more documentation reg. instructions

---

o1vm/src/interpreters/riscv32im/interpreter.rs

The immediate interpretation is trickier than the current version. It will be handled in a follow-up PR.
As for the other interpret_* method, we're building a train of PR to have small PR implementing instruction by instruction.

o1vm/riscv32: sketch implementation of SB-type instr interpretation

---

o1vm/src/interpreters/riscv32im/interpreter.rs

It will be easier to implement in follow-up PR

o1vm/riscv32: expand missing instructions for itype

---

o1vm/src/interpreters/mips/tests.rs
o1vm/src/pickles/tests.rs

It was initially in the pickles subdirectory, which does not make sense as it is not strictly related to the Pickles flavor.

o1vm/mips: move regtest reg. number of selectors into MIPS directory

---

o1vm/src/interpreters/riscv32im/mod.rs
o1vm/src/interpreters/riscv32im/tests.rs

In the meantime, set the correct current value.

o1vm/riscv32: introduce tests checking the number of instructions

---

o1vm/src/interpreters/mips/constraints.rs
o1vm/src/interpreters/mips/interpreter.rs
o1vm/src/interpreters/mips/witness.rs

It was only used by `constraints.rs`, not in the witness nor the interpreter. Inline the method.

o1vm/mips: remove inverse_or_zero from interpreter trait

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

The method is splitted in two different methods, comparetively to MIPS.

o1vm/riscv32: remove unused mul_hi_lo_signed

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

Like mul_hi_lo_signed, the method is splitted in two different methods: mul_hi and mul_lo.

o1vm/riscv32: remove unused mul_hi_lo.

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

It will be used to implement MInstruction::Rem in a follow-up PR.

o1vm/riscv32: implement mod_signed

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

As for mul_hi_lo(_signed), the method is splitted.

o1vm/riscv32: remove unused divmod_signed

---

ivc/src/prover.rs
kimchi/src/prover.rs
msm/src/prover.rs
o1vm/src/pickles/prover.rs
poly-commitment/benches/ipa.rs
poly-commitment/src/commitment.rs
poly-commitment/src/ipa.rs
poly-commitment/src/kzg.rs
poly-commitment/src/lib.rs
poly-commitment/src/utils.rs
poly-commitment/tests/batch_15_wires.rs
poly-commitment/tests/commitment.rs
poly-commitment/tests/ipa_commitment.rs
poly-commitment/tests/kzg.rs

This is a **no-op** docs/naming refactoring commit that does the following:
- Moves `combine_polys` to `poly-commitment/src/utils.rs` (there was a comment left by someone that this is a good idea; I agree)
- Improves docs for `combine_polys` and related structs,  like `PolynomialsToCombine`.
- Renames some variables inside `combine_polys`: "omegas" was used which is (1) only used once in the whole repo, and (2) is absolutely not descriptive, since it has no r. Was replaced by 
- Fixed some typos/bad argument names for `hiding/non_hiding` functions, that are actually operating over the integer expressing the number of chunks, not the size of the domain as the previous variable implied.
- Importantly: gets rid of `"xi"`, which was a very rarely used term to call `polyscale`, also known as …

Refactoring: Improve poly-commitment docs & decrease confusing variable names

---

o1vm/src/interpreters/riscv32im/constraints.rs
o1vm/src/interpreters/riscv32im/interpreter.rs
o1vm/src/interpreters/riscv32im/witness.rs

As for mul_hi_lo(_signed), the method is splitted as there are individual instructions for div and mod.

o1vm/riscv32: remove unused divmod

---

.github/workflows/o1vm-ci.yml

As we enforce some GH actions to pass when targeting master, it can make PR stalled and unmergeable. I do not see any options in GH settings at the moment to include these conditions.
cc @shimkiv: this blocks https://github.com/o1-labs/proof-systems/pull/2755 and https://github.com/o1-labs/proof-systems/pull/2761. Do you have a better option?

CI/o1vm: deactivating path dependent execution

---

signer/src/keypair.rs

Can be used by the upstream OpenMina. See https://github.com/o1-labs/proof-systems/pull/2750/files.

Mina-signer: make secret field of KeyPair public

---

o1vm/Cargo.toml

Only for readability when we want to add/search for a dependency

o1vm: reorganize dependencies in alphabetical order [no-op]

---

o1vm/src/interpreters/riscv32im/tests.rs

Checking that the count of the bit index starts at 0, i.e. the number of bits that bitmask returns if `higher_bit - lower_bit`.

o1vm/ricv32im: regression tests for bitmask

---

mvpoly/src/pbt.rs

It does depend on maximum degree given in parameter. The probability is not negligible if 2 is given.
Cherry-picking from https://github.com/o1-labs/proof-systems/pull/2702/commits

MVPoly/PBT: remove a flaky test for multilinearity

---

mvpoly/src/monomials.rs
mvpoly/src/utils.rs
mvpoly/tests/utils.rs

Using filter_map speeds up the computation by avoiding creating a bigger map than expected if a low upper bound is given with large number of indices.
Cherry-picked from https://github.com/o1-labs/proof-systems/pull/2702/

mvpoly: introduce optional param upper bound to compute nested loops

---

book/specifications/README.md
book/src/fundamentals/zkbook_2pc/pap.md
book/src/kimchi/final_check.md

This pull request addresses minor typos and grammar issues in the following documentation files:  
1. **`README.md`**  
- Corrected the phrase "up to date" to "up-to-date" to follow proper hyphenation for compound adjectives.  
2. **`pap.md`**  
- Replaced "a output label" with "an output label" to align with correct article usage before a word starting with a vowel sound.  
3. **`final_check.md`**  
- Updated "left hand side" to "left-hand side" to fix the missing hyphen in the compound adjective.  
- Improved grammatical correctness and consistency.  
- Enhanced the readability of the documentation.  
These changes are minor but contribute to maintaining high-quality documentation standards for the project.  
- `README.md`: Fixed "up to date" → "up-to-date".  
- `pap.md`: Fixed "a …

Fix typos and grammar issues in documentation files

---

hasher/README.md

Fix broken documentation links
- Replaced `https://github.com/o1-labs/cryptography-rfcs/blob/master/mina/001-poseidon-sponge.md`
with `https://o1-labs.github.io/proof-systems/specs/poseidon.html`.

Fix broken documentation link 

---

o1vm/src/interpreters/riscv32im/witness.rs

The decoding is more verbose on purpose, as I would like to have a regression test checking an exception is raised. Unit tests checking the decoding are coming, mimicking the previous ones.

o1vm/riscv32im: decode M instruction type

---

arrabbiata/README.md

The correct spelling of the word is "arrabbiata," as it refers to the Italian term for a spicy tomato-based pasta sauce. The project uses "Arrabbiata" in the title, but the binary name is incorrectly spelled as "arrabiata." Maintaining consistent spelling aligns with the title and avoids confusion, ensuring clarity and professionalism in the project documentation and implementation.

typo README.md

---

arrabbiata/src/columns.rs
arrabbiata/src/main.rs
mvpoly/src/lib.rs
mvpoly/src/monomials.rs
mvpoly/src/prime.rs
mvpoly/tests/monomials.rs

This pull request prepares the constraints to compute the cross-terms after the different columns and arguments have been computed. Challenges must be treated as a variable, and will be in a future PR.
Previous attempt: https://github.com/o1-labs/proof-systems/pull/2695

Arrabiata: prepare constraints for cross-terms computation

---

mvpoly/src/monomials.rs

The degree is in the type, but we suppose the user will be careful when using the library, which is a bad assumption.
It has already been discussed to remove the type dependency. Let's do it later.

MVPoly: additional checks reg. multiplication of polynomials

---

book/src/SUMMARY.md
book/src/plonk/zkpm.md
o1vm/README-optimism.md

Corrected `Functionnalities` to `Functionalities`
Corrected `permuation` to `permutation`
Corrected `clock is open to date` to `clock is up to date`

fix: typos in documentation files

---

o1vm/src/interpreters/mips/interpreter.rs

When bitlength = 0 and when compiling with `-Coverflow-checks=y`, the runtime alerts us that there is an overflow while shifting. Lifting the type to u64 and cast the value as u32 when the computation is done.
See riscv32im counterparty in https://github.com/o1-labs/proof-systems/pull/2888

o1vm/mips: use u64 to avoid overflow when bitlength is 0

---

o1vm/src/interpreters/riscv32im/interpreter.rs

It is mostly to simplify formal verification tools generating Coq/Lean from Rust code

o1vm/riscv32im: being strict on scope and unsafe def

---

o1vm/src/interpreters/riscv32im/mod.rs

Try with 38, and fibonacci will fail.
It might need to be increased in the future if you see that the current testsuite doesn't cover the whole instruction set.

o1vm/riscv32im: decrease the number of required columns

---

o1vm/src/interpreters/riscv32im/tests.rs

To investigate later under-constrained instructions. Lookups still need to be added.

o1vm/riscv32im: start checking the nb of csts per instruction

---

.gitignore
Makefile

Import all MIPS programs from Optimism, and tweak it to make it compatible with our ELF loader. Requested by @martyall to have more small test programs for the o1vm MIPS edition.

Makefile: target to import all programs from Optimism

---

o1vm/src/legacy/main.rs
o1vm/src/pickles/main.rs
o1vm/src/preimage_oracle.rs
o1vm/src/test_preimage_read.rs

Not every mips program requires this, but we currently throw an exception if it isn't provided

Optional PreImageOracle

---

poseidon/src/lib.rs
poseidon/tests/poseidon_tests.rs

See commit messages.
This work is part of the sponge management currently being implemented in Arrabbiata.

Mina-poseidon: regression tests + top-level documentation

---

arrabbiata/README.md
arrabbiata/src/interpreter.rs
arrabbiata/src/lib.rs
arrabbiata/src/main.rs
arrabbiata/src/witness.rs
arrabbiata/tests/cli.rs
arrabbiata/tests/witness.rs

The steps to finish a first PoC of Arrabbiata are listed in this file `arrabbiata/main.rs`. The plan for the next weeks is to make a list of consecutive PR implementing the different FIXME. At the end of this list, a user should be able to execute `main.rs` with a pre-defined list of zkApp written in Rust using the "interpreter" interface.
The diagram might not be totally correct, nor complete. It will be edited step by step, while the code is being written and tested.
PR in progress are:
- permutation argument (https://github.com/o1-labs/proof-systems/pull/2593)
- Fiat-Shamir (https://github.com/o1-labs/proof-systems/pull/2720 + https://github.com/o1-labs/proof-systems/pull/2686)
This PR only makes the binary `arrabbiata` (defined in `main.rs`) executable and ending with a success …

CI/Arrabbiata: make the main file running for continuous testing

---

.github/workflows/ci.yml

We do only care for one, and it is the one running in gh-page.yml
Also, getting a compiler error from Rust 1.75, might be related to https://github.com/rust-lang/rust/issues/119529

CI: stop generating doc for each Rust toolchain

---

.github/workflows/ci.yml

Previous versions will be dropped step by step. Upgrading step by step to avoid big diffs.

CI: adding Rust 1.75

---

.github/workflows/ci.yml
kimchi/src/circuits/polynomials/foreign_field_add/witness.rs
kimchi/src/tests/foreign_field_add.rs
msm/src/prover.rs
msm/src/verifier.rs
mvpoly/src/pbt.rs
poly-commitment/src/kzg.rs
poly-commitment/tests/kzg.rs

I'm updating step by step to also see which packages must be updated.

CI: add Rust 1.76

---

.github/workflows/ci.yml
kimchi/src/precomputed_srs.rs
msm/src/precomputed_srs.rs

Previous versions will be dropped step by step. Upgrading step by step to avoid big diffs.

Support Rust 1.77

---

.github/workflows/ci.yml

Mina does use 1.72, therefore we have to support at minima 1.72

CI: dropping support for Rust 1.71

---

o1vm/src/interpreters/mips/witness.rs

This PR fixes the bug introduced in https://github.com/o1-labs/proof-systems/pull/2926, which is then 'fixed' incorrectly [here](https://github.com/o1-labs/proof-systems/pull/2945/files#diff-28425787191170e725968d01849f8039700326796697f8c9f5180c3ecfe8f1bfL11).

Stop generating new scratch state for halt addresses

---

ivc/src/expr_eval.rs
ivc/src/ivc/columns.rs
ivc/src/plonkish_lang.rs
ivc/src/poseidon_55_0_7_3_2/columns.rs
ivc/src/poseidon_55_0_7_3_7/columns.rs
ivc/src/poseidon_8_56_5_3_2/columns.rs
ivc/src/prover.rs
ivc/src/verifier.rs
ivc/tests/folding_ivc.rs
ivc/tests/simple.rs
msm/src/circuit_design/constraints.rs
msm/src/circuit_design/witness.rs
msm/src/column_env.rs
msm/src/columns.rs
msm/src/expr.rs
msm/src/fec/columns.rs
msm/src/ffa/columns.rs
msm/src/logup.rs
msm/src/proof.rs
msm/src/serialization/column.rs
msm/src/test/test_circuit/columns.rs
o1vm/src/interpreters/keccak/column.rs
o1vm/src/interpreters/mips/column.rs
o1vm/src/lib.rs
o1vm/src/pickles/column_env.rs
o1vm/src/pickles/verifier.rs

This PR adds a parameter to `Column`, letting us use saner types in place of `usize` where appropriate. This PR is a no-op, retaining the use of `usize` everywhere for now.

Parameterise `Column`

---

ivc/src/ivc/columns.rs
ivc/src/ivc/helpers.rs
ivc/src/ivc/mod.rs
ivc/src/poseidon_55_0_7_3_2/columns.rs
ivc/src/poseidon_55_0_7_3_2/mod.rs
ivc/src/poseidon_55_0_7_3_7/columns.rs
ivc/src/poseidon_55_0_7_3_7/mod.rs
ivc/src/poseidon_8_56_5_3_2/columns.rs
ivc/src/poseidon_8_56_5_3_2/mod.rs
ivc/tests/simple.rs
msm/src/circuit_design/capabilities.rs
msm/src/circuit_design/composition.rs
msm/src/circuit_design/constraints.rs
msm/src/circuit_design/witness.rs
msm/src/columns.rs
msm/src/fec/columns.rs
msm/src/fec/mod.rs
msm/src/ffa/columns.rs
msm/src/ffa/mod.rs
msm/src/serialization/column.rs
msm/src/serialization/interpreter.rs
msm/src/serialization/mod.rs
msm/src/test/test_circuit/columns.rs
o1vm/src/interpreters/keccak/column.rs
o1vm/src/interpreters/mips/column.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/2948, adding a type parameter to `ColumnIndexer` corresponding to the parameter for `Column`. This retains the `usize` type everywhere for now.

Parameterise `ColumnIndexer`

---

o1vm/src/interpreters/keccak/column.rs
o1vm/src/interpreters/mips/column.rs
o1vm/src/lib.rs
o1vm/src/pickles/column_env.rs
o1vm/src/pickles/tests.rs
o1vm/src/pickles/verifier.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/2949, using the new type parameter in `Column` to add a structured type in place of `usize` for the `Relation` kind.

Use a sane type for Relation in the MIPS constraints

---

o1vm/src/interpreters/mips/tests_helpers.rs
o1vm/src/interpreters/mips/witness.rs
o1vm/src/lookups.rs
o1vm/tests/test_mips_elf.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/2950. This PR adds tracking for fixed-table multiplicities in the witness generation. We can use these to inject them at the end of execution, for use in the lookup protocol. This way, we can use the delayed lookup argument for everything.
The indexing code is bad; this is mostly derived from existing code.

Add multiplicity tracking for lookups

---

o1vm/src/interpreters/mips/tests_helpers.rs
o1vm/src/interpreters/mips/witness.rs
o1vm/src/pickles/column_env.rs
o1vm/src/pickles/main.rs
o1vm/src/pickles/proof.rs
o1vm/src/pickles/prover.rs
o1vm/src/pickles/tests.rs
o1vm/src/pickles/verifier.rs

This PR builds upon https://github.com/o1-labs/proof-systems/pull/2943. This propagates the values involved with lookups as witness columns for the prover.
This is a cleaned-up alternative to https://github.com/o1-labs/proof-systems/pull/2946.

Track lookup values in interpreter and proof

---

o1vm/src/cli/cannon.rs
o1vm/src/pickles/main.rs

This has been floating around for a while but is extremely useful to save time on loading the SRS

added srs_cache cli arg

---

kimchi/src/circuits/argument.rs
mvpoly/src/utils.rs

This pull request fixes spelling issues in the `argument.rs` and `utils.rs` files. 
- Fixed "a argument" → "an argument" in `argument.rs`.
- Corrected "an cache" → "a cache" in `utils.rs`.

Fix spelling

---

.github/workflows/saffron.yml
saffron/.gitignore
saffron/test-encoding.sh

Add CI for saffron e2e test (bash scripts using the CLI)

Saffron e2e tests in CI

---

Cargo.lock
saffron/Cargo.toml
saffron/src/main.rs
saffron/src/serialization.rs

I'm adding the tracing library in order to uniformly handle the combo of instrumenting and logging like you find [here](https://github.com/o1-labs/proof-systems/blob/c9ecf8ce19b5197224696f2b599b8041af47a1df/data-storage/src/main.rs#L59-L69)
Here is an example output from running a test locally:
```
2025-01-22T19:32:19.946Z DEBUG saffron: Encoding file input_file="/home/martyall/tmp/bigfile.txt"
2025-01-22T19:32:20.925Z  INFO encode: saffron::serialization: close time.busy=829ms time.idle=5.01µs
2025-01-22T19:32:21.089Z DEBUG saffron: Writing encoded blob to file output_file="/home/martyall/tmp/bigfile.bin"
2025-01-22T19:32:21.543Z DEBUG saffron: Decoding file input_file="/home/martyall/tmp/bigfile.bin"
2025-01-22T19:32:23.293Z  INFO decode: saffron::serialization: close time.busy=1.35s …
```

add tracing to saffron

---

.github/workflows/saffron.yml
Cargo.lock
saffron/Cargo.toml
saffron/src/blob.rs
saffron/src/commitment.rs
saffron/src/env.rs
saffron/src/lib.rs
saffron/src/main.rs
saffron/src/utils.rs

Collects some improvements to running tests / CI that came up while working on #2968 , felt like it was better to pull them out and apply them in a separate PR
- Add SRS caching in CI which reduces the e2e test time from [~3 min](https://github.com/o1-labs/proof-systems/actions/runs/12995728856/job/36243038553?pr=2967) to [20 seconds](https://github.com/o1-labs/proof-systems/actions/runs/12998174831/job/36250749999?pr=2970) :exploding_head:
- Refine the random data generation for the blob unit tests
- add console logging subscriber to tests (still controlled by `RUST_LOG` env var)

Saffron CI Speedups and Cleanups

---

saffron/Cargo.toml
saffron/src/blob.rs
saffron/src/utils.rs

- move the `blob_test_utils` module to `utils.rs` and use as standard way for all data generation. Renamed the generator from `BlobData` to `UserData` to reflect that it has nothing to do with blobs apriori
- reworked @marcbeunardeau88 's test to generate and test multiple queries for every user data generation round

[saffron] Property based test for query

---

arrabbiata/src/witness.rs

Using Fq/Fp required to add more type constraints when working on https://github.com/o1-labs/proof-systems/pull/2938/. Therefore, I suggest to always use E1/E2::ScalarField.

Use E1/E2::ScalarField instead of Fp/Fq

---

arrabbiata/src/curve.rs
arrabbiata/src/interpreter.rs
arrabbiata/src/main.rs
arrabbiata/src/witness.rs

The next one will be https://github.com/o1-labs/proof-systems/pull/2982

Arrabbiata: prepare the primitives to absorb the state after committing to it

---

Cargo.lock
saffron/Cargo.toml
saffron/src/utils.rs

@marcbeunardeau88 did the initial index arithmetic to make the query interface, this PR just cleans up that work. I added additional tests to cover edge cases and attempted to make it more idiomatic (in an opinionated fashion).
The commits are atomic, individual diffs should be clear
- add an error type for malformed queries and force construction of well formed queries through smart constructor `into_query_field`. Added tests. https://github.com/o1-labs/proof-systems/commit/416ed93c800bb52046061435ba8ef5c83d6cc0e5
- remove hard coded use of values like `31` (https://github.com/o1-labs/proof-systems/commit/482964f0e30ba6c01c7e102aa9f80c6d768c8c0b, https://github.com/o1-labs/proof-systems/commit/ffa98c747a37ca628ff358fe6dc5408ca261fc80) and `2 ^ 16` …

[saffron] cleanup query

---

Cargo.lock
saffron/Cargo.toml
saffron/src/blob.rs
saffron/src/lib.rs
saffron/src/proof.rs

- Add "proof of storage" (i.e. the storage provider possesses the data) and verification
- Add tests
cli + e2e tests will be coming in https://github.com/o1-labs/proof-systems/pull/2979
Example test output excerpt:
```
> RUST_LOG=debug SRS_FILEPATH=../srs/test_vesta.srs cargo test -p saffron test_storage_prove_verify --release -- --nocapture
2025-01-28T09:10:21.815Z DEBUG commit_to_field_elems: saffron::commitment: close time.busy=1.34s time.idle=4.11µs
2025-01-28T09:10:21.817Z DEBUG fold_commitments: saffron::commitment: close time.busy=1.13ms time.idle=2.60µs
2025-01-28T09:10:23.463Z DEBUG encode:commit_to_blob_data: saffron::blob: close time.busy=1.41s time.idle=3.93µs
2025-01-28T09:10:23.463Z DEBUG encode: saffron::blob: Encoded 24.11 MB into 12 polynomials
2025-01-28T09:10:23.465Z …
```

Proof of Storage

---

saffron/src/blob.rs
saffron/src/cli.rs
saffron/src/main.rs
saffron/src/proof.rs
saffron/src/utils.rs
saffron/test-encoding.sh

This PR adds a cli command `storage-proof` to generate proofs that the provider has the whole data. This is meant to work with #2979 where the `verify-storage-proof` command is added
- add command `storage-proof` to cli to generate storage proof backed by core code from #2971 
- added `HexString` and `StorageProof` newtypes to unify/simplify reading/outputting binary data with cli commands
- added command as part of e2e script flow

Add storage-proof command to cli and e2e 

---

arrabbiata/tests/constraints.rs

Useful for cross-terms computation

Arrabbiata/test: check transformation into sparse mvpoly

---

saffron/Cargo.toml
saffron/og-flow/main.rs

Bring in [original demo script](https://github.com/o1-labs/proof-systems/blob/feature/test-data-storage-commitments/data-storage/src/main.rs) and replace the random data generation with reading from a file. 
Only meaningful work is https://github.com/o1-labs/proof-systems/pull/2990/commits/2de0a46330f88ed289911228271fba881329c80f. 
example invocation:
```
cargo run --bin saffron-og-flow --release -- saffron/fixtures/lorem.txt
```
NOTE: I needed to modify the original demo before I could work on it -- it used older versions of `arkworks` and `proof-systems`. You can view that diff locally via
```
git diff feature/test-data-storage-commitments:data-storage/src/main.rs  82c0d4a:saffron/og-flow/main.rs
```

Added OG flow as binary

---

poseidon/tests/poseidon_tests.rs

Checking that the block cipher is executed when the rate is reached.

Poseidon/tests: squeeze/check state

---

saffron/e2e-test.sh
saffron/src/blob.rs
saffron/src/cli.rs
saffron/src/commitment.rs
saffron/src/main.rs
saffron/src/proof.rs

The user and storage provider need to communicate about a common commitment type. When working on #3004 I realized that the user will also need to persist these commitments in order to apply updates to them when updating their data. It makes #3004 cleaner if I do this first
- Add `Commitment` type ([5b99888](https://github.com/o1-labs/proof-systems/pull/3005/commits/5b99888600060c9734f7f4a988bb1b932f84c8c1)) and use it in the blob ([3940789](https://github.com/o1-labs/proof-systems/pull/3005/commits/394078986cf203f2a308d4a2828df4d81bab4339))
- Add a `-o [output-file]` arg to the `compute-commitment` CLI command to write the `Commitment` value to disk https://github.com/o1-labs/proof-systems/pull/3005/commits/9bb1b56bcaf812f6981fdb5b0fa03eda6e8126ec
- a few trivial cleanups
- use common …

[saffron] add commitment type shared between user and provider

---

arrabbiata/src/interpreter.rs

The code follows in a future PR. At the moment, the generation of the cross-terms + handling the accumulation scheme require to rework a bit the witness environment. For this reason, first, documentation is added to agree on the structure + the naming convention.

Arrabbiata: add a workflow reg. "two steps" challenges verification

---

saffron/src/diff.rs
saffron/src/lib.rs
saffron/src/utils.rs

This PR builds on #3005 
While working on #3004 I did not approach the `Diff` type carefully enough. This PR is meant to slow things down and make sure we have the spec fulfilled before implementing the update functionality that uses it. 
- clearly define the `Diff` type and it's create method using [sparse representation](https://github.com/o1-labs/proof-systems/pull/3004#discussion_r1946443619) suggested by @dannywillems.
- clearly define `Diff` spec. The assumptions are:
1. You are allowed to construct a diff if the number of polynomials (chunks) required is less than or equal to the original: `test_allow_legal_updates`
2. You are not allowed to construct a diff if the new number of chunks is strictly more -- in this case we should throw an error: `test_cannot_construct_bad_diff`
- add …

[saffron] Add Diff type , methods, and tests

---

saffron/e2e-test.sh

as requested by @dannywillems [here](https://github.com/o1-labs/proof-systems/pull/3005#pullrequestreview-2604185238)
- use underscore as separator 
- fix `.txt` extension for `*_decoded` file
- [justify](https://github.com/o1-labs/proof-systems/pull/3005/files#r1948180600) usage of `tee`
You can test by removing the `rm` cleanup statement at the end of the test and check the git status, e.g.
```
Untracked files:
(use "git add <file>..." to include in what will be committed)
saffron/fixtures/lorem.bin
saffron/fixtures/lorem_commitment.bin
saffron/fixtures/lorem_decoded.txt
```

[saffron] standardize e2e generated file names

---

saffron/src/blob.rs
saffron/src/commitment.rs
saffron/src/diff.rs
saffron/src/proof.rs

- use `chunks` as field name for consistency https://github.com/o1-labs/proof-systems/pull/3009/commits/b83f4e2e7f0215531232994922ed9f15bc9a3068
- add update method for `Commitment` type https://github.com/o1-labs/proof-systems/pull/3009/commits/40851bd8cac1449641b988e7580ba76038f79116
- add update method for `FieldBlob` type with tests https://github.com/o1-labs/proof-systems/pull/3009/commits/dca3c7fb2a212e1c8161b8ee1b2dad3ee56da88a
We discussed moving away from using a CLI to drive the actions e2e test and instead using a client/server implementation with flows written in rust. Instead of implementing the e2e for this flow (which is complicated), I will leave it at the prop tests

[saffron] Add update methods with tests

---

saffron/src/blob.rs

Simple fix for this https://github.com/o1-labs/proof-systems/actions/runs/13273640255/job/37058646902?pr=2969
The problem comes from the time spent computing commitments for test iterations generating "large" user data. Using the `DataSize::Medium` and reducing to 10 test cases still gives good coverage. `Medium` allows for larger than 1 chunk which is the most important thing here. On my machine this went from `1min` to `11s`, CI went back to the normal `60min` range.
While working on this I realized that while correct, the test was written awkwardly. I reordered the commitment checks to more closely match the lifecycle of the update

[saffron] less punishing ci

---

.github/workflows/ci.yml
.github/workflows/saffron.yml
Makefile

This _actually_ fixes the problem that #3023 failed to address. 
- Run all saffron unit tests in their own workflow
- Stop running saffron in the general CI workflow
The tests themselves weren't even the problem -- there were 2 other major factors:
- The code coverage job was building everything with instrumentation flags that were causing something like a 100x slowdown :exploding_head: 
- Since the tests were being run without the SRS cache, they were spending a lot of time computing one (likely once per test module)

Run Saffron in it's own workflow, restore OG CI for core lib only

---

arrabbiata/src/columns.rs
arrabbiata/src/witness.rs

The goal is to be more explicit on the challenges the protocol defines. It will be easier in the code to refer to a particular name instead of an index. Also, we fix the number of challenges, hoping the structure will be linear in memory and we can enjoy the optimsiation of the CPU cache.

Arrabbiata: define Challenges structure

---

arrabbiata/src/main.rs
arrabbiata/src/witness.rs

The reviewer is always encouraged to run:
```
cargo nextest run "test_arrabbiata_binary" --release --nocapture -p arrabbiata
```
that starts the example file. This is also executed in the CI in `tests/cli.rs`.

Arrabbiata: accumulate program state

---

arrabbiata/src/challenge.rs
arrabbiata/src/main.rs
arrabbiata/src/witness.rs

Applying comments from https://github.com/o1-labs/proof-systems/pull/3024#discussion_r1954160085

Arrabbiata: use "combiner" instead of "randomiser" for challenges

---

arrabbiata/src/witness.rs

It was initially added as not all the types were used in the structure definition.
It is the case now.

Arrabbiata: remove marker in Witness structure

---

mvpoly/src/monomials.rs
mvpoly/tests/monomials.rs

Can be useful if we use with selectors for instance, i.e. `q * P(X1, ..., Xn)`.

MVPoly: speed up cross-terms computation when multiplicands are zero

---

arrabbiata/src/main.rs

This will be used in the near future when we will change the Poseidon gadget to the new one, without the fifteen public inputs.
It will be updated over time to detect any change in the verifier circuit.

Arrabbiata: adding a regression test in case circuit changes

---

arrabbiata/src/column.rs
arrabbiata/src/constraint.rs
arrabbiata/src/interpreter.rs
arrabbiata/src/lib.rs
arrabbiata/src/witness.rs
arrabbiata/tests/cli.rs
arrabbiata/tests/constraint.rs
arrabbiata/tests/witness.rs

Following https://github.com/o1-labs/proof-systems/issues/3050

Arrabbiata: new poseidon gadget

---

arrabbiata/src/column.rs
arrabbiata/src/constraint.rs
arrabbiata/src/interpreter.rs
arrabbiata/src/witness.rs
arrabbiata/tests/constraint.rs
arrabbiata/tests/witness.rs

This gadget, with `PoseidonPermutation(usize)`, aims to replace the gadget `Poseidon`, as suggested in #3050.
In a future PR, the gadget `Poseidon` is going to be removed, and the implementation of the methods `fetch_values_to_absorb` and `round_constants` are going to be replaced by the newly added methods.
The gadget is essentially two additions + use of the permutation argument to fetch the values. These two constraints could be provided generically for the whole circuit, but we leave this for future works.
An important note is that the gadget supposes that the permutation argument is implemented, through the use of `load_poseidon_state`, `save_poseidon_state` and `fetch_value_to_absorb_in_sponge`. This will come later.

Arrabbiata: implement gadget PoseidonSpongeAbsorb

---

kimchi/snarky-deriver/src/lib.rs

See related bot PR https://github.com/o1-labs/proof-systems/pull/3088

Snarky/doc: remove link to crates kimchi as it does not exist

---

.github/workflows/gh-page.yml

Updating to nightly will be done when 'time' will have been updated.
Reverting the version bump up introduced in this PR: https://github.com/o1-labs/proof-systems/pull/3068
'time' is updated in https://github.com/o1-labs/proof-systems/pull/3089, but the PR is on hold for now as we must first bump up Mina with the latest proof-systems, c.f. https://github.com/MinaProtocol/mina/pull/16782

CI/gh-page: reverting used Rust toolchailchain to 1.72

---

hasher/src/lib.rs
hasher/src/poseidon.rs

Relying on [core](https://github.com/rust-lang/rust/tree/master/library/core) instead of [std](https://github.com/rust-lang/rust/tree/master/library/std) decreases the number of dependencies, and make it more portable through different platforms.

hasher: use core instead of std

---

kimchi/src/circuits/polynomials/permutation.rs

The commit was reverted here https://github.com/o1-labs/proof-systems/pull/3105 due to the indices bug, which is fixed in this PR.
`mina` PR: https://github.com/MinaProtocol/mina/pull/16812

Reintroduce "Parallelise perm_aggreg" w/ bugfix

---

Cargo.toml

Note that it will also be removed in MIna. Also, it was a dependency that was causing some issues when upgrading Rust because of the strict version requirements we were imposing on the Mina side, for no apparent reasons, as unused.

Deps: remove unused proc-macros2

---

curves/tests/pasta_curves.rs
folding/src/checker.rs
folding/src/eval_leaf.rs
folding/src/expressions.rs
folding/src/lib.rs
folding/src/quadraticization.rs
folding/src/standard_config.rs
ivc/src/expr_eval.rs
ivc/src/plonkish_lang.rs
ivc/src/poseidon_55_0_7_3_2/interpreter.rs
ivc/src/poseidon_55_0_7_3_2/mod.rs
ivc/src/poseidon_55_0_7_3_7/interpreter.rs
ivc/src/poseidon_55_0_7_3_7/mod.rs
ivc/src/poseidon_8_56_5_3_2/bn254/mod.rs
ivc/src/poseidon_8_56_5_3_2/interpreter.rs
ivc/src/poseidon_8_56_5_3_2/mod.rs
ivc/src/poseidon_params_55_0_7_3.rs
ivc/src/prover.rs
ivc/src/verifier.rs
ivc/tests/simple.rs

It is only a first step through having a no_std support. It is not the end-goal of this PR, but only a support in case we want to have it in the future.

folding/ivc/curves: use core instead of std

---

Makefile

See commit messages.
The reviewer is encouraged to run
```
make setup-wasm-toolchain
```
to verify that it works on their OS and architecture, if supported.
It is initially part of https://github.com/o1-labs/proof-systems/pull/3139/, but !3139 is postponed until the build process is fixed.

Makefile: split target setup and improve architecture and OS support for wasm toolchain

---

.github/workflows/ci-nightly.yml
plonk-wasm/src/lib.rs

the nightly job was running `make clean` before running the tests, which deleted all the generated mips bin files. This PR fixes this problem.

fix nightly ci

---

Makefile
plonk-wasm/Cargo.toml

To be used with https://github.com/MinaProtocol/mina/pull/16843.
The option `-C --link-arg=FLAGS` is passed to the compiler `rustc`. In particular, the value `FLAGS` is going to be passed to the linker.
The option `--check-features`, trackable in [the
llm-project/lld](https://github.com/llvm/llvm-project/blob/main/lld/wasm/Options.td#L265) has the following purpose:
```
defm check_features: BB<"check-features",
"Check feature compatibility of linked objects (default)",
"Ignore feature compatibility of linked objects">;
```
In particular, `wasm-ld`, the linker driver for WebAssembly and used in our case, is based [on this codebase](https://lld.llvm.org/WebAssembly.html), and share the flag.
The cancelling flag is `--no-check-features`, currently used in Mina when building the WebAssembly …

plonk-wasm: remove --no-check-features flag

---

.github/workflows/ci.yml
plonk-wasm/src/arkworks/pasta_fp.rs
plonk-wasm/src/arkworks/pasta_fq.rs
plonk-wasm/src/lib.rs
plonk-wasm/src/oracles.rs
plonk-wasm/src/pasta_fp_plonk_index.rs
plonk-wasm/src/pasta_fq_plonk_index.rs
plonk-wasm/src/plonk_proof.rs
plonk-wasm/src/plonk_verifier_index.rs
plonk-wasm/src/srs.rs

Built on top of https://github.com/o1-labs/proof-systems/pull/3144
This patch fixes the Makefile target `lint` when the crate `plonk_wasm` is included.
From this patch, `make lint` will always be run on all the crates defined in the workspace.
The patch does not aim to modify any semantics of plonk-wasm.
The reviewer can reproduce the set of commits by applying the recommendation of the output of `make lint` on each file.

plonk-wasm: appease Clippy

---

saffron/e2e-test.sh
saffron/og-flow/main.rs
saffron/src/blob.rs
saffron/src/cli.rs
saffron/src/commitment.rs
saffron/src/diff.rs
saffron/src/lib.rs
saffron/src/main.rs
saffron/src/storage_proof.rs
saffron/src/utils.rs

This PR attempts to bring the current version of the saffron closer to the demo. It makes a lot of changes that are not easily decoupblable from each other, I'll try to summarise them later.
* Remove group generics from half of the file, use `Curve = Vesta, ScalarField = Fp` etc defined in `saffron::lib` now.
* Justification: we will use only one curve for these, so using generics adds a lot of visual noise. Especially with MSMs since we have to write `<G as AffineCurve>::ScalarField` everywhere.
* Rewrite `diff` module: now the diff contains not the delta but the final value. Might be a good idea to rename to `WriteReq`.
* Justification: In 99% cases wire types will contain write requests with new values, not the deltas. The deltas are computed by storage provider. 
* Rewrite storage …

Saffron: Merge with Demo

---

saffron/src/blob.rs

Fixes cargo docs complaining, which led to the github pages docs CI failure: https://github.com/o1-labs/proof-systems/actions/runs/14340847614/job/40199432360

Fix saffron blob.rs cargo doc warnings (microPR)

---

plonk-wasm/src/lib.rs

This is a no-op, and aims to simply appease Clippy. This commit does not aim to modify the semantics.
- https://github.com/o1-labs/o1js/pull/2140
- https://github.com/o1-labs/o1js-bindings/pull/359
- https://github.com/o1-labs/proof-systems/pull/3161
- https://github.com/MinaProtocol/mina/pull/16891

plonk-wasm/lib: add unsafe keyword and add doc accordingly

---

kimchi-stubs/Cargo.toml

On MacOS arm64, ocaml-rs causes some build issues.

kimchi-stubs: stop generating dylib

---

Cargo.toml
plonk-wasm/Cargo.toml
plonk-wasm/config.toml

First commit fixes this warning:
```
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/volhovm/code/proof-systems/plonk-wasm/Cargo.toml
workspace: /home/volhovm/code/proof-systems/Cargo.toml
```
Second commit fixes this warning (these options are ignored unless they're in `.cargo/config.toml`: https://doc.rust-lang.org/cargo/reference/config.html):
```
warning: /home/volhovm/code/proof-systems/plonk-wasm/Cargo.toml: unused manifest key: build
warning: /home/volhovm/code/proof-systems/plonk-wasm/Cargo.toml: unused manifest key: target.wasm32-unknown-unknown.rustflags
```

Fix plonk-wasm compilation warnings [easy]

---

kimchi/src/circuits/expr.rs
saffron/og-flow/main.rs
saffron/src/commitment.rs
saffron/src/storage_proof.rs
saffron/src/utils.rs
utils/src/field_helpers.rs

This PR unifies scalar’s powers generation through the repository, only using `utils::field_helpers::pows` and removing other implementations.
It also unify the commitments aggregation in Saffron by adding a new function in saffron/utils.

Cleanup & factorize `pows`-related code

---

Cargo.lock
Cargo.toml

- https://github.com/o1-labs/proof-systems/pull/3147
- https://github.com/MinaProtocol/mina/pull/16860
- https://github.com/o1-labs/o1js-bindings/pull/354
- https://github.com/o1-labs/o1js/pull/2131

Bump up wasm-bindgen to  0.2.89

---

.github/workflows/ci.yml
plonk-wasm/src/pasta_fp_plonk_index.rs
plonk-wasm/src/pasta_fq_plonk_index.rs
plonk-wasm/src/plonk_proof.rs
saffron/src/read_proof.rs

This fixes some clippy warnings:
- Fixes saffron related warnings. Also un-excludes saffron from CI so that these checks are done before merging.
- Suppresses plonk-wasm deprication warnings (https://github.com/o1-labs/proof-systems/pull/3163). Un-excludes plonk-wasm from CI, same reasoning.

Fix clippy & suppress plonk-wasm deprecated clippy warnings

---

Cargo.lock
saffron/Cargo.toml
saffron/benches/read_proof_bench.rs

This will be used to compare with the upcoming optimization of read proofs.

Saffron/benches: add bench for read proof

---

.cargo/config.toml
.github/workflows/benches-mina-prover.yml
.github/workflows/wasm.yml
Cargo.lock
Cargo.toml
Makefile
xtask/Cargo.toml
xtask/src/main.rs

Now cargo manages the wasm-pack dependency instead of relying on
whatever is in your shell. This allows you to have one global install of
wasm-pack that's completely different from the `plonk-wasm` dependency

CI: Use xtask pattern for wasm-pack

---

.github/workflows/benches-mina-prover.yml

The CI error in some PRs (e.g. here https://github.com/o1-labs/proof-systems/actions/runs/14995579037/job/42128868995) was present because the script assumed `target/` directory present in the repo. Which is absent until you build it for the first time. Before it was present I guess due to build caching. 
This PR removes the requirement.

Fix bench mina circuit CI job: don't require target/ to be present

---

Cargo.lock
poly-commitment/Cargo.toml
poly-commitment/benches/ipa.rs

Adds the subj benchmark. I wanted to see where exactly the tradeoff is located in terms of using `commit_non_hiding(evals.interpolate())` vs `commit_evaluations(&evals)`.
Results below.

Add a benchmark comparing IPA commitment w/ and w/o Lagrange

---

saffron/Cargo.toml
saffron/benches/folding_bench.rs
saffron/src/folding.rs

Adds benchmarks for folding: interactive prover/verifier + plonkish prover/verifier for the relaxed statement.
Bench results on my machine (may be noisy):
```
folding_ip/folding_prover
time:   [37.932 ms 38.138 ms 38.363 ms]
folding_ip/folding_verifier
time:   [499.56 µs 500.24 µs 500.96 µs]
folding_ip/prover_relaxed
time:   [732.84 ms 736.66 ms 742.93 ms]
folding_ip/verifier_relaxed
time:   [80.869 ms 81.115 ms 81.389 ms]
```
where the first two are aggregation functions, and the last two are plonking proof prover/verifier.

PU: Add benches for folding

---

.cargo/config.toml

I don't think the alias actually causes any problems and is convenient for local development. We just can't use the alias in the makefile

Revert "Cargo: remove config.toml defining alias"

---

Cargo.toml

Motivation:
Proof-systems needs to co-exist with other rust libraries. Pinning the version of serde_json (a very common library) to a specific (older) version is very restrictive. Requesting it be unpinned and replaced with caret.

Deps: Removing serde_json exact version pin, replaced with semver caret.

---

saffron/benches/folding_bench.rs
saffron/benches/read_proof_bench.rs
saffron/src/blob.rs
saffron/src/folding.rs
saffron/src/read_proof.rs
saffron/src/storage.rs
saffron/src/storage_proof.rs

Quite a few tests and benchmarks were using lazy SRS generated on-demand during compile-time. For tests and benchmarks we already had a solution before -- namely, `poly-commitment::precomputed_srs` that reads the pre-generated SRS which already has Lagrange bases pre-generated. This PR uses the latter.
If people like lazy static variables we can use them, but I'd be in favour of using pre-generated SRS embedded into tests, rather than allowing to run tests with an external SRS. I see no value in it and it creates diversity in approaches to test SRSs. I'd like to merge this (to avoid having 2 concurrent approaches), but I'm happy to improve our main approach.

PU: Remove Lazy SRS, use test SRS instead

---

kimchi/Cargo.toml
kimchi/src/tests/framework.rs
kimchi/src/tests/lazy_mode.rs
utils/Cargo.toml
utils/src/lazy_cache.rs

This PR adds a custom feature in `kimchi` and `o1-utils` called `diagnostics` that should be passed whenever we want to include the dependencies `tikv-jemalloc-ctl` and `tikv-jemallocator`. That means, tests using `jemalloc` to measure memory allocation will only perform the memory measurements if both run with `--features diagnostics` and the target architecture is not `wasm32` (this last condition was added in https://github.com/o1-labs/proof-systems/pull/3079 to pass CI). 
The reason I am doing this is that tikv packages seem to have issues with the custom build target `riscv32im-succinct-zkvm-elf` used in SP1. By adding an optional cargo feature we can still run those tests for internal benchmarking while preserving compatibility with external teams without needing them to change …

Add custom feature to enable jemalloc dependencies

---

.github/workflows/benches-mina-prover-set-baseline.yml
kimchi-stubs/src/pasta_fp_plonk_proof.rs
kimchi-stubs/src/pasta_fq_plonk_proof.rs
kimchi/src/circuits/constraints.rs
kimchi/tests/test_constraints.rs
scripts/bench-criterion-mina-circuits.sh

Addresses https://github.com/o1-labs/proof-systems/issues/3256
Due to an error in the `benches-mina-prover.yml` job (see 1) the pull request #3079 could be merged even though it broke the benches (see 2)
1. It was calling the script `scripts/bench-criterion-mina-circuits.sh` which has `set -ex` in the beginning, however the `tee` command after the pipe was masking failing `cargo run bench` -- it was not compiling yet CI was passing, https://github.com/o1-labs/proof-systems/actions/runs/15166787842/job/42646574074#step:8:78
2. By changing the index format, and thus making the pre-generated mina circuits non-deserializable anymore.
This PR fixes the issue:
1. Fixes the deserialization bug this issue was triggered by -- expecting `lazy_mode` bool on deserialization was not consistent with …

Fix failing mina benches in CI

---

Cargo.toml

It was introduced while investigating a bug when moving kimchi-stubs and plonk-wasm. It ended up being base64

Deps: remove some pinned versions

---

.github/workflows/test-export-vectors.yml
Cargo.lock
poseidon/export_test_vectors/Cargo.toml
poseidon/export_test_vectors/README.md
poseidon/export_test_vectors/src/main.rs

Part of simplifying the build process of o1js.
The final goal is to get rid of this directory: https://github.com/o1-labs/o1js/tree/main/src/bindings/crypto/test-vectors.

export-test-vectors: modestly improve + add in CI

---

CHANGELOG.md
signer/src/signature.rs

As for https://github.com/o1-labs/proof-systems/pull/3326, it is for the Rust node, as part of https://github.com/o1-labs/mina-rust/pull/1299/files

mina-signature: add method to return a dummy sig
